### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getMarker' of undefined

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/linter-ui-default#105]
[Enter steps to reproduce below:]

1. Unkown, it just started spamming this suddenly. Was using split panes if it makes a difference. Using bcaa088d01aa2a42ff61bbcfc88900513ffdaf7b as the version.

**Atom Version**: 1.9.0-beta0
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package, v0.0.3

### Stack Trace

Uncaught TypeError: Cannot read property 'getMarker' of undefined

```
At C:\Users\Landon Abney\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\decoration-manager.js:194

TypeError: Cannot read property 'getMarker' of undefined
    at DecorationManager.module.exports.DecorationManager.decorateMarker (C:\Users\Landon Abney\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\decoration-manager.js:194:65)
    at TextEditor.module.exports.TextEditor.decorateMarker (C:\Users\Landon Abney\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\text-editor.js:1525:37)
    at Editor.applyMarker (C:/Users/Landon Abney/Documents/GitHub-release/linter-ui-default/lib/editor.js:211:21)
    at _loop (C:/Users/Landon Abney/Documents/GitHub-release/linter-ui-default/lib/editor.js:193:12)
    at Editor.apply (C:/Users/Landon Abney/Documents/GitHub-release/linter-ui-default/lib/editor.js:180:70)
    at Editors.apply (C:/Users/Landon Abney/Documents/GitHub-release/linter-ui-default/lib/editors.js:68:28)
    at LinterUI.render (C:/Users/Landon Abney/Documents/GitHub-release/linter-ui-default/lib/main.js:70:18)
    at C:/Users/Landon Abney/Documents/GitHub-release/linter/lib/ui-registry.js:32:16
    at Set.forEach (native)
    at UIRegistry.didCalculateMessages (C:/Users/Landon Abney/Documents/GitHub-release/linter/lib/ui-registry.js:31:20)
    at C:/Users/Landon Abney/Documents/GitHub-release/linter/lib/main.js:84:23
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Landon Abney\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Landon Abney\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at MessageRegistry.update (C:/Users/Landon Abney/Documents/GitHub-release/linter/lib/message-registry.js:131:20)
    at later (C:\Users\Landon Abney\Documents\GitHub-release\linter\node_modules\sb-debounce\index.js:9:14)
```

### Commands

```
     -0:33.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:33.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:33.1.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -0:33.1.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:31 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:26.4.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:23.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -0:22.8.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:17.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:16.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:04.5.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:04.5.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:03.3.0 core:move-down (atom-text-editor.editor.is-focused)
 13x -0:02.7.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:00.8.0 core:select-up (atom-text-editor.editor.is-focused)
  2x -0:00.3.0 editor:move-line-up (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "atom-typescript",
      "linter-gjslint",
      "language-chef",
      "linter-scss-lint",
      "linter-pep8",
      "svn",
      "linter-csslint",
      "linter-flow",
      "linter-pylint"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "linter-ui-default": {
    "showPanel": true,
    "showProviderName": true
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.9 (active)
atom-beautify, v0.29.9 (active)
atom-typescript, v10.0.0 (inactive)
autocomplete-python, v1.8.1 (active)
docblockr, v0.7.3 (active)
editorconfig, v1.4.1 (active)
file-watcher, v0.4.0 (active)
highlight-selected, v0.11.2 (active)
language-chef, v0.9.0 (inactive)
language-cjson, v0.0.1 (active)
language-docker, v1.1.6 (active)
language-elixir, v0.14.0 (active)
language-fortran, v2.0.11 (inactive)
language-glsl, v2.0.1 (active)
language-haml, v0.24.0 (active)
language-ini, v1.16.0 (active)
language-postcss, v1.2.3 (active)
language-powershell, v2.1.1 (active)
language-r, v0.4.1 (active)
language-reg, v0.0.0 (active)
linter, v1.11.4 (active)
linter-alex, v3.2.0 (active)
linter-coffeelint, v1.1.2 (active)
linter-csslint, v1.3.2 (inactive)
linter-eslint, v7.2.4 (active)
linter-flake8, v1.13.2 (active)
linter-flow, v5.4.0 (inactive)
linter-htmlhint, v1.2.1 (active)
linter-js-yaml, v1.2.5 (active)
linter-jsonlint, v1.3.0 (active)
linter-markdown, v1.5.2 (active)
linter-perl, v0.8.0 (active)
linter-perlcritic, v0.3.3 (active)
linter-php, v1.2.0 (active)
linter-phpcs, v1.4.0 (active)
linter-phpmd, v1.5.0 (active)
linter-proselint, v3.1.1 (active)
linter-pylama, v0.4.4 (active)
linter-pylint, v1.2.1 (inactive)
linter-rails-best-practices, v0.2.2 (active)
linter-reek, v2.1.5 (active)
linter-rubocop, v0.4.7 (active)
linter-ruby, v1.2.2 (active)
linter-stylelint, v2.17.0 (active)
linter-tidy, v2.1.1 (active)
linter-ui-default, v0.0.3 (active)
mapfile-grammar, v0.1.0 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.24.7 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.1.1 (active)
minimap-selection, v4.4.0 (active)
pigments, v0.31.1 (active)
sequential-number, v0.4.0 (inactive)
seti-syntax, v1.0.1 (active)
seti-ui, v1.3.2 (active)
sort-lines, v0.14.0 (inactive)
svn, v0.0.12 (inactive)
tab-control, v0.6.9 (active)
toggle-quotes, v1.0.0 (inactive)
trailing-spaces, v0.3.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Closing as non-reproable Atom internals bug
