### ISSUE TITLE
Uncaught TypeError: range.intersectsWith is not a function

### ISSUE THREAD

**Issue by GlenCFL** [steelbrain/linter-ui-default#180]
Getting this exception when updating a package to use the Indie Linter 2.0. If the editor has a linter message set, then hovering over anything within that editor will result in this exception being thrown.

The range for the message seems to be valid, as the line decoration is working properly.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.1.0

### Stack Trace

Uncaught TypeError: range.intersectsWith is not a function

```
At C:\Users\GlenCFL\.atom\packages\linter-ui-default\lib\helpers.js:72

TypeError: range.intersectsWith is not a function
    at /packages/linter-ui-default/lib/helpers.js:72:53
    at Set.forEach (native)
    at filterMessagesByRangeOrPoint (/packages/linter-ui-default/lib/helpers.js:69:12)
    at Editor.updateTooltip (/packages/linter-ui-default/lib/editor/index.js:136:22)
    at /packages/linter-ui-default/lib/editor/index.js:91:14)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
  2x -3:06.3.0 linter:lint (atom-text-editor.editor.typescript-editor)
     -3:02.7.0 intentions:highlight (input.hidden-input)
     -3:02.7.0 core:undo (input.hidden-input)
     -3:01.5.0 linter:lint (atom-text-editor.editor.typescript-editor)
     -2:59.3.0 intentions:highlight (input.hidden-input)
     -2:59.3.0 core:undo (input.hidden-input)
     -2:56.2.0 intentions:highlight (input.hidden-input)
     -2:56.2.0 core:undo (input.hidden-input)
     -2:55.1.0 linter:lint (atom-text-editor.editor.typescript-editor)
  2x -2:53 intentions:highlight (input.hidden-input)
     -2:50.7.0 core:undo (input.hidden-input)
     -2:50.1.0 intentions:highlight (input.hidden-input)
     -2:50.1.0 core:undo (input.hidden-input)
     -2:48.9.0 editor:consolidate-selections (input.hidden-input)
     -2:48.9.0 core:cancel (input.hidden-input)
  9x -2:42.8.0 linter:lint (atom-text-editor.editor.typescript-editor)
```

### Non-Core Packages

```
atom-typescript 10.1.15 
autocomplete-cmake 0.3.1 
autocomplete-python 1.8.60 
busy-signal 1.3.0 
genesis-syntax 1.0.9 
genesis-ui 0.5.0 
intentions 1.1.2 
jsonlint 1.1.4 
language-batch 0.4.0 
language-cmake 0.3.0 
language-gn 0.2.0 
language-lua 0.9.11 
linter 2.1.0 
linter-ui-default 1.1.0 
path-of-exile-item-filter 1.0.6 
```

**Comment by GlenCFL** [comment]
This was an issue on my end. I was constructing the ranges within a Task, which resulted in only the start and end properties being set. Reconstructing the Range on the primary thread via Range.fromObject(range) prior to sending them to the linter fixed it.

Your code might want to do this internally to allow for range-compatible objects to be passed in, as most of the Atom API takes them. The two functions that were throwing with this issue were:
- lib/helpers.js -> filterMessagesByRangeOrPoint
- lib/tooltip/index.js -> isValid
