### ISSUE TITLE
Uncaught TypeError: validateDOMNesting.updatedAncestorInfo is not a function

### ISSUE THREAD

**Issue by CKrawczyk** [steelbrain/linter-ui-default#193]
[Enter steps to reproduce:]

1. writing a python script
2. this message pops up every few mins (not sure what is causing it)

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.1.0

### Stack Trace

Uncaught TypeError: validateDOMNesting.updatedAncestorInfo is not a function

```
At /Users/coleman/.atom/packages/linter-ui-default/node_modules/react-dom/lib/ReactDOMContainerInfo.js:27

TypeError: validateDOMNesting.updatedAncestorInfo is not a function
    at ReactDOMContainerInfo (/packages/linter-ui-default/node_modules/react-dom/lib/ReactDOMContainerInfo.js:27:52)
    at mountComponentIntoNode (/packages/linter-ui-default/node_modules/react-dom/lib/ReactMount.js:104:83)
    at ReactReconcileTransaction.perform (/packages/linter-ui-default/node_modules/react-dom/lib/Transaction.js:140:20)
    at batchedMountComponentIntoNode (/packages/linter-ui-default/node_modules/react-dom/lib/ReactMount.js:126:15)
    at ReactDefaultBatchingStrategyTransaction.perform (/packages/linter-ui-default/node_modules/react-dom/lib/Transaction.js:140:20)
    at Object.batchedUpdates (/packages/linter-ui-default/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/packages/linter-ui-default/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at Object._renderNewRootComponent (/packages/linter-ui-default/node_modules/react-dom/lib/ReactMount.js:320:18)
    at Object._renderSubtreeIntoContainer (/packages/linter-ui-default/node_modules/react-dom/lib/ReactMount.js:401:32)
    at Object.render (/packages/linter-ui-default/node_modules/react-dom/lib/ReactMount.js:422:23)
    at /packages/linter-ui-default/lib/tooltip/index.js:53:14)
    at Editor.updateTooltip (/packages/linter-ui-default/lib/editor/index.js:141:20)
    at /packages/linter-ui-default/lib/editor/index.js:91:14)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -0:58.3.0 core:move-down (input.hidden-input)
     -0:56.9.0 editor:newline (input.hidden-input)
     -0:56.3.0 snippets:next-tab-stop (input.hidden-input)
     -0:56.3.0 snippets:expand (input.hidden-input)
     -0:56.3.0 editor:indent (input.hidden-input)
  2x -0:55.8.0 core:backspace (input.hidden-input)
     -0:50.9.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  5x -0:49.4.0 core:backspace (input.hidden-input)
     -0:46.6.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:35.5.0 core:copy (input.hidden-input)
     -0:33.1.0 editor:newline (input.hidden-input)
     -0:32.9.0 snippets:next-tab-stop (input.hidden-input)
     -0:32.9.0 snippets:expand (input.hidden-input)
     -0:32.9.0 editor:indent (input.hidden-input)
  2x -0:32.3.0 core:backspace (input.hidden-input)
     -0:31.8.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-eco 0.2.0 
atom-espresso-soda-theme 0.10.0 
atom-monokai 0.10.9 
atom-terminal 0.8.0 
autocomplete-python 1.8.60 
busy-signal 1.3.0 
clipboard-plus 0.5.1 
color-picker 2.2.5 
emacs-web-view-syntax 0.0.0 
expose 0.14.0 
file-icons 2.0.17 
git-plus undefined 
git-time-machine 1.5.6 
grammar-token-limit 0.1.1 
intentions 1.1.2 
language-babel undefined 
language-iced-coffeescript 0.1.0 
language-latex 1.0.0 
language-lua 0.9.11 
linter 2.1.0 
linter-coffeelint 1.2.1 
linter-csslint 1.3.4 
linter-eslint 8.1.3 
linter-htmlhint 1.3.2 
linter-js-standard undefined 
linter-jsxhint 0.1.2 
linter-pycodestyle 2.0.0 
linter-python 3.1.1 
linter-stylint 2.2.6 
linter-ui-default 1.1.0 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-autohide 0.10.1 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-pigments 0.2.2 
open-in-browser 0.4.7 
pigments undefined 
python-debugger 0.2.0 
react 0.16.2 
Stylus 3.1.0 
terminal-panel 1.14.1 
tomorrow-ya 1.0.2 
```

**Comment by steelbrain** [comment]
Will investigate

**Comment by steelbrain** [comment]
Related https://github.com/facebooknuclide/react-for-atom/issues/13

**Comment by bneumann** [comment]
I am having the same issue with react. Unfortunatley it also prevents the linter UI from showing any help at all. Would you need my error report as well?

**Comment by steelbrain** [comment]
Anyone have any reliable steps on how to reproduce this issue reliably? I can't fix this if I can't repro it

**Comment by CKrawczyk** [comment]
I was able to fix this issues by moving my `~/.atom` folder, and re-installing all my packages (i.e. a clean install of atom).  My guess is one of my packages was conflicting in some way.

**Comment by steelbrain** [comment]
Great, closing based on above discussion
