### ISSUE TITLE
Uncaught TypeError: (0 , _helpers2.hasParent) is not a function

### ISSUE THREAD

**Issue by ozo2003** [steelbrain/linter-ui-default#204]
[Enter steps to reproduce:]

1. Start Atom

**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: XUbuntu 16.04.2
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.2.1

### Stack Trace

Uncaught TypeError: (0 , _helpers2.hasParent) is not a function

```
At /home/io/.atom/packages/linter-ui-default/lib/editor/index.js:129

TypeError: (0 , _helpers2.hasParent) is not a function
    at atom-text-editor.e (index.js:129:40)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Non-Core Packages

```
atom-autocomplete-php 0.22.2 
atom-beautify 0.29.17 
atom-clock 0.1.6 
atom-symfony2 0.2.1 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-php 0.3.7 
autoprefixer 3.6.1 
busy-signal 1.3.0 
docblockr 0.9.1 
emmet 2.4.3 
goto-definition 1.2.0 
highlight-selected 0.12.0 
intentions 1.1.2 
language-smarty 1.8.0 
linter 2.1.0 
linter-csslint 1.3.4 
linter-htmlhint 1.3.2 
linter-jshint 3.0.3 
linter-jsonlint 1.3.0 
linter-php 1.3.1 
linter-sass-lint 1.7.4 
linter-ui-default 1.2.1 
logo-file-icons 1.9.0 
minimap 4.26.8 
minimap-cursorline 0.2.0 
opened-files 0.3.6 
perfectionist 1.4.0 
php-cs-fixer 4.1.0 
php-integrator-autocomplete-plus 1.3.0 
php-twig 4.0.0 
pigments 0.39.0 
symfony-snippets 0.3.0 
synced-sidebar 0.4.3 
tabs-to-spaces 1.0.3 
tag 0.4.0 
tree-ignore 0.6.2 
```

**Comment by steelbrain** [comment]
Are you getting this everytime you start Atom or just once?

**Comment by ozo2003** [comment]
once in a while, mostly on startup

**Comment by steelbrain** [comment]
This is actually an Atom bug, nothing we can do about it other than recommend you to uninstall and then reinstall this package :)
