### ISSUE TITLE
Uncaught Error: Cannot find module '../helpers'

### ISSUE THREAD

**Issue by SaidElBakkali** [steelbrain/linter-ui-default#269]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Linux Mint
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.2.3

### Stack Trace

Uncaught Error: Cannot find module '../helpers'

```
At module.js:457

Error: Cannot find module '../helpers'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/opt/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter-ui-default/lib/tooltip/message.js:19:16)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter-ui-default/lib/tooltip/index.js:23:16)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter-ui-default/lib/editor/index.js:17:16)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter-ui-default/lib/editors.js:9:15)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at LinterUI.observeShowDecorations (/packages/linter-ui-default/lib/main.js:70:19)
```

### Commands

```
     -1:21.6.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:56.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-ui.theme-atom-dark-syntax)
```

### Non-Core Packages

```
atom-alignment 0.12.1 
atom-beautify 0.29.18 
atom-bootstrap3 1.2.12 
atom-css-unit-converter 1.1.1 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
busy-signal 1.3.0 
color-picker 2.2.5 
docblockr 0.9.4 
emmet 2.4.3 
exception-reporting 0.41.3 
file-icons 2.1.3 
hyperclick 0.0.40 
intentions 1.1.2 
jquery-snippets 11.0.0 
linter 2.1.3 
linter-csslint 1.3.4 
linter-php 1.3.2 
linter-phpcs 1.6.0 
linter-scss-lint 3.1.0 
linter-ui-default 1.2.3 
metrics 1.2.2 
minimap 4.27.1 
php-integrator-annotations 1.1.1 
php-integrator-autocomplete-plus 1.3.0 
php-integrator-base 2.1.11 
php-integrator-call-tips 1.2.1 
php-integrator-navigation 1.1.2 
php-integrator-tooltips 1.1.5 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
project-manager 3.3.4 
sync-settings 0.8.1 
```

**Comment by Arcanemagus** [comment]
Can you try re-installing the package?

**Comment by steelbrain** [comment]
Closing as there's been no response for about a month
