### ISSUE TITLE
Uncaught TypeError: uri.match is not a function

### ISSUE THREAD

**Issue by wBureshGitHub** [steelbrain/linter-ui-default#282]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Debian GNU/Linux
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.3.0

### Stack Trace

Uncaught TypeError: uri.match is not a function

```
At /usr/share/atom/resources/app.asar/src/project.js:330

TypeError: uri.match is not a function
    at Project.module.exports.Project.resolvePath (/app.asar/src/project.js:330:29)
    at Workspace.open (/app.asar/src/workspace.js:522:30)
    at /packages/linter-ui-default/lib/panel/index.js:25:20)
    at /packages/linter-ui-default/lib/main.js:48:24
    at Config.module.exports.Config.observeKeyPath (/app.asar/src/config.js:616:7)
    at Config.module.exports.Config.observe (/app.asar/src/config.js:141:21)
    at LinterUI.observeShowPanel (/packages/linter-ui-default/lib/main.js:46:42)
```

### Commands

```
     -0:33.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-Visual-Studio-2015-Dark-Theme.theme-atom-dark-ui)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.29.23 
atom-bootstrap4 1.4.0 
atom-clock 0.1.7 
atom-commander 0.9.0 
atom-html-preview 0.1.22 
atom-live-server 2.1.2 
atom-visual-studio-code-ui 1.3.4 
atomic-chrome 0.3.0 
autocomplete-paths 1.0.5 
bottom-dock 0.4.4 
browser-plus 0.0.87 
browser-refresh 0.9.0 
busy 0.7.0 
busy-signal 1.4.1 
clipboard-plus 0.5.1 
color-picker 2.2.5 
compare-files 0.8.0 
double-tag 0.8.0 
emmet 2.4.3 
file-icons 2.1.4 
git-time-machine 1.5.9 
gulp-manager 0.2.19 
gulp-snippets 0.6.2 
highlight-selected 0.13.1 
icon-fonts 2.16.2 
intentions 1.1.2 
lint 0.0.1 
linter 2.1.4 
linter-bootlint 1.0.4 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-jshint 3.0.3 
linter-markdown 4.0.1 
linter-sass-lint 1.7.4 
linter-scss-lint 3.1.0 
linter-ui-default 1.3.0 
linter-xmllint 1.4.1 
minimap 4.28.2 
multi-cursor 2.1.5 
open-in-browser 0.5.0 
open-in-browsers 0.0.19 
open-recent 5.0.0 
open-terminal-here 2.3.0 
pdf-view 0.57.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
project-viewer 1.0.14 
Remote-FTP 0.10.7 
sass-autocompile 0.13.3 
svg-preview 0.11.0 
svgo 2.8.5 
sync-settings 0.8.1 
todo-show 1.11.0 
Visual-Studio-2015-Dark-Theme 2.4.2 
```

**Comment by steelbrain** [comment]
Thank you for reporting this @wBureshGitHub

It seems like you installed the version of this package intended for Atom v1.17.0 on your v1.16.0. Please install the latest `1.2.x` version of this package intended for your version of Atom.

**Comment by Arcanemagus** [comment]
I'm curious how you got that installed, did Atom present you with that version as an update?

**Comment by wBureshGitHub** [comment]
Да. Вы правы. Я установил версию этого пакета для в1.17.0 на v1.16.0.
Спасибо, теперь все нормально.

**Comment by wBureshGitHub** [comment]
Yes. You're right. I installed the version of this package for v1.17.0 to v1.16.0.
Thanks, now it's fine.

**Comment by MoritzKn** [comment]
@Arcanemagus I got the error as well. In my case I had atom (v1.16) and atom-beta (v1.17) installed, opened atom-beta, updated linter-ui-default, closed atom-beta and then open atom.

**Comment by wBureshGitHub** [comment]
I deleted the atom 1.17beta, left only the atom 1.16. Problem still exists.

**Comment by steelbrain** [comment]
@wBureshGitHub here's the fix

```
apm uninstall linter-ui-default
apm install linter-ui-default
```

**Comment by steelbrain** [comment]
Whoops reopened accidentally
