### ISSUE TITLE
Uncaught TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by Tjoosten** [steelbrain/linter-ui-default#336]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'push' of undefined

```
At C:\Users\Gebruiker\.atom\packages\linter-ui-default\node_modules\react-dom\lib\ReactErrorUtils.js:51

TypeError: Cannot read property 'push' of undefined
    at Labels.toggleLabel (/packages/atom-github-issues/lib/github-view.js:395:36)
    at Object.invokeGuardedCallback (/packages/linter-ui-default/node_modules/react-dom/lib/ReactErrorUtils.js:26:5)
    at executeDispatch (/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginUtils.js:85:21)
    at Object.executeDispatchesInOrder (/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginUtils.js:108:5)
    at executeDispatchesAndRelease (/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginHub.js:54:10)
    at Array.forEach (native)
    at forEachAccumulated (/packages/linter-ui-default/node_modules/react-dom/lib/forEachAccumulated.js:24:9)
    at Object.processEventQueue (/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginHub.js:257:7)
    at runEventQueueInBatch (/packages/linter-ui-default/node_modules/react-dom/lib/ReactEventEmitterMixin.js:17:18)
    at /packages/linter-ui-default/node_modules/react-dom/lib/ReactEventEmitterMixin.js:28:5)
    at handleTopLevelImpl (/packages/linter-ui-default/node_modules/react-dom/lib/ReactEventListener.js:72:24)
    at ReactDefaultBatchingStrategyTransaction.perform (/packages/linter-ui-default/node_modules/react-dom/lib/Transaction.js:140:20)
    at Object.batchedUpdates (/packages/linter-ui-default/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/packages/linter-ui-default/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at dispatchEvent (/packages/linter-ui-default/node_modules/react-dom/lib/ReactEventListener.js:147:20)
```

### Commands

```
     -1:03.9.0 atom-github-issues:open (span.name.icon.icon-repo)
     -0:53.4.0 line-ending-selector:convert-to-LF (atom-text-editor.editor)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
an-old-hope-one-syntax 0.8.0 
atom-codeigniter3-modular-snippets 0.2.2 
atom-github-issues 0.4.3 
atom-jade 0.3.0 
atom-material-syntax 1.0.6 
atom-material-syntax-light 0.4.6 
awesome-material-syntax 0.6.0 
busy-signal 1.4.1 
C3PO-syntax 0.2.0 
code-peek 1.4.20 
colornamer 0.3.1 
conventional-changelog 0.1.0 
dark-flat-ui 1.2.4 
dracula-syntax 2.0.5 
dracula-theme 2.0.0 
duotone-dark-space-syntax 2.1.0 
floobits 0.32.10 
force-line-endings 0.1.1 
git-control 0.9.0 
github-atom-dark-syntax 0.3.2 
github-atom-light-syntax 0.3.2 
github-issues 0.8.3 
github-utils 1.6.0 
github-web 1.1.0 
imdone-atom 2.2.6 
intentions 1.1.2 
jade-beautify 0.1.5 
jekyll 2.1.0 
jekyll-snippets 0.3.2 
jekyll-syntax-highlighting 0.1.0 
language-blade 0.30.0 
language-rust 0.4.10 
laravel 0.7.1 
line-count 0.5.0 
linter 2.1.4 
linter-rust 0.8.0 
linter-ui-default 1.6.0 
my-github-profile 0.2.1 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
octocat-syntax 1.3.1 
one-dark-material-syntax 1.0.3 
outlander-syntax 2.0.0 
outlander-ui 1.4.0 
php-server 0.7.0 
php-twig 4.0.0 
qolor 0.4.1 
R2D2-syntax 0.2.0 
seti-syntax 1.1.3 
seti-ui 1.8.0 
todo-show 1.11.0 
yeti-syntax 0.1.2 
yeti-ui 0.1.6 
```

**Comment by steelbrain** [comment]
Hi @Tjoosten 

Looks like Atom's exception thrower package had a hickup. The stack trace suggests that the issue is in fact in `atom-github-issues` package. Could you report it there please?

Thanks!

**Comment by Tjoosten** [comment]
Alright!
