### ISSUE TITLE
Failed to activate linter-ui-default package when switching projects

### ISSUE THREAD

**Issue by philip-hodder** [steelbrain/linter-ui-default#343]
Hi

I get the following error whenever I switch projects using the "project-viewer" package. This doesn't happen on my Mac, which has almost the same packages installed. 

Thanks!

[Enter steps to reproduce:]

1. Open the "project-viewer" tree
2. Click on a new project to open it.

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.0

### Stack Trace

Failed to activate the linter-ui-default package

```
At Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Error (native)
    at StatusBarView.module.exports.StatusBarView.addRightTile (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/status-bar/lib/status-bar-view.js:90:1)
    at /packages/linter-ui-default/lib/status-bar/index.js:91:67
    at Config.module.exports.Config.observeKeyPath (~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:625:1)
    at Config.module.exports.Config.observe (~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:150:1)
    at StatusBar.attach (/packages/linter-ui-default/lib/status-bar/index.js:87:40)
    at /packages/linter-ui-default/lib/index.js:55:26
    at Set.forEach (native)
    at Object.consumeStatusBar (/packages/linter-ui-default/lib/index.js:54:20)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/service-hub/lib/provider.js:34:1)
    at ServiceHub.module.exports.ServiceHub.consume (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/service-hub/lib/service-hub.js:50:1)
    at Package.module.exports.Package.activateServices (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:454:1)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:256:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:99:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:642:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:374:1
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:644:1
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at Config.module.exports.Config.emitChangeEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:835:1)
    at Config.module.exports.Config.setRawValue (~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:621:1)
    at Config.module.exports.Config.set (~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:236:1)
    at Config.module.exports.Config.removeAtKeyPath (~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:386:1)
    at Package.module.exports.Package.enable (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:84:1)
    at PackageManager.module.exports.PackageManager.enablePackage (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:185:1)
    at list.forEach.pkg (/packages/project-viewer/src/packages.js:16:42)
    at Array.forEach (native)
    at /packages/project-viewer/src/packages.js:14:8)
    at /packages/project-viewer/src/project-view.js:303:22)
    at /packages/project-viewer/src/project-view.js:17:8)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
advanced-open-file 0.16.6 
api-docs 0.0.6 
ask-stack 2.2.0 
atom-beautify 0.29.26 
atom-html-preview 0.1.22 
atom-math 0.0.9 
atom-ungit 0.5.3 
atom-webbrowser 2.1.4 
atom-wrap-in-tag 0.6.0 
atomatigit 1.5.5 
autoclose-html 0.23.0 
autocomplete-date 0.4.0 
autocomplete-paths 1.0.5 
autocomplete-xml 0.9.4 
block-comment-plus 0.4.0 
build-tools 4.5.9 
build-tools-ant 0.1.1 
busy-signal 1.4.1 
character-table 0.4.3 
charcode-display 0.2.1 
color-picker 2.2.5 
custom-title 1.0.1 
dark-flat-ui 1.2.4 
dash 1.7.1 
document-outline 1.5.0 
dumb-quoter 0.1.0 
expose 0.14.0 
faker-atom 1.0.0 
fark-syntax 0.1.0 
file-icons 2.1.7 
filesize 3.0.0 
flex-tool-bar 0.12.0 
fonts 2.1.0 
git-plus 7.9.2 
git-time-machine 1.5.9 
hey-pane 1.0.0 
highlight-selected 0.13.1 
hybrid-reduced-contrast-syntax 0.0.1 
imdone-atom 2.2.6 
intentions 1.1.2 
isotope-ui 2.8.5 
language-diff 0.7.0 
language-jsoniq 1.8.0 
language-markdown 0.22.0 
language-pfm 0.82.0 
lines 0.13.1 
linter 2.1.4 
linter-autocomplete-jing undefined 
linter-htmlhint 1.3.3 
linter-js-cloudformation-yaml 2.2.1 
linter-jshint 3.1.2 
linter-ui-default 1.6.0 
linter-write-good 0.9.0 
markdown-document 0.2.1 
markdown-image-assistant 0.1.8 
markdown-preview-plus 2.4.9 
markdown-table-editor 0.5.2 
merge-conflicts 1.4.5 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
minimap-pigments 0.2.2 
minimap-split-diff 0.3.7 
minimap-titles 1.11.0 
native-ui 0.20.6 
nav-panel 0.0.11 
open-recent 5.0.0 
pdf-view 0.58.0 
pen-paper-coffee-syntax 0.14.9 
pigments 0.39.1 
pinned-tabs 1.1.0 
preview-inline 1.4.7 
project-viewer 1.1.2 
random 1.3.0 
smart-quotes-plus 2.1.0 
solarized-dark-ui 0.3.2 
split-diff 1.4.0 
Sublime-Style-Column-Selection 1.7.4 
svg-preview 0.11.0 
sync-settings 0.8.1 
tablr 1.8.3 
tag 0.5.0 
text-manipulation 0.6.0 
theme-switcher 1.1.0 
tidy-markdown 3.0.1 
todo-show 1.11.0 
tool-bar 1.1.0 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.4.0 
update-changelogs 0.1.0 
wordcount 2.10.4 
working-files 0.6.5 
xml-common-schemata 0.0.3 
Zen 0.18.0 
zentabs 0.8.8 
```

**Comment by philip-hodder** [comment]
I've just seen that this is something the project-viewer package has been looking at, so feel free to close if necessary. 

Thanks!

**Comment by Arcanemagus** [comment]
For reference, this is the related issue: https://github.com/jccguimaraes/atom-project-viewer/issues/154

**Comment by philip-hodder** [comment]
Got it, thanks!
