### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by mitzkia** [steelbrain/linter-ui-default#345]
[Enter steps to reproduce:]

1. There was opened several tabs
2. Used the "Close all tabs" option to close all of the tabs.

**Atom**: 1.19.0-dev-60c1b85ed x64
**Electron**: 1.6.9
**OS**: Ubuntu 17.04
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At /home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/text-editor-component.js:2124

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/text-editor-component.js:2124:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/text-editor-component.js:2120:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/text-editor-component.js:370:16)
    at TextEditorComponent.updateSync (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/text-editor-component.js:267:18)
    at TextEditorComponent.pixelPositionForScreenPosition (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/text-editor-component.js:191:18)
    at HTMLElement.pixelPositionForScreenPosition (/home/micek/micek_work/git_projects/atom/install/share/atom/resources/app/src/text-editor-element.js:243:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:163:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -0:08.8.0 tabs:close-all-tabs (div.title)
     -0:06.9.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:04.5.0 core:paste (div.lines)
```

### Non-Core Packages

```
atom-ctags 5.1.0 
atom-material-syntax 1.0.6 
busy-signal 1.4.1 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.2 
language-syslog-ng 0.0.6 
linter 2.1.4 
linter-pylama 0.8.20 
linter-ui-default 1.6.0 
python-isort 0.0.7 
seti-ui 1.8.0 
sort-lines 0.14.0 
split-diff 1.4.0 
symbols-tree-view 0.14.0 
```

**Comment by mitzkia** [comment]
Trying to create a fix reproduction.

**Comment by mitzkia** [comment]
Ok, I think I have a fix reproduction, but can not reproduce with --safe mode.

```
Atom    : 1.19.0-dev-60c1b85ed
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

1, atom was started from command line: `./atom`
2, create a new empty page with: File -> New file
3, From the following website [https://syslog-ng.gitbooks.io/getting-started/content/chapters/chapter_5/section_2.html](url) I copied the following snippet (from "Example: Java file" section):
```
Javaimport org.syslog_ng.*;

import java.io.*;
```
4, Pasted the snippet into the empty page with right menu (using the mouse)

With this reproduction steps, I can reproduce it in every time.

I hope it helps

**Comment by steelbrain** [comment]
You won't be able to repro this in safe mode if it's related to an API call in Atom internals that this package does because all community packages are disabled in safe mode

**Comment by mitzkia** [comment]
Ok, thank you.

**Comment by mitzkia** [comment]
I can reproduce the issue only enabling the linter and linter-ui-default packages.

**Comment by steelbrain** [comment]
From the stack trace, you are on a manually built version of Atom. Closing as Atom internal error as I'm unable to repro on both beta or stable and the stack traces originate from Atom internals as well
