### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by Kkthnx** [steelbrain/linter-ui-default#356]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.1

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At C:\Users\kkthn\AppData\Local\atom\app-1.19.0-beta0\resources\app\src\text-editor-component.js:2132

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/text-editor-component.js:2132:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/text-editor-component.js:2128:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/text-editor-component.js:373:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/text-editor-component.js:270:18)
    at TextEditorComponent.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/text-editor-component.js:194:18)
    at HTMLElement.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/text-editor-element.js:243:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:163:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -1:03.0 intentions:highlight (input.hidden-input)
     -1:02.9.0 core:save (input.hidden-input)
     -0:39.6.0 intentions:highlight (input.hidden-input)
undefined -0:39.4.0 core:undo (input.hidden-input)
  3x -0:32.7.0 intentions:highlight (input.hidden-input)
 42x -0:32.2.0 core:redo (input.hidden-input)
  5x -0:29.5.0 core:undo (input.hidden-input)
 11x -0:28 core:redo (input.hidden-input)
     -0:25.7.0 core:undo (input.hidden-input)
 74x -0:25.3.0 core:redo (input.hidden-input)
 15x -0:20.6.0 core:undo (input.hidden-input)
  3x -0:11.2.0 core:redo (input.hidden-input)
     -0:09.4.0 core:undo (input.hidden-input)
     -0:08.8.0 core:save (input.hidden-input)
     -0:06.4.0 intentions:highlight (input.hidden-input)
     -0:06.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.2 
language-lua-wow 0.2.0 
language-toc-wow 0.2.0 
linter 2.1.4 
linter-lua-findglobals 1.2.0 
linter-ui-default 1.6.1 
sort-lines 0.14.0 
```

**Comment by steelbrain** [comment]
You're on an Atom beta, so blame it on the beta and not linter-ui-default :)

**Comment by Kkthnx** [comment]
Alright, Ill revert and see what I get then. I completely forgot I was in Beta. Thank you.
