### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by datitisev** [steelbrain/linter-ui-default#358]
[Enter steps to reproduce:]

1. Fold anything
2. Try to unfold it. Sometimes it works, sometimes it errors. I've gotten this with JS and CSS code, even though I don't have linting for CSS.
  a. It sometimes also causes glitches in the UI when it does fold / unfold

      ![image](https://user-images.githubusercontent.com/6401250/27248349-455abd50-52d0-11e7-9641-35700ff8be80.png)

I think this is related https://github.com/atom/atom/issues/7305, as I seem to get both errors at the same time.

---

**Atom**: 1.19.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2250

TypeError: Cannot read property 'length' of undefined
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2250:33)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:9:50)
    at /packages/linter-ui-default/lib/editor/index.js:163:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -5:26.6.0 editor:consolidate-selections (input.hidden-input)
     -5:26.6.0 atom-minify:close-panel (input.hidden-input)
     -5:26.6.0 core:cancel (input.hidden-input)
     -0:54.4.0 emmet:toggle-comment (input.hidden-input)
     -0:54.4.0 editor:toggle-line-comments (input.hidden-input)
     -0:54.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:53.8.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:53.8.0 docblockr:parse-enter (input.hidden-input)
     -0:53.8.0 editor:newline (input.hidden-input)
     -0:53.4.0 core:paste (input.hidden-input)
     -0:52.2.0 auto-indent:apply (input.hidden-input)
  3x -0:49 find-and-replace:select-next (input.hidden-input)
     -0:41.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.29.26 
atom-handlebars 1.3.0 
atom-icons 0.2.2 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-minify 0.8.0 
atom-monokai 0.10.9 
atom-ternjs 0.18.3 
atom-typescript 11.0.3 
atom-uikit 1.2.2 
atom-visual-studio-code-ui 1.3.4 
auto-indent 0.5.0 
auto-indent-file 0.2.0 
autoprefixer 3.7.0 
better-handlebars 0.1.1 
busy 0.7.0 
busy-signal 1.4.3 
dash 1.7.1 
docblockr 0.10.3 
docs-snippets 0.8.0 
emmet 2.4.3 
es6-javascript 1.0.0 
express-complete 0.2.0 
git-control 0.9.0 
git-plus 7.9.3 
git-status 0.3.4 
guess-indent 0.1.0 
Handlebars 1.8.0 
hyperclick 0.0.40 
intentions 1.1.2 
jade 1.1.0 
javascript-snippets 1.2.1 
js-hyperclick 1.11.0 
language-pug 0.0.21 
language-vue 0.23.0 
linter 2.1.4 
linter-codeclimate 0.2.5 
linter-eslint 8.2.1 
linter-pug 1.3.1 
linter-ui-default 1.6.1 
material-ui 1.0.10 
minify-j-s 2.0.0 
monokai-seti 0.9.0 
nodejs-snippets 2.0.2 
php-twig 4.0.0 
pigments 0.39.1 
Quick-JavaScript 2.2.0 
quick-scroll 2.1.3 
rain-syntax 2.0.2 
react-es6-snippets 0.3.0 
scroll-percentage 1.2.1 
sepia-syntax 1.1.0 
seti-ui 1.8.0 
solarized-seti-ui 0.8.6 
spacegray-atom-dark-syntax 1.3.2 
split-diff 1.4.1 
travis-ci-status 1.3.1 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.4.0 
wakatime 7.0.3 
```

**Comment by steelbrain** [comment]
Hi @datitisev

You're on Atom beta so the error is coming from Atom internals, you could switch to the stable pipeline to ensure stability.
