### ISSUE TITLE
Uncaught Error: Cannot find module './delegate'

### ISSUE THREAD

**Issue by EdwardDiehl** [steelbrain/linter-ui-default#360]
Steps to reproduce

1. Install atom editor
2. Install `sync settings` package
3. Restore settings from my secure gist 

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.1

### Stack Trace

Uncaught Error: Cannot find module './delegate'

```
At /usr/share/atom/resources/app/static/<embedded>:1

Error: Cannot find module './delegate'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (usr/share/atom/resources/app/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-ui-default/lib/tooltip/index.js:19:17)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-ui-default/lib/editor/index.js:17:16)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-ui-default/lib/editors.js:9:15)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at LinterUI.observeShowDecorations (/packages/linter-ui-default/lib/main.js:61:19)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.0 
atom-material-syntax 1.0.6 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.4 
atom-ternjs 0.18.3 
atom-typescript 11.0.3 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
bottom-dock 0.4.4 
busy-signal 1.4.3 
docblockr 0.10.3 
editor-background 1.2.38 
file-icons 2.1.7 
goto-definition 1.3.3 
highlight-selected 0.13.1 
intentions 1.1.2 
language-elixir 0.19.0 
linter 2.2.0 
linter-elixir-credo 1.1.0 
linter-elixirc 1.6.0 
linter-eslint 8.2.1 
linter-htmlhint 1.3.3 
linter-rubocop 2.1.1 
linter-ruby 1.2.5 
linter-stylelint 3.10.0 
linter-tslint 1.6.0 
linter-ui-default 1.6.1 
linter-write-good 0.9.0 
markdown-preview-plus 2.4.9 
merge-conflicts 1.4.5 
node-debugger 1.10.1 
open-in-browsers 0.0.30 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
project-manager 3.3.5 
ruby-block 0.3.6 
script 3.15.0 
split-diff 1.4.1 
sync-settings 0.8.2 
```

**Comment by steelbrain** [comment]
This is a one time issue with the way updates work in Atom, please restart the editor to fix
