### ISSUE TITLE
Uncaught TypeError: Cannot read property '__reactInternalInstance$x2pwg47ht8m2z7kz40kg4aemi' of null

### ISSUE THREAD

**Issue by yvan-sraka** [steelbrain/linter-ui-default#362]
I just clicked on the "Conversation" view of the new GitHub PR integration.

**Atom**: 1.18.0 x64
**Electron**: 1.4.16
**OS**: "Arch Linux"
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.1

### Stack Trace

Uncaught TypeError: Cannot read property '__reactInternalInstance$x2pwg47ht8m2z7kz40kg4aemi' of null

```
At /home/yvan/.atom/packages/linter-ui-default/node_modules/react-dom/lib/ReactDOMComponentTree.js:113

TypeError: Cannot read property '__reactInternalInstance$x2pwg47ht8m2z7kz40kg4aemi' of null
    at Object.getClosestInstanceFromNode (/packages/linter-ui-default/node_modules/react-dom/lib/ReactDOMComponentTree.js:113:11)
    at findParent (/packages/linter-ui-default/node_modules/react-dom/lib/ReactEventListener.js:38:32)
    at handleTopLevelImpl (/packages/linter-ui-default/node_modules/react-dom/lib/ReactEventListener.js:67:28)
    at ReactDefaultBatchingStrategyTransaction.perform (/usr/lib/atom/node_modules/react-dom/lib/Transaction.js:143:20)
    at Object.batchedUpdates (/packages/linter-ui-default/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/packages/linter-ui-default/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at dispatchEvent (/packages/linter-ui-default/node_modules/react-dom/lib/ReactEventListener.js:147:20)
```

### Commands

```
     -7:09.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
  3x -2:58.6.0 core:backspace (input.hidden-input)
  2x -2:43.4.0 github:toggle-github-tab (input.hidden-input)
     -2:38.3.0 github:toggle-git-tab (input.hidden-input)
     -2:33.1.0 command-palette:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.1 
busy-signal 1.4.3 
editorconfig 2.2.2 
file-icons 2.1.7 
intentions 1.1.2 
language-babel 2.66.0 
language-haskell 1.12.1 
language-rust 0.4.10 
language-tex 0.4.0 
lines 0.13.1 
linter 2.2.0 
linter-clang 4.1.1 
linter-eslint 8.2.1 
linter-php 1.3.2 
linter-rust 0.8.0 
linter-scss-lint 3.1.0 
linter-tslint 1.6.0 
linter-ui-default 1.6.1 
pigments 0.39.1 
react-snippets 0.8.0 
```

**Comment by steelbrain** [comment]
Do you have any reliable steps to repro this?

**Comment by yvan-sraka** [comment]
Just use this build https://www.archlinux.org/packages/community/x86_64/atom/ with the `linter` package and click on the 'Conversation' button in the new GitHub pane: https://github.atom.io/

**Comment by steelbrain** [comment]
I'm getting something similar myself, but it's coming from the Github package, the GitHub package uses react too and Atom tends to use the same react across multiple packages

so not sure if what you're experiencing is coming from the Github package as well

**Comment by Arcanemagus** [comment]
It's likely that you have something that is changing `process.node_env` to `development`. This causes React to break itself in all sorts of "fun" and "interesting" ways because the React people think that's a good idea for some reason.

The reason this is being reported here is as @steelbrain said Atom is simply re-using the React version from this package.
