### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by iam4x** [steelbrain/linter-ui-default#364]
1. Go into a file with a merge confict
2. Enjoy the spam

![image](https://user-images.githubusercontent.com/893837/27336447-e10e656a-55cf-11e7-91e4-4f6ec7e4c701.png)

**Atom**: 1.19.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2250

TypeError: Cannot read property 'length' of undefined
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2250:33)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:9:50)
    at /packages/linter-ui-default/lib/editor/index.js:163:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -0:31 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:24.3.0 fuzzy-finder:toggle-file-finder (atom-pane.pane)
     -0:23.1.0 core:confirm (input.hidden-input)
  2x -0:16.2.0 core:cancel (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:10.6.0 editor:consolidate-selections (input.hidden-input)
     -0:10.6.0 core:cancel (input.hidden-input)
     -0:10.1.0 editor:consolidate-selections (input.hidden-input)
     -0:10.1.0 core:cancel (input.hidden-input)
  8x -0:08.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
afterglow-monokai-syntax 1.3.5 
ariake-dark-syntax 0.1.3 
atom-dark-fusion-syntax 2.2.0 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-monokai-flat 3.0.0 
atom-typescript 11.0.3 
atom-zeus-syntax 1.0.3 
atomic-chrome 0.3.0 
autocomplete-emojis 2.5.0 
autocomplete-modules 1.6.10 
autocomplete-paths 1.0.5 
ayu 0.1.0 
behave-theme 1.7.0 
blue-gray-syntax 0.4.0 
busy-signal 1.4.3 
cake-syntax 1.0.2 
chester-atom-syntax 0.2.0 
color-picker 2.2.5 
docker 0.7.0 
dockerletion 0.2.0 
editorconfig 2.2.2 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.7 
firewatch-syntax 1.1.1 
flatwhite-syntax 0.8.1 
genesis-syntax 1.0.9 
genesis-ui 0.5.0 
git-time-machine 1.5.9 
gloom 0.6.4 
gruvbox-plus-syntax 1.3.1 
hey-pane 1.0.0 
hyperclick 0.0.40 
intentions 1.1.2 
js-hyperclick 1.11.0 
language-babel 2.66.0 
language-csv 1.1.2 
language-docker 1.1.8 
language-postcss 1.3.1 
language-pug 0.0.21 
language-swift 0.5.0 
linter 2.2.0 
linter-alex 4.0.0 
linter-docker 0.2.0 
linter-eslint 8.2.1 
linter-flow 5.6.0 
linter-ui-default 1.6.1 
linter-write-good 0.9.0 
material-syntax 0.6.1 
minimap 4.28.2 
monokai-slate 0.6.0 
native-ui 0.21.0 
NewFirewatch-syntax 1.2.0 
nord-atom-ui 0.11.0 
nucleus-dark-ui 0.12.3 
one-dark-vivid-syntax 1.7.1 
pigments 0.39.1 
postcss-sorting 2.10.0 
predawn-syntax 1.0.4 
predawn-ui 1.0.7 
prettier-atom 0.33.0 
qolor 0.4.2 
ramda-syntax 1.0.4 
seti-ui 1.8.0 
single-click-open 0.2.2 
slime 2.1.0 
sort-lines 0.14.0 
tablr 1.8.3 
todo-show 1.11.0 
yuno-commit-plus 0.2.1 
```

**Comment by steelbrain** [comment]
You are on Atom dev, please revert to stable to fix this

**Comment by iam4x** [comment]
Instead of closing this, shall we not investigate the cause? And if it's a bug introduced by new API changes in Atom we should fix them before this version is released.

I'll investigate and get back to you.

**Comment by steelbrain** [comment]
Hi @iam4x 

You are absolutely right about keeping up with compatibility but the thing is, this is not a compatibility issue, just an Atom internal bug that'll hopefully be fixed in next beta so not sure how we can proof ourselves for that :)

**Comment by alexandernst** [comment]
Just happened to me as well. @steelbrain Maybe the bug will be fixed if an issue report is open? Isn't that how bugs get fixed? (people opening bug reports and devs looking at them and fixing them). That's the entire idea of releasing betas, right?
