### ISSUE TITLE
Error attempting to install the latest version of linter-ui-default

### ISSUE THREAD

**Issue by Spitfire1900** [steelbrain/linter-ui-default#369]
```U:\>apm install linter-ui-default
Installing linter-ui-default to C:\Users\johndoe\.atom\packages failed

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\johndoe\AppDat
a\Local\Temp\apm-install-dir-117523-6588-yfm1kw.21qq6w29\package.json'
npm WARN apm-install-dir-117523-6588-yfm1kw.21qq6w29 No description
npm WARN apm-install-dir-117523-6588-yfm1kw.21qq6w29 No repository field.
npm WARN apm-install-dir-117523-6588-yfm1kw.21qq6w29 No README data
npm WARN apm-install-dir-117523-6588-yfm1kw.21qq6w29 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\johndoe\\AppData\\Local\\atom\\app-1.18.0\\resources\\
app\\apm\\bin\\node.exe" "C:\\Users\\johndoe\\AppData\\Local\\atom\\app-1.18.0\\
resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\U
sers\\johndoe\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\johndoe\\.atom\\.
apmrc" "install" "C:\\Users\\johndoe\\AppData\\Local\\Temp\\d-117523-6588-f6uf0q
.4y00zlg14i\\package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "-
-global-style" "--msvs_version=2010"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\johndoe\AppData\Local\Temp\apm-install-dir-117523-6588-yf
m1kw.21qq6w29\node_modules\linter-ui-default
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\johndoe\AppData
\Local\Temp\apm-install-dir-117523-6588-yfm1kw.21qq6w29\node_modules\linter-ui-d
efault' -> 'C:\Users\johndoe\AppData\Local\Temp\apm-install-dir-117523-6588-yfm1
kw.21qq6w29\node_modules\.linter-ui-default.DELETE'
npm ERR!     at moveAway (C:\Users\johndoe\AppData\Local\atom\app-1.18.0\resourc
es\app\apm\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Users\johndoe\AppData\Local\atom\app-1.18.0\reso
urces\app\apm\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at C:\Users\johndoe\AppData\Local\atom\app-1.18.0\resources\app\apm
\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\johndoe\AppData
\Local\Temp\apm-install-dir-117523-6588-yfm1kw.21qq6w29\node_modules\linter-ui-d
efault' -> 'C:\Users\johndoe\AppData\Local\Temp\apm-install-dir-117523-6588-yfm1
kw.21qq6w29\node_modules\.linter-ui-default.DELETE'
npm ERR!     at Error (native)
npm ERR!  Error: EPERM: operation not permitted, rename 'C:\Users\johndoe\AppDat
a\Local\Temp\apm-install-dir-117523-6588-yfm1kw.21qq6w29\node_modules\linter-ui-
default' -> 'C:\Users\johndoe\AppData\Local\Temp\apm-install-dir-117523-6588-yfm
1kw.21qq6w29\node_modules\.linter-ui-default.DELETE'
npm ERR!     at moveAway (C:\Users\johndoe\AppData\Local\atom\app-1.18.0\resourc
es\app\apm\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Users\johndoe\AppData\Local\atom\app-1.18.0\reso
urces\app\apm\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at C:\Users\johndoe\AppData\Local\atom\app-1.18.0\resources\app\apm
\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\johndoe\AppData
\Local\Temp\apm-install-dir-117523-6588-yfm1kw.21qq6w29\node_modules\linter-ui-d
efault' -> 'C:\Users\johndoe\AppData\Local\Temp\apm-install-dir-117523-6588-yfm1
kw.21qq6w29\node_modules\.linter-ui-default.DELETE'
npm ERR!     at Error (native)
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\johndoe\AppData\Local\Temp\apm-install-dir-117523-6588-yfm
1kw.21qq6w29\npm-debug.log
```

**Comment by steelbrain** [comment]
APM bug, uninstall and reinstall the package to fix

**Comment by Spitfire1900** [comment]
Uninstall reinstall worked after also performing `apm clean`. Did not work otherwise.
