### ISSUE TITLE
Uncaught TypeError: Cannot read property 'row' of undefined

### ISSUE THREAD

**Issue by drawcard** [steelbrain/linter-ui-default#371]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.2

### Stack Trace

Uncaught TypeError: Cannot read property 'row' of undefined

```
At /Users/drawcard/.atom/packages/linter-ui-default/lib/helpers.js:175

TypeError: Cannot read property 'row' of undefined
    at /packages/linter-ui-default/lib/helpers.js:175:25
    at Array.sort (native)
    at sortMessages (/packages/linter-ui-default/lib/helpers.js:138:23)
    at ReactTable.render (/packages/linter-ui-default/node_modules/sb-react-table/lib/index.js:114:16)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/packages/linter-ui-default/node_modules/react-dom/lib/ReactCompositeComponent.js:798:30)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/packages/linter-ui-default/node_modules/react-dom/lib/ReactCompositeComponent.js:821:32)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/packages/linter-ui-default/node_modules/react-dom/lib/ReactCompositeComponent.js:745:36)
    at ReactCompositeComponentWrapper._performComponentUpdate (/packages/linter-ui-default/node_modules/react-dom/lib/ReactCompositeComponent.js:723:10)
    at ReactCompositeComponentWrapper.updateComponent (/packages/linter-ui-default/node_modules/react-dom/lib/ReactCompositeComponent.js:644:12)
    at ReactCompositeComponentWrapper.receiveComponent (/packages/linter-ui-default/node_modules/react-dom/lib/ReactCompositeComponent.js:546:10)
    at Object.receiveComponent (/packages/linter-ui-default/node_modules/react-dom/lib/ReactReconciler.js:124:22)
    at Object.updateChildren (/packages/linter-ui-default/node_modules/react-dom/lib/ReactChildReconciler.js:109:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/packages/linter-ui-default/node_modules/react-dom/lib/ReactMultiChild.js:211:28)
    at ReactDOMComponent._updateChildren (/packages/linter-ui-default/node_modules/react-dom/lib/ReactMultiChild.js:310:31)
    at ReactDOMComponent.updateChildren (/packages/linter-ui-default/node_modules/react-dom/lib/ReactMultiChild.js:297:12)
    at ReactDOMComponent._updateDOMChildren (/packages/linter-ui-default/node_modules/react-dom/lib/ReactDOMComponent.js:942:12)
    at ReactDOMComponent.updateComponent (/packages/linter-ui-default/node_modules/react-dom/lib/ReactDOMComponent.js:760:10)
    at ReactDOMComponent.receiveComponent (/packages/linter-ui-default/node_modules/react-dom/lib/ReactDOMComponent.js:722:10)
    at Object.receiveComponent (/packages/linter-ui-default/node_modules/react-dom/lib/ReactReconciler.js:124:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/packages/linter-ui-default/node_modules/react-dom/lib/ReactCompositeComponent.js:753:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (/packages/linter-ui-default/node_modules/react-dom/lib/ReactCompositeComponent.js:723:10)
    at ReactCompositeComponentWrapper.updateComponent (/packages/linter-ui-default/node_modules/react-dom/lib/ReactCompositeComponent.js:644:12)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (/packages/linter-ui-default/node_modules/react-dom/lib/ReactCompositeComponent.js:560:12)
    at Object.performUpdateIfNecessary (/packages/linter-ui-default/node_modules/react-dom/lib/ReactReconciler.js:156:22)
    at runBatchedUpdates (/packages/linter-ui-default/node_modules/react-dom/lib/ReactUpdates.js:150:21)
    at ReactReconcileTransaction.perform (/packages/linter-ui-default/node_modules/react-dom/lib/Transaction.js:143:20)
    at ReactUpdatesFlushTransaction.perform (/packages/linter-ui-default/node_modules/react-dom/lib/Transaction.js:143:20)
    at ReactUpdatesFlushTransaction.perform (/packages/linter-ui-default/node_modules/react-dom/lib/ReactUpdates.js:89:32)
    at Object.flushBatchedUpdates (/packages/linter-ui-default/node_modules/react-dom/lib/ReactUpdates.js:172:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/packages/linter-ui-default/node_modules/react-dom/lib/Transaction.js:209:25)
    at ReactDefaultBatchingStrategyTransaction.perform (/packages/linter-ui-default/node_modules/react-dom/lib/Transaction.js:156:16)
    at Object.batchedUpdates (/packages/linter-ui-default/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.enqueueUpdate (/packages/linter-ui-default/node_modules/react-dom/lib/ReactUpdates.js:200:22)
    at enqueueUpdate (/packages/linter-ui-default/node_modules/react-dom/lib/ReactUpdateQueue.js:24:16)
    at Object.enqueueSetState (/packages/linter-ui-default/node_modules/react-dom/lib/ReactUpdateQueue.js:218:5)
    at PanelComponent.ReactComponent.setState (/packages/linter-ui-default/node_modules/react/lib/ReactBaseClasses.js:64:16)
    at /packages/linter-ui-default/lib/panel/component.js:24:12
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PanelDelegate.update (/packages/linter-ui-default/lib/panel/delegate.js:79:18)
    at Panel.update (/packages/linter-ui-default/lib/panel/index.js:68:19)
    at LinterUI.render (/packages/linter-ui-default/lib/main.js:87:18)
    at /packages/linter/lib/ui-registry.js:32:16
    at Set.forEach (native)
    at UIRegistry.render (/packages/linter/lib/ui-registry.js:31:20)
    at /packages/linter/lib/main.js:187:23
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at MessageRegistry.update (/packages/linter/lib/message-registry.js:130:20)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -2:42 core:undo (input.hidden-input)
  2x -2:41 autocomplete-plus:confirm (input.hidden-input)
  3x -2:36 core:copy (input.hidden-input)
     -2:32.4.0 core:paste (input.hidden-input)
     -2:29.3.0 core:copy (input.hidden-input)
     -2:29.2.0 core:paste (input.hidden-input)
 16x -0:27.7.0 core:backspace (input.hidden-input)
  3x -0:17.6.0 core:move-down (input.hidden-input)
     -0:16.8.0 autocomplete-plus:confirm (input.hidden-input)
  4x -0:15.7.0 core:backspace (input.hidden-input)
  2x -0:13 core:copy (input.hidden-input)
     -0:10.3.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:10.3.0 editor:newline (input.hidden-input)
     -0:10 core:paste (input.hidden-input)
     -0:07.7.0 core:backspace (input.hidden-input)
     -0:06.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
aligner-php 1.1.1 
atom-beautify 0.30.1 
atom-wordpress 0.3.0 
autocomplete-bibtex 0.7.0 
autocomplete-paths 1.0.5 
autocomplete-php 0.3.7 
busy-signal 1.4.3 
code-peek 1.4.20 
color-picker 2.2.5 
duplicate-line-or-selection 0.9.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.7 
fonts 3.0.2 
html-to-css 0.2.2 
imdone-atom 2.2.6 
intentions 1.1.2 
less-autocompile 1.0.0 
linter 2.2.0 
linter-bootlint 1.0.4 
linter-eslint 8.2.1 
linter-htmlhint 1.3.3 
linter-js-yaml 1.2.7 
linter-jshint 3.1.2 
linter-jsonlint 1.3.0 
linter-just-say-no 0.7.3 
linter-less 2.6.0 
linter-liferay 3.0.0 
linter-markdownlint 1.0.1 
linter-php 1.3.2 
linter-processing 2.2.2 
linter-proselint 3.2.1 
linter-python 3.1.2 
linter-ruby 1.2.5 
linter-shellcheck 1.4.4 
linter-stylelint 3.10.0 
linter-ui-default 1.6.2 
linter-vagrant-validate 1.1.0 
linter-write-good 0.9.0 
linter-xmllint 1.4.3 
minimap 4.28.2 
minimap-find-and-replace 4.5.2 
minimap-linter 2.0.0 
minimap-pigments 0.2.2 
php-debug 0.2.4 
pigments 0.39.1 
project-manager 3.3.5 
sass-autocompile 0.13.3 
sort-lines 0.14.0 
sorter 1.1.0 
sync-settings 0.8.2 
wordpress-api 1.2.2 
wordpress-dictionary 4.4.0 
wordpress-suite 1.0.4 
wp-snippets 0.2.10 
```

**Comment by tstackhouse** [comment]
Updating to linter-ui-default v1.6.3  appears to have fixed this issue for me.

**Comment by steelbrain** [comment]
As no further info has been provided and we have a confirmation about it being fixed. Closing
