### ISSUE TITLE
atom.workspace.getCenter is not a function

### ISSUE THREAD

**Issue by ryanhiebert** [steelbrain/linter-ui-default#373]
This only started in the past couple days. I was on the atom beta, but I uninstalled the beta and am now using the latest stable, and it's still happening. #25 directed to create a new issue, I didn't see another recent one that this seemed to be a duplicate of.

1. Open atom
2. ...
3. complain

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.2

### Stack Trace

Failed to activate the linter-ui-default package

```
At atom.workspace.getCenter is not a function

TypeError: atom.workspace.getCenter is not a function
    at /packages/linter-ui-default/lib/status-bar/index.js:39:43)
    at /packages/linter-ui-default/lib/main.js:33:22)
    at Object.provideUI (/packages/linter-ui-default/lib/index.js:36:22)
    at Package.module.exports.Package.activateServices (/app.asar/src/package.js:393:69)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:221:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:812:28
```

### Commands

```
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-python-run 0.7.3 
atom-python-test 0.7.0 
atom-python-virtualenv 0.14.0 
autocomplete-python 1.9.1 
autoupdate-packages 1.3.1 
build-cargo 2.0.0 
busy-signal 1.4.3 
dockerletion 0.2.0 
file-type-icons 1.3.4 
gloom 0.6.4 
intentions 1.1.2 
language-docker 1.1.8 
language-ini 1.19.0 
language-javascript-jsx 0.3.7 
language-rust 0.4.10 
language-sphinx 0.1.6 
linter 2.2.0 
linter-docker 0.2.0 
linter-eslint 8.2.1 
linter-flake8 2.2.1 
linter-js-standard 3.9.1 
linter-js-yaml 1.2.7 
linter-rust 0.8.0 
linter-ui-default 1.6.2 
logo-file-icons 1.11.0 
merge-conflicts 1.4.5 
multi-cursor 2.1.5 
prettier-atom 0.34.0 
python-tools 0.6.9 
rustfmt 0.1.3 
sphinx-preview 0.1.1 
theme-switch 0.4.0 
```

**Comment by steelbrain** [comment]
Hi @ryanhiebert 

You might want to update your Atom version. We may have forgot to bump the minimum required Atom version for the update

**Comment by ryanhiebert** [comment]
Thanks, that worked. I didn't realize that the Ubuntu package didn't auto-update, or at least update with apt. Sorry for the noise.
