### ISSUE TITLE
Uncaught Error: Cannot find module 'sb-event-kit'

### ISSUE THREAD

**Issue by llucasapolinario** [steelbrain/linter-ui-default#387]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.3

### Stack Trace

Uncaught Error: Cannot find module 'sb-event-kit'

```
At C:\Users\apoli\AppData\Local\atom\app-1.18.0\resources\app\static\<embedded>:1

Error: Cannot find module 'sb-event-kit'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-ui-default/node_modules/disposable-event/lib/index.js:3:19)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-ui-default/lib/editor/index.js:3:35)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-ui-default/lib/editors.js:3:43)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at LinterUI.observeShowDecorations (/packages/linter-ui-default/lib/main.js:51:19)
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
linter 2.2.0 
linter-php 1.3.2 
linter-ui-default 1.6.3 
platformio-ide-terminal 2.5.3 
```

**Comment by steelbrain** [comment]
Hi @llucasapolinario 

It looks like APM is at it again, fix is

```
apm uninstall linter
apm install linter
```
