### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by PipC** [steelbrain/linter-ui-default#388]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta4 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.3

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\pipch\AppData\Local\atom\app-1.19.0-beta4\resources\app\src\text-editor-component.js:2266

TypeError: Cannot read property 'length' of undefined
    at TextEditorComponent.screenPositionForPixelPosition (~/AppData/Local/atom/app-1.19.0-beta4/resources/app/src/text-editor-component.js:2266:33)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:9:50)
    at /packages/linter-ui-default/lib/editor/index.js:168:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -5:02.5.0 tree-view:remove (li.file.entry.list-item.selected)
     -4:57 intentions:highlight (input.hidden-input)
     -4:56.6.0 core:copy (input.hidden-input)
     -1:52.8.0 intentions:highlight (input.hidden-input)
     -1:52.7.0 core:select-all (input.hidden-input)
     -1:52.5.0 intentions:highlight (input.hidden-input)
     -1:52.4.0 core:paste (input.hidden-input)
     -1:39.8.0 intentions:highlight (input.hidden-input)
     -1:39.7.0 core:paste (input.hidden-input)
     -1:37.4.0 intentions:highlight (input.hidden-input)
     -1:37.1.0 core:save (input.hidden-input)
     -0:50.9.0 intentions:highlight (input.hidden-input)
     -0:50.7.0 core:save (input.hidden-input)
     -0:08.8.0 tree-view-filter:activate (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
Atom-Bash-Snippets 0.0.3 
atom-beautify 0.30.4 
atom-grails 1.0.1 
atom-material-ui 2.0.4 
atom-shell-commands 1.5.0 
busy-signal 1.4.3 
file-types 0.5.5 
fold-functions 0.5.0 
format-sql 0.3.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
incremental-search 5.2.2 
intentions 1.1.2 
language-apache 1.7.0 
language-awk 0.1.12 
language-batch 0.4.0 
language-generic-config 1.3.0 
language-groovy 0.7.0 
language-tsql 0.19.0 
language-vb 0.1.0-pre1 
language-vba 0.2.5 
language-vue 0.23.0 
language-vue-component 0.5.0 
linter 2.2.0 
linter-ui-default 1.6.3 
minimap 4.29.0 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
quick-query-mssql 0.1.4 
split-diff 1.4.3 
Sublime-Style-Column-Selection 1.7.4 
tree-view-filter 0.5.3 
vue-autocomplete 0.1.1 
vue-format 0.4.0 
vue-snippets 0.6.0 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by steelbrain** [comment]
You're on Atom beta and the stack trace is coming from Atom Internals.

Closing as external

**Comment by Arcanemagus** [comment]
To provide a bit more context, it's _likely_ this is fixed by https://github.com/atom/atom/pull/15051, once the next beta lands including that this should hopefully not show up again. Do you happen to know how you triggered this so it can be tested as to whether that fixes it?

**Comment by Ben3eeE** [comment]
@Arcanemagus FYI: I get redirected here when reproducing https://github.com/atom/atom/issues/15441 if you have any other issues for this open.

**Comment by Arcanemagus** [comment]
@Ben3eeE That's very odd, the title is different from https://github.com/atom/atom/issues/15441, which means the error reporting package _shouldn't_ be matching to this issue, are you sure the stack trace and/or title is the same as in https://github.com/atom/atom/issues/15441?

**Comment by Ben3eeE** [comment]
@Arcanemagus It throws both https://github.com/atom/atom/issues/15441 and this.

**Comment by Arcanemagus** [comment]
I can reproduce https://github.com/atom/atom/issues/15441 following the steps in the issue, but I don't get any errors from `linter-ui-default` when it happens. Do you have a provider that is giving messages on that document?

**Comment by Ben3eeE** [comment]
I get errors from `linter-ui-default` only after `Atom Core` has been throwing for a while and I am selecting text in the document. I am reproducing with the markdown file linked in the issue. I currently only have the `linter-js-standard` provider.

**Comment by Arcanemagus** [comment]
For reference, the two errors seen by @Ben3eeE were the stack trace from this issue with slightly different line numbers:

```
TypeError: Cannot read property 'length' of undefined
    at TextEditorComponent.screenPositionForPixelPosition (C:\Users\bene\AppData\Local\atom\app-1.19.4\resources\app\src\text-editor-component.js:2367:33)
    at getBufferPositionFromMouseEvent (file:///C:/Users/bene/.atom/packages/linter-ui-default/lib/editor/helpers.js:9:50)
    at HTMLElement.<anonymous> (file:///C:/Users/bene/.atom/packages/linter-ui-default/lib/editor/index.js:168:29)
    at later (C:\Users\bene\.atom\packages\linter\node_modules\sb-debounce\index.js:9:14)
```

And a new stack trace that is probably also Atom Core, but triggered here:

```
TypeError: Cannot read property 'id' of undefined
    at TextEditorComponent.addBlockDecorationToRender (C:\Users\bene\AppData\Local\atom\app-1.19.4\resources\app\src\text-editor-component.js:1185:67)
    at TextEditorComponent.addDecorationToRender (C:\Users\bene\AppData\Local\atom\app-1.19.4\resources\app\src\text-editor-component.js:1026:22)
    at decorationsByMarker.forEach (C:\Users\bene\AppData\Local\atom\app-1.19.4\resources\app\src\text-editor-component.js:995:20)
    at Map.forEach (native)
    at TextEditorComponent.queryDecorationsToRender (C:\Users\bene\AppData\Local\atom\app-1.19.4\resources\app\src\text-editor-component.js:990:31)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (C:\Users\bene\AppData\Local\atom\app-1.19.4\resources\app\src\text-editor-component.js:381:16)
    at TextEditorComponent.updateSync (C:\Users\bene\AppData\Local\atom\app-1.19.4\resources\app\src\text-editor-component.js:276:16)
    at TextEditorComponent.pixelPositionForScreenPosition (C:\Users\bene\AppData\Local\atom\app-1.19.4\resources\app\src\text-editor-component.js:208:18)
    at HTMLElement.pixelPositionForScreenPosition (C:\Users\bene\AppData\Local\atom\app-1.19.4\resources\app\src\text-editor-element.js:243:32)
    at getBufferPositionFromMouseEvent (file:///C:/Users/bene/.atom/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at HTMLElement.<anonymous> (file:///C:/Users/bene/.atom/packages/linter-ui-default/lib/editor/index.js:168:29)
    at later (C:\Users\bene\.atom\packages\linter\node_modules\sb-debounce\index.js:9:14)
```
