### ISSUE TITLE
Search in a big file: Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by setalosas** [steelbrain/linter-ui-default#391]
I get this error quite often these days. In most cases it says it's already reported, this one is different.

1. I edit a rather big (960k) html file.
2. I press F3 for next search result.
2. If I click 'Close all', the boxes disappear, but immediately new boxes are coming up with the same message, so I have to exit and restart Atom.

![image](https://user-images.githubusercontent.com/21111643/28622357-8883ba9c-7214-11e7-9244-9635d313b335.png)

**Atom**: 1.19.0-beta5 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.3

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At C:\Users\chuck\AppData\Local\atom\app-1.19.0-beta5\resources\app\src\text-editor-component.js:2148

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.19.0-beta5/resources/app/src/text-editor-component.js:2148:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.19.0-beta5/resources/app/src/text-editor-component.js:2144:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.19.0-beta5/resources/app/src/text-editor-component.js:378:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.19.0-beta5/resources/app/src/text-editor-component.js:269:18)
    at TextEditorComponent.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.19.0-beta5/resources/app/src/text-editor-component.js:195:18)
    at HTMLElement.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.19.0-beta5/resources/app/src/text-editor-element.js:243:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:168:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -4:40.3.0 editor:newline (input.hidden-input)
     -4:37.7.0 core:move-up (input.hidden-input)
     -4:37.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -4:37.5.0 editor:newline (input.hidden-input)
 19x -4:30.1.0 intentions:highlight (input.hidden-input)
     -4:29 core:copy (input.hidden-input)
     -3:51.8.0 intentions:highlight (input.hidden-input)
     -3:51.3.0 core:copy (input.hidden-input)
  2x -3:46.5.0 editor:newline (input.hidden-input)
     -3:45.9.0 core:paste (input.hidden-input)
     -1:46.8.0 open-recent:File1-Cː\Users\chuck\Downloads\yyyyyyyyyy\(23) History ‐ YouTube.html (input.hidden-input)
     -1:18.4.0 intentions:highlight (input.hidden-input)
     -1:18.2.0 find-and-replace:show (input.hidden-input)
     -1:15.9.0 editor:move-to-first-character-of-line (input.hidden-input)
     -1:15.3.0 core:confirm (input.hidden-input)
 47x -0:43.3.0 find-and-replace:find-next (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server 2.1.2 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.4 
atom-runner 2.7.1 
atom-solarized-dark-ui 0.28.1 
atom-terminal-panel 4.4.4 
autoclose-html 0.23.0 
browser-plus 0.0.98 
busy-signal 1.4.3 
color-picker 2.2.5 
custom-title 1.0.1 
file-icons 2.1.9 
flex-tool-bar 0.12.0 
fonts 3.0.2 
glowing-cursor 0.1.2 
hyperclick 0.1.2 
icon-fonts 2.16.2 
intentions 1.1.2 
ionic-preview 0.7.0 
jekyll 2.1.0 
jslint 1.5.1 
less-autocompile 1.0.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-js-standard 3.9.1 
linter-jshint 3.1.5 
linter-php 1.3.2 
linter-ui-default 1.6.3 
material-syntax 0.6.1 
material-ui 1.0.10 
materialize-css 0.3.0 
minimap 4.29.2 
minimap-autohide 0.10.1 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-pigments 0.2.2 
multi-cursor-plus 1.2.0 
open-in-browser 0.5.2 
open-recent 5.0.0 
php-debug 0.2.4 
php-integrator-autocomplete-plus 1.6.0 
php-integrator-base 3.0.1 
php-integrator-navigation 1.2.1 
pigments 0.40.0 
platformio-ide-terminal 2.5.3 
pretty-json 1.6.4 
project-manager 3.3.5 
project-plus 1.0.0 
project-viewer 1.2.0 
quick-highlight 0.10.0 
save-session 0.15.7 
select-rectangle 1.0.2 
solarized-dark-apparent-ui-successor 0.2.0 
solarized-dark-ui 0.3.2 
tool-bar 1.1.0 
tool-bar-main 0.0.10 
toolbar-iconshortcuts 3.13.0 
```

**Comment by steelbrain** [comment]
The stack trace is coming from Atom so I'd say a bug in Atom, plus you're on a beta

**Comment by DanFreed** [comment]
I started seeing this today as well:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.3


### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2148

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2148:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2144:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:378:16)
    at TextEditorComponent.updateSync (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:269:18)
    at TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:195:18)
    at HTMLElement.pixelPositionForScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-element.js:243:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:168:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -6:36.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -6:22.8.0 core:close (input.hidden-input)
  2x -3:54.3.0 pane:show-next-item (input.hidden-input)
     -3:53.4.0 symbols-view:toggle-file-symbols (input.hidden-input)
     -3:51.1.0 core:confirm (input.hidden-input)
  3x -3:25.8.0 pane:show-previous-item (input.hidden-input)
     -3:24.9.0 pane:show-next-item (input.hidden-input)
     -3:22.6.0 symbols-view:toggle-file-symbols (input.hidden-input)
     -3:20.6.0 core:confirm (input.hidden-input)
  3x -0:51.1.0 pane:show-next-item (input.hidden-input)
     -0:50.4.0 symbols-view:toggle-file-symbols (input.hidden-input)
     -0:48.5.0 core:confirm (input.hidden-input)
     -0:36.8.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
```

### Non-Core Packages

```
astromac-ui 0.1.0 
atom-beautify 0.30.4 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-text-transformer 0.7.0 
autocomplete-bash-builtins 0.3.5 
autocomplete-paths 1.0.5 
autohide-tree-view 0.25.1 
beacon-ui 0.5.0 
busy-signal 1.4.3 
color-picker 2.2.5 
dlg 0.0.0 
epic-lib 0.0.1 
file-icons 2.1.9 
find-list 0.3.0 
googlesearch 1.5.0 
highlight-selected 0.13.1 
intentions 1.1.2 
isotope-ui 2.8.5 
keymaps undefined 
lib undefined 
lines 0.13.1 
linter 2.2.0 
linter-perl-check-syntax 0.8.1 
linter-ui-default 1.6.3 
menus undefined 
monokai-seti 0.9.0 
monokai-seti-dfreed 0.9.0 
native-ui 0.21.0 
package-cop 0.2.10 
perldoc 0.0.2 
perltidy 4.0.0 
remote-atom 1.3.10 
save-session undefined 
sepia-syntax 1.1.0 
seti-ui 1.9.0 
seti-ui-red 0.13.0 
solarized-dark-syntax-custom 1.0.0 
spec undefined 
status-bar-stats 1.0.4 
styles undefined 
Sublime-Style-Column-Selection 1.7.4 
svndiff 0.0.0 
symbol-gen 1.3.1 
symbols-tree-view 0.14.0 
todo-show 1.11.0 
unity-ui 2.1.11 
vim-mode-plus 0.95.0 
xml-formatter 0.11.0 
yosemate-ui 0.7.1 
```

**Comment by setalosas** [comment]
Should I post it there then? (I just pressed the 'create issue' button in the error message.)

**Comment by steelbrain** [comment]
Yes, you should search if there's an Issue on the Atom repo with a similar stack trace already, if not create a new one. Thanks for taking the time to report this 👍
