### ISSUE TITLE
Uncaught Error: Cannot find module './ReactComponent'

### ISSUE THREAD

**Issue by asaramet** [steelbrain/linter-ui-default#392]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.4.16
**OS**: "Arch Linux"
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.3

### Stack Trace

Uncaught Error: Cannot find module './ReactComponent'

```
At module.js:457

Error: Cannot find module './ReactComponent'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/lib/atom/src/module-cache.js:350:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/linter-ui-default/node_modules/react/lib/React.js:16:22)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/linter-ui-default/node_modules/react/react.js:3:18)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/linter-ui-default/lib/tooltip/index.js:9:14)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/linter-ui-default/lib/editor/index.js:5:71)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/linter-ui-default/lib/editors.js:3:43)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at LinterUI.observeShowDecorations (/packages/linter-ui-default/lib/main.js:51:19)
```

### Commands

```
  4x -0:17.8.0 vim-mode-plus:move-up (input.hidden-input)
```

### Non-Core Packages

```
atom-typescript 11.0.6 
busy-signal 1.4.3 
emmet 2.4.3 
ex-mode 0.15.0 
git-plus 7.9.3 
intentions 1.1.2 
language-docker 1.1.8 
language-latex 1.0.0 
language-nginx 0.8.0 
latextools 0.8.5 
linter 2.2.0 
linter-ui-default 1.6.3 
vim-mode-plus 0.95.0 
```

**Comment by steelbrain** [comment]
Looks like an Atom cache issue, solutions that work mostly

1. Restart your Editor
2. Uninstall and reinstall the package
2. Rename `.atom` in your `$HOME` to `.atom-bkp` and reinstall the packages

**Comment by aminya** [comment]
Closing since already fixed.
