### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by Geo1088** [steelbrain/linter-ui-default#395]
Steps to reproduce:

1. Open Atom with `linter` and `linter-ui-default` installed and enabled.
2. See error notification prompting me to create this issue.

This occurs even when the only non-core packages enabled are `linter` and `linter-ui-standard`. I'm guessing this is a beta thing.

**Atom**: 1.19.0-beta5 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.3

### Stack Trace

Uncaught SyntaxError: Invalid or unexpected token

```
At C:\Users\George\AppData\Local\atom\app-1.19.0-beta5\resources\app\src\native-compile-cache.js:97

SyntaxError: Invalid or unexpected token
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.0-beta5/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.0-beta5/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.19.0-beta5/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.19.0-beta5/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-ui-default/lib/editors.js:3:43)
    at /packages/linter-ui-default/lib/editors.js:90:25)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.0-beta5/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.0-beta5/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.19.0-beta5/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.19.0-beta5/resources/app/src/native-compile-cache.js:66:33)
    at LinterUI.observeShowDecorations (/packages/linter-ui-default/lib/main.js:51:19)
```

### Commands

```
     -0:16.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-clock 0.1.13 
auto-detect-indentation 1.3.0 
busy-signal 1.4.3 
chrome-color-picker 0.8.0 
counter 0.3.5 
file-icons 2.1.9 
git-time-machine 1.5.9 
github-atom-light-syntax 0.5.0 
highlight-bad-chars 1.0.7 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-js-standard 3.9.3 
linter-sass-lint 1.7.4 
linter-ui-default 1.6.3 
minimap 4.29.3 
monokai 0.24.0 
nord-atom-syntax 0.9.1 
pretty-json 1.6.4 
sort-lines 0.14.0 
```

**Comment by steelbrain** [comment]
Good Ol' Atom Internals bug.

Fix is to run

```
apm uninstall linter-ui-default
apm install linter-ui-default
```

**Comment by Geo1088** [comment]
Didn't work for me. Alt-F4'd Atom, reinstalled from powershell (a couple times to make sure), and I still get the error on startup.

**Comment by steelbrain** [comment]
Rename your `.atom` to `.atom-bkp` and then install, sometimes Atom cache messes up

**Comment by Geo1088** [comment]
Looks like that did it, thanks.
