### ISSUE TITLE
Uncaught TypeError: TreeView is not a constructor

### ISSUE THREAD

**Issue by gausie** [steelbrain/linter-ui-default#396]
[Enter steps to reproduce:]

1. Typing in a file that has linting enabled. This also happened in 1.16, but I upgraded to also upgrade linter-ui-default. Still experiencing however, unfortunately.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 17.04
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.3

### Stack Trace

Uncaught TypeError: TreeView is not a constructor

```
At /home/gausie/.atom/packages/linter-ui-default/lib/main.js:81

TypeError: TreeView is not a constructor
    at LinterUI.render (/packages/linter-ui-default/lib/main.js:81:23)
    at /packages/linter/lib/ui-registry.js:32:16
    at Set.forEach (native)
    at UIRegistry.render (/packages/linter/lib/ui-registry.js:31:20)
    at /packages/linter/lib/main.js:187:23
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at MessageRegistry.update (/packages/linter/lib/message-registry.js:130:20)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
  9x -0:41.4.0 core:move-right (input.hidden-input)
     -0:39.7.0 core:backspace (input.hidden-input)
 22x -0:38.7.0 core:move-left (input.hidden-input)
     -0:33.3.0 core:backspace (input.hidden-input)
 29x -0:33.1.0 core:move-right (input.hidden-input)
  6x -0:31.4.0 core:backspace (input.hidden-input)
     -0:30.3.0 intentions:highlight (input.hidden-input)
     -0:30.1.0 core:save (input.hidden-input)
  6x -0:27.3.0 core:select-left (input.hidden-input)
     -0:26.3.0 intentions:highlight (input.hidden-input)
     -0:26.2.0 core:cut (input.hidden-input)
     -0:25.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -0:25.5.0 core:move-left (input.hidden-input)
  2x -0:24.2.0 core:backspace (input.hidden-input)
     -0:23.4.0 intentions:highlight (input.hidden-input)
     -0:23.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
file-icons 2.1.9 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.3 
multi-cursor 2.1.5 
sort-lines 0.14.0 
```

**Comment by steelbrain** [comment]
Hi @gausie 

Did you restart Atom to make sure it wasn't a one-time bug?

**Comment by gausie** [comment]
Yes, and restarted my computer.

**Comment by steelbrain** [comment]
Ah this sounds like an issue with Atom cache then, this should fix it

- Close all Atom instances
- Rename `.atom` in your `$HOME` to `.atom-bkp`
- Reinstall the packages you want
- Start Atom

**Comment by aminya** [comment]
Closing since it is already fixed
