### ISSUE TITLE
Uncaught TypeError: paneItem.getURI is not a function

### ISSUE THREAD

**Issue by MeDean** [steelbrain/linter-ui-default#408]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 17.04
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.3

### Stack Trace

Uncaught TypeError: paneItem.getURI is not a function

```
At /home/dean/.atom/packages/linter-ui-default/lib/helpers.js:41

TypeError: paneItem.getURI is not a function
    at getActiveTextEditor (/packages/linter-ui-default/lib/helpers.js:41:65)
    at /packages/linter-ui-default/lib/panel/delegate.js:34:26
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/usr/share/atom/resources/app/src/pane-container.js:280:26)
    at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app/src/pane.js:318:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/usr/share/atom/resources/app/src/pane.js:454:25)
    at Pane.module.exports.Pane.activateNextItem (/usr/share/atom/resources/app/src/pane.js:409:27)
    at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app/src/pane.js:607:22)
    at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app/src/pane.js:685:22)
    at TabBarView.module.exports.TabBarView.closeTab (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:340:32)
    at HTMLDivElement.TabView.didClickCloseIcon (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:228:25)
```

### Commands

```
     -5:58.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-clock 0.1.13 
javascript-snippets 1.2.1 
atom-runner 2.7.1 
simplified-chinese-menu 5.3.4 
atom-ternjs 0.18.3 
vue2-autocomplete 0.1.0-alpha.4 
autocomplete-paths 1.0.5 
autocomplete-php 0.3.7 
autocomplete-python 1.9.1 
busy-signal 1.4.3 
docblockr 0.11.0 
emmet 2.4.3 
file-icons 2.1.10 
filetype-color 0.1.4 
highlight-selected 0.13.1 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.2.0 
linter-ui-default 1.6.3 
node_modules undefined 
platformio-ide-terminal 2.5.4 
```

**Comment by steelbrain** [comment]
Ahh yes, should've thought about that one. When the Tree View is not in a dock but a pane container.

Also just a sidenote that you might wanna drag the tree view inside a dock instead
