### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-package-deps'

### ISSUE THREAD

**Issue by LiangTianFu** [steelbrain/linter-ui-default#412]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.4

### Stack Trace

Uncaught Error: Cannot find module 'atom-package-deps'

```
At C:\Users\lianger\AppData\Local\atom\app-1.19.0\resources\app\static\<embedded>:1

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.19.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.19.0/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.19.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:66:33)
    at installLinterUIDefaultDeps (/packages/linter-ui-default/lib/index.js:23:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.4 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
atom-clock 0.1.13 
docblockr 0.10.5 
docblockr 0.10.5 
emmet 2.4.3 
linter 2.2.0 
linter-ui-default 1.6.4 
```

**Comment by Arcanemagus** [comment]
Please try re-installing the package, it looks like Atom failed to install a dependency.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
