### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by stariel** [steelbrain/linter-ui-default#414]
[Enter steps to reproduce:]

1. ... I created a nav bar in index.html and this error popped up
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 17.04
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.4

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At /usr/share/atom/resources/app/src/text-editor-component.js:2168

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (/usr/share/atom/resources/app/src/text-editor-component.js:2168:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/usr/share/atom/resources/app/src/text-editor-component.js:2164:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/usr/share/atom/resources/app/src/text-editor-component.js:385:16)
    at TextEditorComponent.updateSync (/usr/share/atom/resources/app/src/text-editor-component.js:276:18)
    at TextEditorComponent.pixelPositionForScreenPosition (/usr/share/atom/resources/app/src/text-editor-component.js:202:18)
    at HTMLElement.pixelPositionForScreenPosition (/usr/share/atom/resources/app/src/text-editor-element.js:243:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:168:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -4:45.3.0 core:move-right (input.hidden-input)
     -4:42.4.0 core:backspace (input.hidden-input)
     -4:38.3.0 core:move-down (input.hidden-input)
     -4:36.3.0 intentions:highlight (input.hidden-input)
     -4:35.6.0 find-and-replace:select-next (input.hidden-input)
     -4:34.4.0 core:move-down (input.hidden-input)
  2x -4:33.3.0 core:move-left (input.hidden-input)
     -4:29.1.0 core:backspace (input.hidden-input)
     -4:27.6.0 core:move-down (input.hidden-input)
  2x -2:42.8.0 intentions:highlight (input.hidden-input)
     -2:31 core:save (input.hidden-input)
  3x -2:01.9.0 core:backspace (input.hidden-input)
     -1:54.9.0 intentions:highlight (input.hidden-input)
     -1:54.7.0 core:save (input.hidden-input)
  2x -0:51.8.0 core:backspace (input.hidden-input)
 31x -0:45.4.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
color-picker 2.2.5 
file-icons 2.1.10 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.4 
minimap 4.29.6 
open-in-browser 0.5.2 
tree-view-git-status 1.4.0 
```

**Comment by steelbrain** [comment]
@Arcanemagus Do we have a bug reported in Atom core with this stack trace?

**Comment by Ben3eeE** [comment]
@steelbrain I get redirected here when reproducing https://github.com/atom/atom/issues/15168

**Comment by Arcanemagus** [comment]
Looks like this is solved by https://github.com/atom/atom/pull/15270.
