### ISSUE TITLE
Uncaught Error: Requested measurement of a line that is not currently rendered

### ISSUE THREAD

**Issue by garethallenstringer** [steelbrain/linter-ui-default#418]
[Enter steps to reproduce:]

1. Deleted a line of code in JS
2. Got caught in an infinite error loop

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.5

### Stack Trace

Uncaught Error: Requested measurement of a line that is not currently rendered

```
At C:\Users\GarethAllen-Stringer\AppData\Local\atom\app-1.19.1\resources\app\src\text-editor-component.js:2206

Error: Requested measurement of a line that is not currently rendered
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.19.1/resources/app/src/text-editor-component.js:2204:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.19.1/resources/app/src/text-editor-component.js:2197:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.19.1/resources/app/src/text-editor-component.js:384:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.19.1/resources/app/src/text-editor-component.js:276:18)
    at TextEditorComponent.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.19.1/resources/app/src/text-editor-component.js:202:18)
    at HTMLElement.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-element.js:243:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:168:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
  2x -5:03.1.0 intentions:highlight (input.hidden-input)
     -5:02.6.0 core:save (input.hidden-input)
  2x -4:33.5.0 core:backspace (input.hidden-input)
     -4:29 intentions:highlight (input.hidden-input)
     -4:28.6.0 core:save (input.hidden-input)
  8x -2:35.6.0 core:backspace (input.hidden-input)
  8x -1:26.4.0 core:move-right (input.hidden-input)
  4x -1:24 core:backspace (input.hidden-input)
     -1:13.5.0 editor:newline (input.hidden-input)
  6x -0:42.9.0 intentions:highlight (input.hidden-input)
     -0:42.2.0 core:save (input.hidden-input)
     -0:34.2.0 intentions:highlight (input.hidden-input)
     -0:33.8.0 core:select-all (input.hidden-input)
 31x -0:32 intentions:highlight (input.hidden-input)
     -0:24.6.0 settings-view:open (input.hidden-input)
     -0:10.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
autoclose-html 0.23.0 
autoupdate-packages 1.3.1 
busy-signal 1.4.3 
duplicate-line-or-selection 0.9.0 
emmet 2.4.3 
file-icons 2.1.10 
intentions 1.1.5 
linter 2.2.0 
linter-htmlhint 1.3.3 
linter-jshint 3.1.5 
linter-ui-default 1.6.5 
lucid-tabs 1.1.1 
minimap 4.29.6 
minimap-selection 4.5.0 
open-recent 5.0.0 
pigments 0.40.2 
sass-autocompile 0.13.3 
scroll-through-time 0.2.0 
sync-settings 0.8.2 
todo-show 1.11.0 
```

**Comment by steelbrain** [comment]
Error is coming from Atom internals. You should see if there's an error in `atom/atom` repo of a similar stack trace, if not should open one.

Cheers

**Comment by Arcanemagus** [comment]
For reference, this is filed as https://github.com/atom/atom/issues/15263.
