### ISSUE TITLE
Uncaught Error: Cannot find module 'sb-debounce'

### ISSUE THREAD

**Issue by chivornpen** [steelbrain/linter-ui-default#421]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.7

### Stack Trace

Uncaught Error: Cannot find module 'sb-debounce'

```
At C:\Users\Chhivorn Pen\AppData\Local\atom\app-1.19.2\resources\app\static\<embedded>:1

Error: Cannot find module 'sb-debounce'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.19.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.19.2/resources/app/src/module-cache.js:354:58)
    at Module.require (C:/Users/Chhivorn%20Pen/AppData/Local/atom/app-1.19.2/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.19.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-ui-default/lib/editor/index.js:7:19)
    at /packages/linter-ui-default/lib/editor/index.js:307:24)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.2/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (C:/Users/Chhivorn%20Pen/AppData/Local/atom/app-1.19.2/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.19.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-ui-default/lib/editors.js:3:43)
    at /packages/linter-ui-default/lib/editors.js:90:25)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.2/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.2/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (C:/Users/Chhivorn%20Pen/AppData/Local/atom/app-1.19.2/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.19.2/resources/app/src/native-compile-cache.js:66:33)
    at LinterUI.observeShowDecorations (/packages/linter-ui-default/lib/main.js:51:19)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-bootstrap3 1.2.12 
atom-typescript 11.0.6 
jquery-snippets 11.0.0 
language-blade 0.34.0 
linter-ui-default 1.6.7 
minimap 4.29.6 
```

**Comment by steelbrain** [comment]
APM installation issue, please uninstall and reinstall this package, that should fix it.

We've been getting a lot of these recently, I wonder what the guys at APM are doing, will see if there's an existing bug, if not try to report it
