### ISSUE TITLE
Failed to load the linter-ui-default package

### ISSUE THREAD

**Issue by wkra** [steelbrain/linter-ui-default#424]
Cannot read property 'scripts' of null in C:\Users\wojtek\.atom\packages\linter-ui-default\package.json

TypeError: Cannot read property 'scripts' of null
    at normalize (C:\Users\wojtek\AppData\Local\atom\app-1.19.2\resources\app\node_modules\normalize-package-data\lib\normalize.js:25:17)
    at PackageManager.module.exports.PackageManager.normalizePackageMetadata (C:\Users\wojtek\AppData\Local\atom\app-1.19.2\resources\app\src\package-manager.js:852:22)
    at PackageManager.module.exports.PackageManager.loadPackageMetadata (C:\Users\wojtek\AppData\Local\atom\app-1.19.2\resources\app\src\package-manager.js:826:24)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (C:\Users\wojtek\AppData\Local\atom\app-1.19.2\resources\app\src\package-manager.js:530:43)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\wojtek\AppData\Local\atom\app-1.19.2\resources\app\src\package-manager.js:495:27)
    at PackageManager.module.exports.PackageManager.disablePackage (C:\Users\wojtek\AppData\Local\atom\app-1.19.2\resources\app\src\package-manager.js:195:25)
    at HTMLButtonElement.enablementButtonClickHandler (C:\Users\wojtek\AppData\Local\atom\app-1.19.2\resources\app\node_modules\settings-view\lib\package-card.js:363:31)
  at C:\Users\wojtek\.atom\packages\linter-ui-default\package.json:1:1

**Comment by steelbrain** [comment]
Looks like APM did it again. Here's the fix

```
apm uninstall linter
apm install linter
```
