### ISSUE TITLE
Uncaught TypeError: Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by ryanhs** [steelbrain/linter-ui-default#426]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0-dev-ea6cb7bd1 x64
**Electron**: 1.6.9
**OS**: Ubuntu 17.04
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.7

### Stack Trace

Uncaught TypeError: Cannot read property 'firstChild' of undefined

```
At /home/ryan/.atom-install/share/atom/resources/app/src/text-editor-component.js:2107

TypeError: Cannot read property 'firstChild' of undefined
    at TextEditorComponent.measureLongestLineWidth (/home/ryan/.atom-install/share/atom/resources/app/src/text-editor-component.js:2107:112)
    at TextEditorComponent.measureContentDuringUpdateSync (/home/ryan/.atom-install/share/atom/resources/app/src/text-editor-component.js:381:16)
    at TextEditorComponent.screenPositionForPixelPosition (/home/ryan/.atom-install/share/atom/resources/app/src/text-editor-component.js:2249:18)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:9:50)
    at /packages/linter-ui-default/lib/editor/index.js:168:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -1:26.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
  2x -1:14.1.0 intentions:highlight (input.hidden-input)
     -1:07.2.0 application:new-file (input.hidden-input)
     -0:31.8.0 intentions:highlight (input.hidden-input)
     -0:31.8.0 core:paste (input.hidden-input)
  2x -0:31.8.0 intentions:highlight (input.hidden-input)
     -0:28.1.0 core:paste (input.hidden-input)
  2x -0:20.9.0 intentions:highlight (input.hidden-input)
     -0:17.4.0 core:paste (input.hidden-input)
     -0:12.6.0 intentions:highlight (input.hidden-input)
     -0:12.3.0 core:close (input.hidden-input)
     -0:09.8.0 intentions:highlight (input.hidden-input)
     -0:09.5.0 application:new-file (input.hidden-input)
     -0:07.7.0 intentions:highlight (input.hidden-input)
     -0:07.6.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
angular-2 0.2.6 
atom-beautify 0.29.26 
atom-typescript 11.0.7 
busy-signal 1.4.3 
file-icons 2.1.11 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.7 
quick-query 0.10.1 
```

the atom suggest to report it

**Comment by steelbrain** [comment]
Error is coming from Atom internals, you are on Atom dev (not even beta). I would recommend reposting this if you hit this in a stable version

**Comment by Arcanemagus** [comment]
Duplicate of #417

**Comment by Arcanemagus** [comment]
@ryanhs This should be fixed by https://github.com/atom/atom/pull/15313, does your custom build include that? If not try doing a build that includes that fix and see if this is fixed.

**Comment by ryanhs** [comment]
ah yes.. thank you :+1: 

i even forgot i have custom build
