### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by borisovms** [steelbrain/linter-ui-default#455]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Linux Mint
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.10

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At /home/userpc/.atom/packages/linter-ui-default/node_modules/react-dom/lib/ReactErrorUtils.js:49

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.analysis.indexProject (/packages/atom-lupa/node_modules/lupa/src/analysis.js:93:27)
    at /packages/atom-lupa/lib/lupaMiddleware.js:55:30
    at GoToTransformer.dispatch (/packages/atom-lupa/lib/middleware/domMiddleware.js:59:9)
    at /packages/atom-lupa/lib/middleware/domMiddleware.js:68:37
    at Object.dispatch (/packages/atom-lupa/node_modules/redux-thunk/lib/index.js:14:16)
    at onClick (/packages/atom-lupa/lib/components/Lupa.js:160:34)
    at Object.invokeGuardedCallback (/packages/linter-ui-default/node_modules/react-dom/lib/ReactErrorUtils.js:24:5)
    at executeDispatch (/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginUtils.js:83:21)
    at Object.executeDispatchesInOrder (/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginUtils.js:106:5)
    at executeDispatchesAndRelease (/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginHub.js:41:22)
    at executeDispatchesAndReleaseTopLevel (/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginHub.js:52:10)
    at Array.forEach (native)
    at forEachAccumulated (/packages/linter-ui-default/node_modules/react-dom/lib/forEachAccumulated.js:22:9)
    at Object.processEventQueue (/packages/linter-ui-default/node_modules/react-dom/lib/EventPluginHub.js:252:7)
    at runEventQueueInBatch (/packages/linter-ui-default/node_modules/react-dom/lib/ReactEventEmitterMixin.js:15:18)
    at /packages/linter-ui-default/node_modules/react-dom/lib/ReactEventEmitterMixin.js:25:5)
    at handleTopLevelImpl (/packages/linter-ui-default/node_modules/react-dom/lib/ReactEventListener.js:70:24)
    at ReactDefaultBatchingStrategyTransaction.perform (/packages/linter-ui-default/node_modules/react-dom/lib/Transaction.js:141:20)
    at Object.batchedUpdates (/packages/linter-ui-default/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:60:26)
    at Object.batchedUpdates (/packages/linter-ui-default/node_modules/react-dom/lib/ReactUpdates.js:95:27)
    at dispatchEvent (/packages/linter-ui-default/node_modules/react-dom/lib/ReactEventListener.js:145:20)
```

### Commands

```
     -1:07.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:45.1.0 atom-lupa:toggle (input.hidden-input)
```

### Non-Core Packages

```
api-workbench 0.8.47 
atom-beautify 0.30.6 
atom-easy-jsdoc 4.12.4 
atom-lupa 0.7.43 
atom-ternjs 0.18.3 
autocomplete 0.47.0 
autocomplete-modules 1.8.0 
busy-signal 1.4.3 
copy-path 0.4.2 
double-tag 1.1.0 
emmet 2.4.3 
export-html 3.1.0 
file-icons 2.1.14 
goto-definition 1.3.4 
highlight-line 0.12.0 
highlight-selected 0.13.1 
hyperclick 0.1.5 
intentions 1.1.5 
javascript-snippets 1.2.1 
js-hyperclick 1.12.2 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
monokai 0.24.0 
node-debugger 1.10.1 
pigments 0.40.2 
pretty-json 1.6.4 
rest-client 1.3.1 
seti-ui 1.9.0 
split-diff 1.5.1 
symbols-list 2.4.1 
sync-settings 0.8.3 
```

**Comment by Arcanemagus** [comment]
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.analysis.indexProject (/packages/atom-lupa/node_modules/lupa/src/analysis.js:93:27)
    at /packages/atom-lupa/lib/lupaMiddleware.js:55:30
```

Looks like this is actually in [atom-lupa](https://github.com/hex13/atom-lupa), Atom just used the React instance from here and didn't figure out where it was coming from properly. You'll want to re-file this over there 😉.
