### ISSUE TITLE
Failed to activate the linter-ui-default package  At atom.workspace.getCenter is not a function

### ISSUE THREAD

**Issue by AudriusBuika** [steelbrain/linter-ui-default#460]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.6
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package, v1.6.2

### Stack Trace

Failed to activate the linter-ui-default package

```
At atom.workspace.getCenter is not a function

TypeError: atom.workspace.getCenter is not a function
    at new StatusBar (/Users/audrius/.atom/packages/linter-ui-default/lib/status-bar/index.js:39:43)
    at new LinterUI (/Users/audrius/.atom/packages/linter-ui-default/lib/main.js:33:22)
    at Object.provideUI (/Users/audrius/.atom/packages/linter-ui-default/lib/index.js:36:22)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:366:69)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:194:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:164:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:94:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:154:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:550:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:508:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:831:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "reopenProjectMenuCount": 10,
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v11.0.6 (inactive)
busy-signal, v1.4.3 (inactive)
intentions, v1.1.5 (inactive)
linter, v2.2.0 (inactive)
linter-eslint, v8.4.0 (inactive)
linter-ui-default, v1.6.2 (inactive)
vim-mode-plus, v0.93.0 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.14.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.33.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.43.2 (inactive)
bracket-matcher, v0.85.1 (inactive)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.2.0 (inactive)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.1 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (inactive)
metrics, v1.1.3 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.5 (inactive)
status-bar, v1.6.0 (inactive)
styleguide, v0.48.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.211.1 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
> Atom Version: 1.13.1

Please update to the current version of Atom... I'm not sure how you actually got `linter-ui-default` installed at all as that version is new enough to know that it should have checked the [allowed range](https://github.com/steelbrain/linter-ui-default/blob/f93b38c7c34e0bbce20ddb82db282295c3ee0685/package.json#L13).

**Comment by GregKaleka** [comment]
I'm getting this same error, with the most recent version of Atom.

[Enter steps to reproduce:]

1. Open Atom

**Atom**: 1.24.1 ia32
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Enterprise 2015 LTSB
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1


### Stack Trace

Failed to activate the linter-ui-default package

```
At (0 , _validate.ui) is not a function

TypeError: (0 , _validate.ui) is not a function
    at UIRegistry.add (/packages/linter/lib/ui-registry.js:16:36)
    at Linter.addUI (/packages/linter/lib/main.js:205:21)
    at Object.consumeUI (/packages/linter/lib/index.js:112:16)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.activateServices (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:397:75)
    at Package.activateNow (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:233:20)
    at measure (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:200:20)
    at Package.activate (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.24.1/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.24.1/resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.24.1/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.24.1/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.24.1/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (~/AppData/Local/atom/app-1.24.1/resources/app/src/atom-environment.js:841:27)
```

### Commands

```
     -6:20.4.0 intentions:highlight (input.hidden-input)
     -6:20.4.0 editor:toggle-line-comments (input.hidden-input)
     -6:20.2.0 core:save (input.hidden-input)
  2x -6:17.2.0 core:delete (input.hidden-input)
     -6:13.6.0 intentions:highlight (input.hidden-input)
     -6:13.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-django 0.3.2 
autocomplete-swift 1.0.3 
busy-signal 1.4.3 
django-templates 0.5.0 
expose 0.15.0 
file-icons 2.1.17 
highlight-selected 0.13.1 
intentions 1.1.5 
language-swift 0.5.0 
linter 2.2.0 
linter-csslint 2.0.0 
linter-htmlhint 1.4.0 
linter-swiftc 2.0.0 
linter-ui-default 1.7.1 
swift-debugger 0.1.2 
terminal-plus 0.14.5 
todo-show 2.2.0 
```

**Comment by Arcanemagus** [comment]
Your stack trace is entirely different @GregKaleka, can you try re-installing the package? If that doesn't work please file a new issue so we can work on debugging this more.
