### ISSUE TITLE
Uncaught Error: Cannot find module './editors'

### ISSUE THREAD

**Issue by pythoninthegrass** [steelbrain/linter-ui-default#461]
[Enter steps to reproduce:]

1. Ran sync-settings > restore
2. Triggered error
3. Need to remove and reinstall manually. Will update ticket.

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.10

### Stack Trace

Uncaught Error: Cannot find module './editors'

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:1

Error: Cannot find module './editors'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at LinterUI.observeShowDecorations (/packages/linter-ui-default/lib/main.js:61:19)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.6 
auto-update-packages 1.0.1 
autocomplete-modules 1.8.0 
autocomplete-paths 2.12.1 
busy-signal 1.4.3 
color-picker 2.2.5 
dash 1.7.1 
emmet 2.4.3 
file-icons 2.1.13 
git-plus 7.10.0 
hydrogen-launcher 1.2.1 
intentions 1.1.5 
json-converter 0.2.4 
language-batchfile 0.7.0 
language-liquid 0.6.0 
language-powershell 4.0.0 
language-rust 0.4.12 
language-vbscript 0.9.0 
linter 2.2.0 
linter-csslint 2.0.0 
linter-jscs 4.1.3 
linter-jsonlint 1.3.0 
linter-pylama 0.9.4 
linter-rubocop 2.2.0 
linter-rust 0.8.2 
linter-shellcheck 1.4.6 
linter-ui-default 1.6.10 
markdown-preview-plus 2.4.16 
markdown-writer 2.7.3 
merge-conflicts 1.4.5 
minimap 4.29.7 
pandoc-convert 1.1.1 
pigments 0.40.2 
remote-edit 1.9.0 
ruby-block-converter 4.0.1 
ruby-blue-syntax 0.2.2 
sort-lines 0.18.0 
sorter 1.1.0 
sync-settings 0.8.3 
tabs-to-spaces 1.0.3 
teletype 0.2.3 
terminal-plus 0.14.5 
todo-show 2.1.0 
```

**Comment by Arcanemagus** [comment]
Can you try re-installing the package? That's one of the main files and if Atom can't find that something is very wrong with your installation of this package.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response and the high probability this is a `sync-settings` bug.
