### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by BillGR17** [steelbrain/linter-ui-default#468]
[Enter steps to reproduce:]

1. I selected multiple lines (they didnt even contain an error)
2. I tried to right click on the selected lines i am not sure if the error came before or after the right click

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: "Arch Linux"
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.10

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /usr/lib/atom/src/text-editor-component.js:636

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (/usr/lib/atom/src/text-editor-component.js:636:39)
    at Map.forEach (native)
    at TextEditorComponent.renderLineTiles (/usr/lib/atom/src/text-editor-component.js:633:37)
    at TextEditorComponent.renderContent (/usr/lib/atom/src/text-editor-component.js:576:12)
    at TextEditorComponent.renderScrollContainer (/usr/lib/atom/src/text-editor-component.js:551:12)
    at TextEditorComponent.render (/usr/lib/atom/src/text-editor-component.js:496:14)
    at Object.updateSync (/usr/lib/atom/node_modules/etch/lib/component-helpers.js:107:34)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/usr/lib/atom/src/text-editor-component.js:373:10)
    at TextEditorComponent.updateSync (/usr/lib/atom/src/text-editor-component.js:264:10)
    at TextEditorComponent.pixelPositionForScreenPosition (/usr/lib/atom/src/text-editor-component.js:196:12)
    at HTMLElement.pixelPositionForScreenPosition (/usr/lib/atom/src/text-editor-element.js:243:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:178:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -0:10.1.0 editor:consolidate-selections (input.hidden-input)
     -0:10.1.0 core:cancel (input.hidden-input)
     -0:09.9.0 editor:consolidate-selections (input.hidden-input)
     -0:09.9.0 core:cancel (input.hidden-input)
     -0:09.7.0 editor:consolidate-selections (input.hidden-input)
     -0:09.7.0 core:cancel (input.hidden-input)
     -0:09.6.0 editor:consolidate-selections (input.hidden-input)
     -0:09.6.0 core:cancel (input.hidden-input)
     -0:09.4.0 editor:consolidate-selections (input.hidden-input)
     -0:09.4.0 core:cancel (input.hidden-input)
     -0:08.3.0 editor:consolidate-selections (input.hidden-input)
     -0:08.3.0 core:cancel (input.hidden-input)
     -0:08.1.0 editor:consolidate-selections (input.hidden-input)
     -0:08.1.0 core:cancel (input.hidden-input)
     -0:07.9.0 editor:consolidate-selections (input.hidden-input)
     -0:07.9.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-bootstrap3 1.2.12 
atom-handlebars 1.3.0 
autocomplete-modules 1.10.0 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.16 
highlight-selected 0.13.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-rust 0.4.12 
linter 2.2.0 
linter-eslint 8.4.0 
linter-rust 0.8.4 
linter-ui-default 1.6.10 
pigments 0.40.2 
platformio-ide-terminal 2.8.0 
Stylus 3.1.1 
```

**Comment by Arcanemagus** [comment]
This is an Atom internal bug that is mistakenly getting sent here since this is where the initial call came from. Please follow https://github.com/atom/atom/issues/16179 for further updates.
