### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by codekidX** [steelbrain/linter-ui-default#476]
[Enter steps to reproduce:]

1. All I know is my Macbook Pro went to sleep and after waking it up I got these atom error dialogs, everytime it tries to lint check

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.10

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:191

Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:183:27)
    at TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2109:41)
    at Editor.decorateMarker (/packages/linter-ui-default/lib/editor/index.js:290:23)
    at _loop (/packages/linter-ui-default/lib/editor/index.js:283:12)
    at Editor.apply (/packages/linter-ui-default/lib/editor/index.js:261:61)
    at /packages/linter-ui-default/lib/editors.js:56:48
    at Array.forEach (native)
    at /packages/linter-ui-default/lib/editors.js:56:23
    at Array.forEach (native)
    at Editors.update (/packages/linter-ui-default/lib/editors.js:53:15)
    at LinterUI.render (/packages/linter-ui-default/lib/main.js:73:17)
    at /packages/linter/lib/ui-registry.js:32:16
    at Set.forEach (native)
    at UIRegistry.render (/packages/linter/lib/ui-registry.js:31:20)
    at /packages/linter/lib/main.js:187:23
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at MessageRegistry.update (/packages/linter/lib/message-registry.js:130:20)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -0:38.2.0 editor:newline (input.hidden-input)
     -0:35.5.0 core:move-down (input.hidden-input)
  2x -0:35.3.0 autocomplete-plus:confirm (input.hidden-input)
     -0:31.9.0 editor:newline (input.hidden-input)
     -0:29.5.0 autocomplete-plus:confirm (input.hidden-input)
     -0:28.5.0 core:move-left (input.hidden-input)
  2x -0:27 core:move-right (input.hidden-input)
     -0:24.8.0 core:backspace (input.hidden-input)
  2x -0:23.2.0 core:move-left (input.hidden-input)
     -0:22.6.0 core:move-right (input.hidden-input)
     -0:21.1.0 autocomplete-plus:confirm (input.hidden-input)
     -0:20.2.0 core:move-left (input.hidden-input)
  2x -0:15.2.0 core:backspace (input.hidden-input)
     -0:11.9.0 autocomplete-plus:confirm (input.hidden-input)
     -0:06.5.0 editor:newline (input.hidden-input)
     -0:06.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-material-ui 2.1.1 
atom-ternjs 0.18.3 
autocomplete-modules 1.8.0 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
editorconfig 2.2.2 
es6-javascript 1.0.0 
file-header 1.13.8 
file-icons 2.1.15 
intentions 1.1.5 
javascript-snippets 1.2.1 
kite 0.62.0 
language-babel 2.81.1 
linter 2.2.0 
linter-eslint 8.4.0 
linter-flake8 2.3.0 
linter-ui-default 1.6.10 
material-palenight-syntax 1.5.7 
minimap 4.29.7 
python-autopep8 0.1.3 
remote-edit 1.9.0 
script 3.17.3 
todo-show 2.1.0 
```

**Comment by codekidX** [comment]
Seems #434 is already open, human error
