### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, 9)

### ISSUE THREAD

**Issue by Zuldruck** [steelbrain/linter-ui-default#479]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.10

### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, 9)

```
At /usr/share/atom/resources/app/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (NaN, 9)
    at Function.module.exports.Point.assertValid (/usr/share/atom/resources/app/node_modules/text-buffer/lib/point.js:63:21)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1220:19)
    at TextBuffer.module.exports.TextBuffer.clipRange (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1208:26)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker-layer.js:225:52)
    at TextBuffer.module.exports.TextBuffer.markRange (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:818:44)
    at _loop (/packages/linter-ui-default/lib/editor/index.js:268:33)
    at Editor.apply (/packages/linter-ui-default/lib/editor/index.js:261:61)
    at /packages/linter-ui-default/lib/editors.js:56:48
    at Array.forEach (native)
    at /packages/linter-ui-default/lib/editors.js:56:23
    at Array.forEach (native)
    at Editors.update (/packages/linter-ui-default/lib/editors.js:53:15)
    at LinterUI.render (/packages/linter-ui-default/lib/main.js:73:17)
    at /packages/linter/lib/ui-registry.js:32:16
    at Set.forEach (native)
    at UIRegistry.render (/packages/linter/lib/ui-registry.js:31:20)
    at /packages/linter/lib/main.js:187:23
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at MessageRegistry.update (/packages/linter/lib/message-registry.js:130:20)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
 31x -4:29.1.0 core:backspace (input.hidden-input)
     -4:10.5.0 intentions:highlight (input.hidden-input)
     -4:10.4.0 core:undo (input.hidden-input)
     -4:08.7.0 intentions:highlight (input.hidden-input)
 12x -4:08.2.0 core:undo (input.hidden-input)
     -4:03.9.0 intentions:highlight (input.hidden-input)
  4x -4:03.8.0 core:undo (input.hidden-input)
     -3:30.9.0 core:backspace (input.hidden-input)
     -3:30.5.0 intentions:highlight (input.hidden-input)
     -3:29.3.0 core:undo (input.hidden-input)
     -3:21.9.0 core:backspace (input.hidden-input)
     -3:19.8.0 intentions:highlight (input.hidden-input)
     -3:19.2.0 core:undo (input.hidden-input)
 17x -3:16.4.0 editor:newline (input.hidden-input)
 11x -2:59 core:backspace (input.hidden-input)
 80x -0:32.1.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atomic-emacs 0.12.1 
busy-signal 1.4.3 
epitech-header 1.2.3 
epitech-norm-linter 1.12.3 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.10 
multi-comment 0.3.0 
platformio-ide-terminal 2.7.0 
teletype 0.7.0 
```

**Comment by steelbrain** [comment]
Hi @Zuldruck 

This appears to be an issue with the `epitech-norm-linter` package. Please reopen this issue in their repository.

Thanks!
