### ISSUE TITLE
Uncaught TypeError: this.registry.startIdForScope is not a function

### ISSUE THREAD

**Issue by adamzerner** [steelbrain/linter-ui-default#481]
[Enter steps to reproduce:]

Seems to happen when I open a `.todo` file.

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.10

### Stack Trace

Uncaught TypeError: this.registry.startIdForScope is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:324

TypeError: this.registry.startIdForScope is not a function
    at Grammar.module.exports.Grammar.startIdForScope (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:324:34)
    at TextMateLanguageMode.tokenizedLineForRow (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:428:30)
    at TextMateHighlightIterator.seek (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:746:49)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:83:58)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at DisplayLayer.getScreenLine (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:639:60)
    at TextEditor.screenLineForScreenRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1243:36)
    at TextEditorComponent.requestHorizontalMeasurement (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2258:47)
    at TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:205:18)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:246:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:178:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Non-Core Packages

```
busy-signal 1.4.3 
file-icons 2.1.16 
intentions 1.1.5 
language-babel 2.84.0 
language-vue 0.23.1 
language-vue-component 0.5.0 
linter 2.2.0 
linter-jscs 4.1.3 
linter-jshint 3.1.6 
linter-ui-default 1.6.10 
tasks 2.9.1 
```

**Comment by Arcanemagus** [comment]
This is an Atom internal bug, I've added a comment on the relevant issue in the link above so I'm closing this issue here.

Thanks for reporting this!
