### ISSUE TITLE
Highlighting incorrect lines of code

### ISSUE THREAD

**Issue by alexswiontek** [steelbrain/linter-ui-default#489]
_Versions_
Atom: 1.24.0
OS: macOS High Sierrra 10.13.3

_Behavior_
Linter UI seems to be highlighting on the line _above_ where the error occurs.

_Screenshots_
<img width="519" alt="1" src="https://user-images.githubusercontent.com/15092959/37046989-8da583d4-211e-11e8-86cb-a20da02eadf7.png">
<img width="524" alt="1-err" src="https://user-images.githubusercontent.com/15092959/37046992-8f2e786e-211e-11e8-9de6-694670e24cc8.png">
^ would expect the "_." portion to be underlined

-----------------------------------------------

<img width="539" alt="2" src="https://user-images.githubusercontent.com/15092959/37047057-bee6a9fa-211e-11e8-831b-42512a042a2c.png">
<img width="682" alt="2-err" src="https://user-images.githubusercontent.com/15092959/37047060-c052ecfe-211e-11e8-8b23-51a53c45a2a7.png">
^ would expect "results" to be underlined

-----------------------------------------------

![screen shot 2018-03-06 at 9 06 27 am](https://user-images.githubusercontent.com/15092959/37046830-1d0e6a50-211e-11e8-8e40-0ba791c085fc.png)

_Notes_
Seems to have occurred since updating to the recent version of linter-ui-default (1.7.1)

**Comment by steelbrain** [comment]
Hi @alexswiontek

From the screenshot you attached, there's an error saying the package loading for `linter-ui-default` was failed, the error description/message could provide an insight into why you are seeing this behavior.

Can you please post the full contents of that error in console?

**Comment by alexswiontek** [comment]
Sure thing, thanks for the quick response! Here is the error:

```
Uncaught (in promise) Error: Failed to load package 'linter-ui-default'
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:691:35)
    at packagesToEnable.forEach.name (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:440:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:440:30)
    at /Applications/Atom.app/Contents/Resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:407:18)
    at PackageManager.module.exports.PackageManager.removePackageNameFromDisabledPackages (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:696:32)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:579:25
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

**Comment by steelbrain** [comment]
Can you please execute this in the dev console so the actual error gets logged instead?

```js
atom.packages.activatePackage('linter-ui-default').catch(e => console.error(e))
```

**Comment by alexswiontek** [comment]
<img width="1278" alt="screen shot 2018-03-06 at 9 45 39 am" src="https://user-images.githubusercontent.com/15092959/37048584-27284d76-2123-11e8-999a-144f520ad0f3.png">

^ haven't been able to recreate the error in the console...looks like it has realigned the highlighting once I clicked "ESLint Fix", but hasn't thrown any errors

**Comment by steelbrain** [comment]
That's strange... Whelp, if nothing else works the turn it off-and-on again should 😄 

Try this in console and then restart Atom and see if you see the issue still

```
apm uninstall linter-ui-default
apm install linter-ui-default
```
Or you could just uninstall -> install from the settings view, your call

**Comment by alexswiontek** [comment]
Looks like the atom equivalent of "restarting the computer" worked 😅

<img width="598" alt="screen shot 2018-03-06 at 9 50 24 am" src="https://user-images.githubusercontent.com/15092959/37048852-f4a6ec12-2123-11e8-9997-a66ca7f93184.png">

^ appears to be highlighting the correct code now

I can close if you'd like. Thanks for your help!

**Comment by steelbrain** [comment]
Glad it works for you now! Cheers
