### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by danielmarcgardner** [steelbrain/linter-ui-default#492]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.2
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:191

Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:183:27)
    at TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2124:41)
    at Editor.decorateMarker (/packages/linter-ui-default/lib/editor/index.js:332:23)
    at _loop (/packages/linter-ui-default/lib/editor/index.js:315:12)
    at Editor.apply (/packages/linter-ui-default/lib/editor/index.js:303:61)
    at /packages/linter-ui-default/lib/editors.js:60:48
    at Array.forEach (native)
    at /packages/linter-ui-default/lib/editors.js:60:23
    at Array.forEach (native)
    at Editors.update (/packages/linter-ui-default/lib/editors.js:57:15)
    at LinterUI.render (/packages/linter-ui-default/lib/main.js:87:17)
    at /packages/linter/lib/ui-registry.js:32:16
    at Set.forEach (native)
    at UIRegistry.render (/packages/linter/lib/ui-registry.js:31:20)
    at /packages/linter/lib/main.js:187:23
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at MessageRegistry.update (/packages/linter/lib/message-registry.js:130:20)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -1:09.5.0 editor:newline (input.hidden-input)
     -1:08.3.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -1:07.7.0 editor:newline (input.hidden-input)
     -1:03.3.0 core:backspace (input.hidden-input)
     -0:59.9.0 core:cut (input.hidden-input)
     -0:59.3.0 core:backspace (input.hidden-input)
     -0:58.1.0 core:move-up (input.hidden-input)
     -0:57.6.0 core:paste (input.hidden-input)
  5x -0:56.1.0 core:backspace (input.hidden-input)
     -0:19.4.0 core:cut (input.hidden-input)
  2x -0:18.7.0 core:move-right (input.hidden-input)
     -0:17.9.0 core:move-left (input.hidden-input)
 13x -0:17.5.0 core:backspace (input.hidden-input)
     -0:12.8.0 editor:newline (input.hidden-input)
     -0:11.1.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -0:10.3.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.0 
atom-bootstrap4 1.4.0 
atom-html-preview 0.2.5 
atom-ide-ui 0.9.3 
atom-typescript 12.3.5 
busy-signal 1.4.3 
css-snippets 1.1.0 
emmet 2.4.3 
file-icons 2.1.17 
flexbox-snippets 0.3.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-babel 2.84.0 
language-graphql 0.9.0 
linter 2.2.0 
linter-csslint 2.0.0 
linter-eslint 8.4.1 
linter-htmlhint 1.4.0 
linter-jshint 3.1.6 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
react 0.18.0 
script 3.17.3 
tool-bar 1.1.6 
tool-bar-almighty 0.8.2 
```

**Comment by dcurletti** [comment]
Getting the same errors.

**Comment by aeblin** [comment]
[Enter steps to reproduce:]

Also getting this when opening a partially completed index.js file for an Express/Apollo server.

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1


### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:191

Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:183:27)
    at TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2123:41)
    at Editor.decorateMarker (/packages/linter-ui-default/lib/editor/index.js:332:23)
    at _loop (/packages/linter-ui-default/lib/editor/index.js:315:12)
    at Editor.apply (/packages/linter-ui-default/lib/editor/index.js:303:61)
    at /packages/linter-ui-default/lib/editors.js:60:48
    at Array.forEach (native)
    at /packages/linter-ui-default/lib/editors.js:60:23
    at Array.forEach (native)
    at Editors.update (/packages/linter-ui-default/lib/editors.js:57:15)
    at LinterUI.render (/packages/linter-ui-default/lib/main.js:87:17)
    at /packages/linter/lib/ui-registry.js:32:16
    at Set.forEach (native)
    at UIRegistry.render (/packages/linter/lib/ui-registry.js:31:20)
    at /packages/linter/lib/main.js:187:23
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at MessageRegistry.update (/packages/linter/lib/message-registry.js:130:20)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-ide-ui 0.9.4 
atom-material-ui 2.1.3 
auto-update-packages 1.0.1 
base-16-ocean-dark-ui-theme 1.7.2 
base16-ocean-dark-spacegray 0.13.0 
base16-ocean-dark-syntax-theme 0.1.10 
busy-signal 1.4.3 
cobalt2-syntax 0.5.3 
emmet 2.4.3 
intentions 1.1.5 
language-babel 2.84.0 
language-graphql 0.9.0 
less-than-slash 0.18.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-php 1.5.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
oceanic-next 1.0.0 
prettier-atom 0.51.0 
react-snippets 1.0.1 
sync-settings 0.8.5 
Zen 0.18.0 
```

**Comment by aeblin** [comment]
Just managed to resolve this by disabling linter, restarting Atom, and finally re-enabling linter. Worth noting Atom updated from 1.24.0 to 1.24.1 in the process.

**Comment by AlexWayfer** [comment]
Still an issue in Atom 1.34:

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: linux 4.20.0-arch1-1-ARCH
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1


### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /usr/share/atom/resources/app/static/<embedded>:11

Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (/usr/share/atom/resources/app/static/<embedded>:11:518765)
    at TextEditor.decorateMarker (/usr/share/atom/resources/app/static/<embedded>:11:27540)
    at Editor.decorateMarker (/packages/linter-ui-default/lib/editor/index.js:332:23)
    at _loop (/packages/linter-ui-default/lib/editor/index.js:315:12)
    at Editor.apply (/packages/linter-ui-default/lib/editor/index.js:303:61)
    at /packages/linter-ui-default/lib/editors.js:60:48
    at Array.forEach (<anonymous>)
    at /packages/linter-ui-default/lib/editors.js:60:23
    at Array.forEach (<anonymous>)
    at Editors.update (/packages/linter-ui-default/lib/editors.js:57:15)
    at LinterUI.render (/packages/linter-ui-default/lib/main.js:87:17)
    at /packages/linter/lib/ui-registry.js:32:16
    at Set.forEach (<anonymous>)
    at UIRegistry.render (/packages/linter/lib/ui-registry.js:31:20)
    at /packages/linter/lib/main.js:187:23
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1190133)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191574)
    at MessageRegistry.update (/packages/linter/lib/message-registry.js:130:20)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -0:54.6.0 intentions:highlight (input.hidden-input)
     -0:54.5.0 pane:show-next-item (input.hidden-input)
     -0:54.4.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -0:49.2.0 intentions:highlight (input.hidden-input)
     -0:49.2.0 editor:duplicate-lines (input.hidden-input)
     -0:48.8.0 intentions:highlight (input.hidden-input)
     -0:48.5.0 editor:select-to-beginning-of-word (input.hidden-input)
  5x -0:44.7.0 core:select-page-down (input.hidden-input)
     -0:43.1.0 intentions:highlight (input.hidden-input)
     -0:42.8.0 editor:indent-selected-rows (input.hidden-input)
     -0:42.2.0 core:move-right (input.hidden-input)
     -0:42 core:move-left (input.hidden-input)
     -0:41.8.0 intentions:highlight (input.hidden-input)
     -0:41.6.0 editor:duplicate-lines (input.hidden-input)
     -0:41.3.0 snippets:previous-tab-stop (input.hidden-input)
     -0:41.3.0 editor:outdent-selected-rows (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-smart-tabs 0.1.0 
atom-typescript 12.7.3 
auto-detect-indentation 1.3.0 
auto-update-plus 0.5.8 
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
autocomplete-paths 2.12.2 
autocomplete-ruby 0.2.8 
autoupdate-packages 1.3.1 
ax-monokai-syntax 0.3.0 
better-git-blame 0.4.7 
blocky 0.13.0 
busy-signal 2.0.0 
color-picker 2.3.0 
editorconfig 2.2.2 
file-icons 2.1.27 
genesis-ui 0.5.0 
git-time-machine 2.1.0 
go-plus 6.0.2 
goto-definition 1.3.4 
highlight-selected 0.14.0 
ide-crystal 0.3.3 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-crystal-actual 0.37.2 
language-fish-shell 1.1.0 
language-haml 0.31.1 
language-postcss 1.3.1 
language-vue 0.24.0 
linter 2.2.0 
linter-erb 1.1.2 
linter-eslint 8.5.0 
linter-htmlhint 1.5.1 
linter-jshint 3.1.9 
linter-markdown 5.2.2 
linter-reek 2.2.2 
linter-rubocop 2.2.3 
linter-ruby 1.2.6 
linter-spell 0.15.0 
linter-stylelint 4.3.2 
linter-ui-default 1.7.1 
linter-ui-plus 0.3.2 
merge-conflicts 1.4.5 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
monocolor-blue-syntax 2.0.0 
monokai 0.24.0 
monokai-flat 1.0.1 
monokai-plus 0.1.3 
monokai-pro 0.1.0 
monokai-slate 0.6.0 
monokai-sublime 1.0.0 
nord-atom-syntax 0.9.1 
northem-atom-syntax 2.1.0 
northem-dark-atom-syntax 2.1.0 
nucleus-dark-ui 0.12.3 
one-monokai 0.3.0 
platformio-ide-terminal 2.8.4 
precss 0.3.0 
remember-file-positions 0.2.3 
revert-buffer 0.6.0 
ruby-block 0.3.6 
ruby-block-converter 4.1.1 
ruby-define-method 0.2.2 
ruby-test 1.0.2 
scroll-editor-on-middle-click 0.6.0 
seeing-is-believing 15.0.0 
seti-icons 1.5.4 
seti-ui 1.11.0 
single-click-open 0.2.2 
space-tab 0.4.2 
space-underscore 0.1.1 
split-diff 1.5.4 
stacked-tabs 0.1.3 
symbols-tree-view 0.14.0 
sync-settings 0.8.6 
tab-control 0.6.11 
tabs-to-spaces 1.0.5 
tasks 2.10.1 
teletype 0.13.3 
term3 0.22.1 
toggle-quotes 1.1.3 
tree-view-open-files 0.3.0 
yard 0.5.1 
zentabs 0.8.9 
```

**Comment by octoquad** [comment]
I use PHP Linter with PHP CS & PHP MD. This file triggers this specific problem all the time. Hopefully this can help you identify the problem and fix it.

[panacea-api.zip](https://github.com/steelbrain/linter-ui-default/files/2850908/panacea-api.zip)

**Comment by lewismoten** [comment]
I'm getting the same problem. However, it seems to only be when my file is named `read-riff-header.js`. I've tried naming it other things and the error goes away. I rename it back to `read-riff-header.js` and I get the bug again. You may have to close/reopen the file to confirm.
