### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by rsolomonjr** [steelbrain/linter-ui-default#506]
[Enter steps to reproduce:]

1. save json 
2. 'word wrap' json file
3. errors appear

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At C:\Users\rsolomon\AppData\Local\atom\app-1.27.2\resources\app\src\text-editor-component.js:663

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (~/AppData/Local/atom/app-1.27.2/resources/app/src/text-editor-component.js:663:45)
    at Map.forEach (native)
    at TextEditorComponent.renderLineTiles (~/AppData/Local/atom/app-1.27.2/resources/app/src/text-editor-component.js:660:43)
    at TextEditorComponent.renderContent (~/AppData/Local/atom/app-1.27.2/resources/app/src/text-editor-component.js:601:18)
    at TextEditorComponent.renderScrollContainer (~/AppData/Local/atom/app-1.27.2/resources/app/src/text-editor-component.js:577:18)
    at TextEditorComponent.render (~/AppData/Local/atom/app-1.27.2/resources/app/src/text-editor-component.js:522:20)
    at Object.updateSync (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/etch/lib/component-helpers.js:107:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.27.2/resources/app/src/text-editor-component.js:392:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.27.2/resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.27.2/resources/app/src/text-editor-component.js:207:18)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:246:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
  3x -6:31.9.0 core:delete (input.hidden-input)
     -6:12.5.0 intentions:highlight (input.hidden-input)
     -6:12.4.0 core:paste (input.hidden-input)
     -6:07.5.0 core:delete (input.hidden-input)
     -5:46 intentions:highlight (input.hidden-input)
     -5:45.8.0 core:paste (input.hidden-input)
  2x -5:41 html-entitize:encode (input.hidden-input)
     -5:31.7.0 core:select-right (input.hidden-input)
  4x -5:30.8.0 core:delete (input.hidden-input)
 41x -5:09.6.0 intentions:highlight (input.hidden-input)
     -5:07.8.0 core:save (input.hidden-input)
     -0:44.6.0 editor:toggle-soft-wrap (input.hidden-input)
  4x -0:26.2.0 intentions:highlight (input.hidden-input)
     -0:25.6.0 core:undo (input.hidden-input)
undefined -0:24.7.0 intentions:highlight (input.hidden-input)
     -0:13 core:undo (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-live-server 2.2.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
atom-react-autocomplete 0.1.10 
atom-wrap-in-tag 0.6.0 
autocomplete-html-entities 0.2.0 
autocomplete-paths 2.12.2 
autoupdate-packages 1.3.1 
busy-signal 1.4.3 
cobalt2-syntax 0.5.3 
emmet 2.4.3 
file-icons 2.1.21 
fonts 3.0.3 
git-plus 7.10.2 
git-time-machine 2.1.0 
highlight-selected 0.13.1 
html-entitize 1.1.0 
html-wrapper 0.2.0 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
open-in-browser 0.5.2 
open-recent 5.0.0 
pigments 0.40.2 
project-manager 3.3.6 
remote-ftp 2.2.0 
```

**Comment by aminya** [comment]
Close in favor of the already reported issue: #571

Please add more information to that issue, if it happens in the latest version of Atom and linter.
