### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by MichaelA59** [steelbrain/linter-ui-default#508]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.3
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:663

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:663:46)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:660:43)
    at TextEditorComponent.renderContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:601:18)
    at TextEditorComponent.renderScrollContainer (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:577:18)
    at TextEditorComponent.render (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:522:20)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:107:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:392:16)
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2399:18)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:9:50)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -2:44 core:close (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-one-dark-ui)
     -2:31.6.0 core:save (input.hidden-input)
     -2:30 core:close (input.hidden-input)
     -2:24.6.0 tree-view:toggle (input.hidden-input)
     -2:09.9.0 core:save (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-one-dark-ui)
     -1:39.7.0 core:close (input.hidden-input)
     -0:32 window:decrease-font-size (input.hidden-input)
     -0:26.3.0 tree-view:toggle (input.hidden-input)
     -0:21.6.0 window:decrease-font-size (div.tool-panel.tree-view)
  2x -0:20.5.0 window:increase-font-size (div.tool-panel.tree-view)
  2x -0:16.4.0 window:decrease-font-size (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
autoclose-html 0.23.0 
busy-signal 1.4.3 
clipboard-plus 0.5.1 
color-picker 2.3.0 
file-icons 2.1.22 
highlight-selected 0.14.0 
intentions 1.1.5 
language-babel 2.85.0 
linter 2.2.0 
linter-rubocop 2.2.3 
linter-ui-default 1.7.1 
monokai 0.24.0 
pigments 0.40.2 
ruby-block 0.3.6 
todo-show 2.3.0 
```

**Comment by aminya** [comment]
Close in favor of the already reported issue: #571

Please add more information to that issue, if it happens in the latest version of Atom and linter.
