### ISSUE TITLE
Uncaught TypeError: Cannot destructure property `textNodes` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by eristoddle** [steelbrain/linter-ui-default#511]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Cannot destructure property `textNodes` of 'undefined' or 'null'.

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2398

TypeError: Cannot destructure property `textNodes` of 'undefined' or 'null'.
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2398:65)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:9:50)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -7:34.8.0 project-find:show-in-current-directory (div.icon.name.nuclide-ui-path-with-file-icon.icon-file-directory.name.nuclide-file-tree-path.icon-nuclicon-file-directory-starred)
     -7:27.2.0 core:paste (input.hidden-input)
     -7:26.2.0 core:confirm (input.hidden-input)
     -4:23.8.0 core:backspace (input.hidden-input)
  2x -4:22 core:save (input.hidden-input)
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-beautify 0.33.0 
atom-dark-monokai-syntax 0.18.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-react-native-autocomplete 0.0.27 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
busy 0.7.0 
busy-signal 1.4.3 
copy-path 0.5.1 
dark-plus-syntax 2.5.0 
docblockr 0.13.7 
editorconfig 2.2.2 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
emmet-jsx-props 1.4.0 
es6-javascript 1.0.0 
file-icons 2.1.24 
file-types 1.0.1 
fold-search-results 1.0.5 
format-sql 0.3.0 
ghar-dark-syntax 2.0.0 
git-plus 8.0.0 
git-plus-plus 1.1.0 
git-plus-toolbar 1.0.1 
gl-dark-syntax 3.0.0 
go-plus 5.8.5 
grunt-snippets 0.1.1 
highlight-selected 0.14.0 
hyperclick 0.1.5 
ide-php 0.7.14 
ide-typescript 0.7.6 
imdone-atom-github 0.1.11 
intentions 1.1.5 
javascript-snippets 1.2.1 
jekyll 2.1.0 
language-apache 1.8.0 
language-aspx 0.5.0 
language-docker 1.1.8 
language-ethereum 0.3.9 
language-javascript-jsx 0.3.7 
language-liquid 0.7.0 
leanpub-snippets 0.2.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-golinter 1.2.2 
linter-stylelint 4.3.2 
linter-swagger 0.5.1 
linter-ui-default 1.7.1 
local-history 4.3.1 
mac-os-ui 0.3.0 
markdown-helpers 0.3.0 
markdown-scroll-sync 2.1.2 
markdown-writer 2.9.0 
MavensMate-Atom 1.1.0 
merge-conflicts 1.4.5 
multirow-tabs 0.3.3 
native-ui 0.26.3 
npm-plus 0.4.0 
nuclide 0.337.0 
nuclide-format-js 0.0.47 
one-dark-vivid-syntax 1.8.1 
organize-imports 1.0.0 
pear-dark-syntax 1.0.9 
pigments 0.40.2 
pinned-tabs 2.0.6 
prettier-atom 0.54.0 
project-manager 3.3.6 
prompt-big-file 0.5.0 
react 0.18.0 
react-snippets 1.1.1 
snow-dark-syntax 0.1.1 
sort-lines 0.18.0 
spectrum-dark-syntax 0.2.0 
split-diff 1.5.2 
spring-dark-syntax 0.0.4 
sync-settings 0.8.6 
titan-dark-syntax 2.0.0 
todo-show 2.3.0 
tool-bar 1.1.7 
tool-bar-almighty 0.8.2 
tool-bar-markdown-writer 0.4.0 
unity-dark-ui 2.0.9 
unity-ui 2.1.11 
Warm-Dark-syntax 0.1.0 
zhk-dark-syntax 0.3.1 
```

**Comment by aminya** [comment]
Closing in favor of another duplicate issue. https://github.com/steelbrain/linter-ui-default/issues/534
