### ISSUE TITLE
Uncaught Error: Cannot find module 'marked'

### ISSUE THREAD

**Issue by marius-mac** [steelbrain/linter-ui-default#512]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Home N
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught Error: Cannot find module 'marked'

```
At module.js:545

Error: Cannot find module 'marked'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.30.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.30.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-ui-default/lib/tooltip/message.js:21:15)
    at /packages/linter-ui-default/lib/tooltip/message.js:221:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.30.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-ui-default/lib/tooltip/index.js:23:16)
    at /packages/linter-ui-default/lib/tooltip/index.js:102:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.30.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-ui-default/lib/editor/index.js:17:16)
    at /packages/linter-ui-default/lib/editor/index.js:384:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.30.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-ui-default/lib/editors.js:9:15)
    at /packages/linter-ui-default/lib/editors.js:121:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.30.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:66:33)
    at LinterUI.observeShowDecorations (/packages/linter-ui-default/lib/main.js:61:19)
```

### Commands

```
 46x -8:27.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.1 
autocomplete-html-entities 0.2.0 
autocomplete-java 1.2.7 
autocomplete-json 5.5.2 
autocomplete-sql 0.5.0 
autocomplete-xml 0.10.1 
busy-signal 1.4.3 
color-picker 2.3.0 
intentions 1.1.5 
linter 2.2.0 
linter-csslint 2.0.1 
linter-htmlhint 1.5.0 
linter-jshint 3.1.8 
linter-ui-default 1.7.1 
lorem 1.5.0 
php-cs-fixer 4.1.1 
```

**Comment by aminya** [comment]
Please reinstall the package.
