### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Gilbertrdz** [steelbrain/linter-ui-default#514]
When I'm going to right click on some code I get this error.

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At C:\Users\elcap\AppData\Local\atom\app-1.30.0\resources\app\src\text-editor-component.js:666

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (~/AppData/Local/atom/app-1.30.0/resources/app/src/text-editor-component.js:666:46)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (~/AppData/Local/atom/app-1.30.0/resources/app/src/text-editor-component.js:663:43)
    at TextEditorComponent.renderContent (~/AppData/Local/atom/app-1.30.0/resources/app/src/text-editor-component.js:604:18)
    at TextEditorComponent.renderScrollContainer (~/AppData/Local/atom/app-1.30.0/resources/app/src/text-editor-component.js:580:18)
    at TextEditorComponent.render (~/AppData/Local/atom/app-1.30.0/resources/app/src/text-editor-component.js:525:20)
    at Object.updateSync (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/etch/lib/component-helpers.js:107:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.30.0/resources/app/src/text-editor-component.js:392:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.30.0/resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.30.0/resources/app/src/text-editor-component.js:207:18)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:246:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -0:55.6.0 core:close (input.hidden-input)
     -0:53.6.0 intentions:highlight (input.hidden-input)
     -0:53.4.0 core:close (input.hidden-input)
     -0:49.8.0 intentions:highlight (input.hidden-input)
     -0:49.7.0 core:save (input.hidden-input)
undefined -0:44.2.0 intentions:highlight (input.hidden-input)
     -0:36.5.0 core:backspace (input.hidden-input)
     -0:34 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:34 editor:newline (input.hidden-input)
     -0:33.1.0 intentions:highlight (input.hidden-input)
     -0:31.7.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:31.7.0 editor:newline (input.hidden-input)
     -0:31.5.0 intentions:highlight (input.hidden-input)
     -0:31.3.0 core:save (input.hidden-input)
     -0:09.1.0 intentions:highlight (input.hidden-input)
     -0:09.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.1 
atom-ternjs 0.18.3 
atom-wordpress 0.3.0 
autocomplete-php 0.3.7 
autocomplete-wordpress-hooks 0.2.3 
autoprefixer 3.7.1 
busy-signal 1.4.3 
color-picker 2.3.0 
emmet 2.4.3 
file-icons 2.1.24 
fonts 3.1.0 
goto-definition 1.3.4 
highlight-selected 0.14.0 
ide-php 0.7.15 
intentions 1.1.5 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.7.1 
livestyle-atom 0.2.10 
lorem 1.5.0 
materialize-css 0.5.1 
php-integrator-autocomplete-plus 1.6.2 
pigments 0.40.2 
remote-ftp 2.2.0 
teletype 0.13.3 
terminal-plus 0.14.5 
todo-show 2.3.2 
wordpress-api 1.2.2 
wordpress-autocomplete 1.5.0 
```

**Comment by aminya** [comment]
Close in favor of the already reported issue: #571

Please add more information to that issue, if it happens in the latest version of Atom and linter.
