### ISSUE TITLE
SyntaxError: Unexpected end of JSON input while parsing near

### ISSUE THREAD

**Issue by adammenges** [steelbrain/linter-ui-default#519]
During install I see the following error, thoughts?

![linter-bug](https://user-images.githubusercontent.com/817438/47383176-eccd3c80-d6b8-11e8-8351-700efed1c31a.gif)

Contents of that debugging log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
1 verbose cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/Users/adammenges/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/Users/adammenges/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/linter-ui-default/versions/1.7.1/tarball',
1 verbose cli   '--runtime=electron',
1 verbose cli   '--target=2.0.7',
1 verbose cli   '--dist-url=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v8.9.3
4 verbose npm-session 14f18616e6c6ca4b
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://www.atom.io/api/packages/linter-ui-default/versions/1.7.1/tarball 571ms
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/linter-ui-default/versions/1.7.1/tarball fetched in 584ms
9 timing stage:loadCurrentTree Completed in 744ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 0ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule linter-ui-default@1.7.1 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/disposable-event 10ms (from cache)
18 http fetch GET 200 https://registry.npmjs.org/atom-package-deps 11ms (from cache)
19 http fetch GET 200 https://registry.npmjs.org/marked 12ms (from cache)
20 http fetch GET 200 https://registry.npmjs.org/sb-debounce 11ms (from cache)
21 http fetch GET 200 https://registry.npmjs.org/react 13ms (from cache)
22 http fetch GET 200 https://registry.npmjs.org/sb-react-table 14ms (from cache)
23 http fetch GET 200 https://registry.npmjs.org/react-dom 14ms (from cache)
24 silly pacote range manifest for atom-package-deps@^4.3.1 fetched in 17ms
25 silly resolveWithNewModule atom-package-deps@4.6.2 checking installable status
26 silly pacote range manifest for disposable-event@^1.0.3 fetched in 17ms
27 silly resolveWithNewModule disposable-event@1.0.3 checking installable status
28 silly fetchPackageMetaData error for react-dom@^16.0.0 Unexpected end of JSON input while parsing near '...orzfUwjSPI6URv4H4YS9Y'
29 silly pacote range manifest for sb-debounce@^1.0.1 fetched in 17ms
30 silly resolveWithNewModule sb-debounce@1.0.2 checking installable status
31 silly pacote range manifest for marked@^0.3.9 fetched in 18ms
32 silly resolveWithNewModule marked@0.3.19 checking installable status
33 silly pacote range manifest for react@^16.0.0 fetched in 19ms
34 silly resolveWithNewModule react@16.5.2 checking installable status
35 silly pacote range manifest for sb-react-table@^1.0.2 fetched in 20ms
36 silly resolveWithNewModule sb-react-table@1.0.2 checking installable status
37 timing stage:rollbackFailedOptional Completed in 0ms
38 timing stage:runTopLevelLifecycles Completed in 776ms
39 silly saveTree apm-install-dir-118923-28431-7t1j4u.8a0zn
39 silly saveTree `-- linter-ui-default@1.7.1
39 silly saveTree   +-- atom-package-deps@4.6.2
39 silly saveTree   +-- disposable-event@1.0.3
39 silly saveTree   +-- marked@0.3.19
39 silly saveTree   +-- react@16.5.2
39 silly saveTree   +-- sb-debounce@1.0.2
39 silly saveTree   `-- sb-react-table@1.0.2
40 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...orzfUwjSPI6URv4H4YS9Y'
40 verbose stack     at JSON.parse (<anonymous>)
40 verbose stack     at parseJson (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
40 verbose stack     at consumeBody.call.then.buffer (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
40 verbose stack     at <anonymous>
40 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
41 verbose cwd /private/var/folders/v9/1kmsxk8142vfvtrd3th17d5m0000gq/T/apm-install-dir-118923-28431-7t1j4u.8a0zn
42 verbose Darwin 18.0.0
43 verbose argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/adammenges/.atom/.apm/.apmrc" "--userconfig" "/Users/adammenges/.atom/.apmrc" "install" "https://www.atom.io/api/packages/linter-ui-default/versions/1.7.1/tarball" "--runtime=electron" "--target=2.0.7" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--global-style"
44 verbose node v8.9.3
45 verbose npm  v6.2.0
46 error Unexpected end of JSON input while parsing near '...orzfUwjSPI6URv4H4YS9Y'
47 verbose exit [ 1, true ]
```

**Comment by adammenges** [comment]
FWIW Atom is at the latest version: 1.32.0

Here are my installed packages, all on the latest versions:
* atom-ide-ui
* aurora-theme
* autoclose-html
* busy-signal
* city-lights-syntax
* city-lights-ui
* color-picker
* css-snippets
* highlight-selected
* ide-css
* ide-html
* ide-python
* ide-typescript
* intentions
* language-javascript-jsx
* linter
* linter-pylint
* minimap
* nord-atom-syntax
* nord-atom-ui
* react
* space-tab
* sync-settings
* teletype
* zentabs

**Comment by adammenges** [comment]
Also the part of the JSON it fails at changes between a few different points depending on the run, for whatever reason:

``` bash
⇒  apm install linter-ui-default
Installing linter-ui-default to /Users/adammenges/.atom/packages ✗

Unexpected end of JSON input while parsing near '...j2BuBXtbnfEJD7ZcQXx/Q'

A complete log of this run can be found in: /Users/adammenges/.atom/.apm/_logs/2018-10-29T19_45_02_402Z-debug.log

⇒  apm install linter-ui-default
Installing linter-ui-default to /Users/adammenges/.atom/packages ✗

Unexpected end of JSON input while parsing near '..._hasShrinkwrap":false'

A complete log of this run can be found in: /Users/adammenges/.atom/.apm/_logs/2018-10-29T19_45_05_970Z-debug.log
```

**Comment by steelbrain** [comment]
From our previous experiences, people with system proxies have this issue. Their proxies try to inject stuff into Github's APM response format (IIRC?)

**Comment by abbassiddiqi** [comment]
Cleaning the corrupted local npm cache may fix this error.

    npm cache clean --force

Just run your npm command again after executing the above command in your terminal.

----------

There could be few other reasons for the invalid JSON, as described in the official documentation [here](https://docs.npmjs.com/common-errors#invalid-json).

The official `npm` website has well documented most of the common errors. But unfortunately they don’t appear on the top results when you google the error.

**Comment by adammenges** [comment]
Got it, thanks for the links to the docs! Hope this helps someone else find it more quickly.
