### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by oscar-SHIFT** [steelbrain/linter-ui-default#521]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At C:\Users\oscar\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:75360)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:75292)
    at TextEditorComponent.renderContent (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:73818)
    at TextEditorComponent.renderScrollContainer (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:73278)
    at TextEditorComponent.render (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:72057)
    at Object.updateSync (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:14:126499)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:69915)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:67302)
    at TextEditorComponent.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:65971)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:246:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -2:47.1.0 core:copy (span.syntax--entity.syntax--name.syntax--tag)
     -2:44.7.0 editor:newline (input.hidden-input)
     -2:43.6.0 core:backspace (input.hidden-input)
     -2:38.6.0 intentions:highlight (input.hidden-input)
     -2:38.2.0 core:paste (input.hidden-input)
     -2:26.8.0 core:backspace (input.hidden-input)
 12x -2:12.2.0 intentions:highlight (input.hidden-input)
     -2:11.4.0 core:save (input.hidden-input)
     -1:48.1.0 intentions:highlight (input.hidden-input)
     -1:47.8.0 core:copy (input.hidden-input)
     -1:45.1.0 intentions:highlight (input.hidden-input)
     -1:44.7.0 core:paste (input.hidden-input)
  8x -1:42.2.0 core:backspace (input.hidden-input)
     -1:37.1.0 intentions:highlight (input.hidden-input)
     -1:36.8.0 core:save (input.hidden-input)
     -0:18.7.0 script:kill-process (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.7 
atom-runner 2.7.1 
autocomplete-python 1.10.12 
busy-signal 1.4.3 
file-icons 2.1.24 
Hydrogen 2.6.0 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
open-recent 5.0.0 
pane-layout-plus 0.7.4 
pigments 0.40.2 
print-code 0.7.1 
python-runner 1.2.0 
python-tools 0.6.9 
script 3.18.1 
script-runner 2.3.1 
```

**Comment by clair513** [comment]
I have similar issue in my Atom. [Here are relevant details](https://github.com/atom/atom/issues/18343).

**Comment by aminya** [comment]
Close in favor of the already reported issue: #571

Please add more information to that issue, if it happens in the latest version of Atom and linter.
