### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tree' of null

### ISSUE THREAD

**Issue by TanyaGir** [steelbrain/linter-ui-default#523]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'tree' of null

```
At C:\Users\Tanya Sharma\AppData\Local\atom\app-1.32.1\resources\app\static\<embedded>:11

TypeError: Cannot read property 'tree' of null
    at TreeSitterLanguageMode.get tree [as tree] (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:2937844)
    at TreeSitterLanguageMode.getFoldableRangeContainingPoint (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:2940135)
    at TreeSitterLanguageMode.isFoldableAtRow (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:2939234)
    at TextEditor.isFoldableAtBufferRow (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:48170)
    at TextEditorComponent.queryLineNumbersToRender (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:80177)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:69734)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:67306)
    at TextEditorComponent.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:65975)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:246:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
  8x -8:48.6.0 core:move-down (input.hidden-input)
     -8:36 intentions:highlight (input.hidden-input)
     -8:35.7.0 core:copy (input.hidden-input)
     -8:27.6.0 core:paste (input.hidden-input)
     -8:27.2.0 core:confirm (input.hidden-input)
  4x -8:23.7.0 core:move-left (input.hidden-input)
 17x -8:21.1.0 core:move-down (input.hidden-input)
     -8:12.5.0 core:move-up (input.hidden-input)
 13x -8:11 core:move-down (input.hidden-input)
 43x -8:04.7.0 core:move-up (input.hidden-input)
 35x -7:57.3.0 core:move-down (input.hidden-input)
 18x -2:10.4.0 core:move-up (input.hidden-input)
 20x -0:27.2.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
emmet 2.4.3 
intentions 1.1.5 
jslint 1.5.1 
linter 2.2.0 
linter-eslint 8.4.1 
linter-pylint 2.1.1 
linter-ui-default 1.7.1 
minimap 4.29.9 
prettier-atom 0.55.2 
python-autopep8 0.1.3 
remote-ftp 2.2.0 
split-diff 1.5.3 
```

**Comment by steelbrain** [comment]
Hey this looks like an Atom bug, can you please transfer this to Github's Atom repository?
