### ISSUE TITLE
Uncaught TypeError: Editors is not a constructor

### ISSUE THREAD

**Issue by darkpio** [steelbrain/linter-ui-default#528]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Unknown Windows version
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Editors is not a constructor

```
At C:\Users\darkp\.atom\packages\linter-ui-default\lib\main.js:65

TypeError: Editors is not a constructor
    at /packages/linter-ui-default/lib/main.js:65:27
    at Config.observeKeyPath (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:332465)
    at Config.observe (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:326976)
    at LinterUI.observeShowDecorations (/packages/linter-ui-default/lib/main.js:63:42)
```

### Commands

```
 18x -9:33.3.0 core:backspace (input.hidden-input)
  2x -3:14.3.0 core:paste (div.line)
     -2:08.0 sync-settings:restore (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.1 
atom-python-virtualenv 1.0.2 
autocomplete-python 1.10.11 
busy-signal 1.4.3 
intentions 1.1.5 
kite 0.110.0 
line-ending-converter 1.3.2 
linter 2.2.0 
linter-flake8 2.3.0 
linter-ui-default 1.7.1 
minimap 4.29.8 
python-autopep8 0.1.3 
python-indent 1.1.6 
python-tools 0.6.9 
script 3.18.1 
seti-icons 1.5.4 
seti-syntax 1.2.0 
seti-ui 1.11.0 
sync-settings 0.8.6 
teletype 0.13.3 
```

**Comment by aminya** [comment]
This is fixed in the latest version
