### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by rj4ck** [steelbrain/linter-ui-default#531]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At C:\Users\rjack\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:75663)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:75595)
    at TextEditorComponent.renderContent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:74121)
    at TextEditorComponent.renderScrollContainer (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:73581)
    at TextEditorComponent.render (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:72360)
    at Object.updateSync (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:126536)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:70218)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:67605)
    at TextEditorComponent.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:66274)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:246:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -3:48.1.0 intentions:highlight (input.hidden-input)
     -3:48 core:save (input.hidden-input)
     -3:39.8.0 editor:newline (input.hidden-input)
     -3:39.6.0 intentions:highlight (input.hidden-input)
     -3:39.5.0 core:paste (input.hidden-input)
     -3:38.9.0 editor:newline (input.hidden-input)
     -3:38.7.0 intentions:highlight (input.hidden-input)
     -3:38.6.0 core:save (input.hidden-input)
  2x -3:28.7.0 core:backspace (input.hidden-input)
     -3:27.5.0 intentions:highlight (input.hidden-input)
     -3:27.4.0 core:save (input.hidden-input)
     -1:05.2.0 core:move-left (input.hidden-input)
     -0:30.5.0 intentions:highlight (input.hidden-input)
  5x -0:30.3.0 core:undo (input.hidden-input)
     -0:26.7.0 intentions:highlight (input.hidden-input)
     -0:26.6.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 2.0.0 
editorconfig 2.3.0 
file-header 1.13.9 
intentions 1.1.5 
linter 2.3.0 
linter-eslint 8.5.2 
linter-ui-default 1.7.1 
platformio-ide-terminal 2.9.0 
terminal-plus 0.14.5 
```

**Comment by aminya** [comment]
Close in favor of the already reported issue: #571

Please add more information to that issue, if it happens in the latest version of Atom and linter.
