### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ameenmattar** [steelbrain/linter-ui-default#533]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.13.6
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1103304)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1099010)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:89306)
    at TextEditorComponent.queryScreenLinesToRender (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:79324)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:69977)
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:107330)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:9:50)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-django 0.3.2 
atom-runner 2.7.1 
atom-ternjs 0.18.3 
autocomplete-json 5.5.2 
autocomplete-modules 2.2.2 
autocomplete-python 1.10.12 
busy-signal 1.4.3 
clipboard-plus 0.5.1 
css-in-js 1.4.0 
django-templates 0.5.0 
file-icons 2.1.25 
highlight-selected 0.14.0 
intentions 1.1.5 
language-babel 2.85.0 
linter 2.2.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
nuclide 0.357.0 
prettier-atom 0.55.2 
pretty-json 2.0.3 
python-iresolve 0.0.3 
python-isort 0.0.7 
react-es6-snippets 0.3.0 
react-es7-snippets 0.3.13 
react-native-snippets 0.3.0 
script 3.18.1 
```

**Comment by aminya** [comment]
Closing in favor of another duplicate issue. https://github.com/steelbrain/linter-ui-default/issues/538
