### ISSUE TITLE
Uncaught TypeError: Cannot destructure property `textNodes` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by yns99** [steelbrain/linter-ui-default#534]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Cannot destructure property `textNodes` of 'undefined' or 'null'.

```
At C:\Users\HI\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11

TypeError: Cannot destructure property `textNodes` of 'undefined' or 'null'.
    at TextEditorComponent.screenPositionForPixelPosition (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:107558)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:9:50)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
  7x -9:28.8.0 core:backspace (input.hidden-input)
  2x -9:21.5.0 core:move-down (input.hidden-input)
     -9:20.5.0 autocomplete-plus:confirm (input.hidden-input)
     -9:05.7.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -9:05.6.0 editor:newline (input.hidden-input)
  2x -9:01.5.0 core:backspace (input.hidden-input)
     -9:00.1.0 core:move-right (input.hidden-input)
  5x -8:59.9.0 core:backspace (input.hidden-input)
     -8:38.4.0 intentions:highlight (input.hidden-input)
  8x -8:38.1.0 core:undo (input.hidden-input)
  3x -7:32.1.0 core:backspace (input.hidden-input)
  2x -6:01.5.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
 25x -5:03.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-live-server 2.3.0 
busy-signal 2.0.0 
emmet 2.4.3 
file-icons 2.1.30 
intentions 1.1.5 
linter 2.3.0 
linter-phpcs 1.6.12 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-pigments 0.2.2 
pigments 0.40.2 
```

**Comment by aminya** [comment]
Similar to https://github.com/steelbrain/linter-ui-default/issues/571
