### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by rayvikram** [steelbrain/linter-ui-default#538]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\vikram\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:14:1104122)
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:14:1099828)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:14:89305)
    at TextEditorComponent.queryScreenLinesToRender (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:79324)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:69977)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:67605)
    at TextEditorComponent.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:66274)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:246:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
  4x -7:18.2.0 core:backspace (input.hidden-input)
     -0:47.3.0 intentions:highlight (input.hidden-input)
     -0:47 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
busy-signal 1.4.3 
csslint 1.2.0 
emmet 2.4.3 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-jshint 3.1.11 
linter-ui-default 1.7.1 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by TizianoGC** [comment]
Same here. This bug starts to occur after I switch from a tab in which I was using Hydrogen to another one. Here are my specs:

*Atom*: 1.35.1 x64
*Electron*: 2.0.18
*Chrome*: 61.0.3163.100
*Node*: v8.9.3
*OS*: Ubuntu 18.04

**Comment by turnpiece** [comment]
Any update on this? I'm getting the same thing and it's making Atom virtually unusable.

**Comment by aminya** [comment]
This is from a function that calls an Atom function. Similar to https://github.com/steelbrain/linter-ui-default/issues/571
