### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by AIasd** [steelbrain/linter-ui-default#539]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.13.3
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1104184)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1099890)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:89305)
    at TextEditorComponent.queryScreenLinesToRender (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:79324)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:69977)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:67605)
    at TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:66274)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:246:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -4:19 core:paste (input.hidden-input)
  5x -4:18.1.0 core:save (input.hidden-input)
 27x -3:04.9.0 find-and-replace:select-next (input.hidden-input)
     -2:44.8.0 editor:newline (input.hidden-input)
  2x -2:42.5.0 core:backspace (input.hidden-input)
  2x -2:32.9.0 core:save (input.hidden-input)
     -2:26.3.0 core:undo (input.hidden-input)
     -2:25.7.0 core:save (input.hidden-input)
     -1:45.3.0 core:copy (input.hidden-input)
     -1:44.6.0 core:paste (input.hidden-input)
     -1:43.9.0 core:move-left (input.hidden-input)
  6x -1:43.7.0 core:backspace (input.hidden-input)
     -1:39.7.0 core:save (input.hidden-input)
     -1:05.0 core:undo (input.hidden-input)
     -1:03.5.0 core:redo (input.hidden-input)
  4x -1:01.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 2.0.0 
intentions 1.1.5 
language-ocaml 1.9.5 
linter 2.3.0 
linter-pyflakes 0.3.2 
linter-python-pep8 0.2.0 
linter-ui-default 1.7.1 
prettier-atom 0.56.3 
```

**Comment by aminya** [comment]
Closing in favor of another duplicate issue. https://github.com/steelbrain/linter-ui-default/issues/538
