### ISSUE TITLE
Uncaught TypeError: Cannot destructure property `length` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by evgeniy1st** [steelbrain/linter-ui-default#541]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.0 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Cannot destructure property `length` of 'undefined' or 'null'.

```
At C:\Users\Евгений\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11

TypeError: Cannot destructure property `length` of 'undefined' or 'null'.
    at TextMateLanguageMode.indentLevelForLine (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:556326)
    at TextMateLanguageMode.endRowForCodeFoldAtRow (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:558864)
    at TextMateLanguageMode.endRowForFoldAtRow (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:558563)
    at TextMateLanguageMode.isFoldableAtRow (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:554644)
    at TextEditor.isFoldableAtBufferRow (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:48469)
    at TextEditorComponent.queryLineNumbersToRender (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:80476)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:70033)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:67605)
    at TextEditorComponent.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:66274)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:246:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
  6x -7:12.9.0 core:move-down (div.tool-panel.tree-view)
  6x -7:12 core:move-up (div.tool-panel.tree-view)
     -4:59.6.0 editor:newline (input.hidden-input)
  3x -4:59.2.0 intentions:highlight (input.hidden-input)
     -4:58.7.0 core:paste (input.hidden-input)
     -1:21.4.0 editor:newline (input.hidden-input)
 10x -1:21.1.0 intentions:highlight (input.hidden-input)
     -1:20.3.0 core:paste (input.hidden-input)
 92x -1:18 intentions:highlight (input.hidden-input)
     -1:14.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-css-comb 3.5.1 
atom-html-preview 0.2.6 
atom-live-server 2.3.0 
busy-signal 2.0.0 
emmet 2.4.3 
highlight-line 0.12.0 
Hydrogen 2.9.0 
intentions 1.1.5 
language-vue 0.24.0 
linter 2.3.0 
linter-php 1.6.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
vue-autocomplete 0.1.1 
```

**Comment by aminya** [comment]
Closing in favor of another duplicate issue. https://github.com/steelbrain/linter-ui-default/issues/538
