### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by alexgvozden** [steelbrain/linter-ui-default#548]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:518146)
    at TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:27540)
    at Editor.decorateMarker (/packages/linter-ui-default/lib/editor/index.js:332:23)
    at _loop (/packages/linter-ui-default/lib/editor/index.js:315:12)
    at Editor.apply (/packages/linter-ui-default/lib/editor/index.js:303:61)
    at /packages/linter-ui-default/lib/editors.js:60:48
    at Array.forEach (<anonymous>)
    at /packages/linter-ui-default/lib/editors.js:60:23
    at Array.forEach (<anonymous>)
    at Editors.update (/packages/linter-ui-default/lib/editors.js:57:15)
    at LinterUI.render (/packages/linter-ui-default/lib/main.js:87:17)
    at /packages/linter/lib/ui-registry.js:32:16
    at Set.forEach (<anonymous>)
    at UIRegistry.render (/packages/linter/lib/ui-registry.js:31:20)
    at /packages/linter/lib/main.js:170:23
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1207528)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1208969)
    at MessageRegistry.update (/packages/linter/lib/message-registry.js:126:20)
    at invokeFunc (/packages/linter/node_modules/lodash/debounce.js:95:19)
    at leadingEdge (/packages/linter/node_modules/lodash/debounce.js:105:22)
    at /packages/linter/node_modules/lodash/debounce.js:172:16)
    at /packages/linter/lib/message-registry.js:49:10)
    at MessageRegistry.set (/packages/linter/lib/message-registry.js:50:4)
    at /packages/linter/lib/main.js:159:29
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1207528)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1208969)
    at /packages/linter/lib/indie-registry.js:33:20
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1207528)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1208969)
    at IndieDelegate.setAllMessages (/packages/linter/lib/indie-delegate.js:81:18)
    at ErrorPusher.pushErrors (/packages/atom-typescript/dist/main/errorPusher.js:60:25)
    at invokeFunc (/packages/atom-typescript/node_modules/lodash/lodash.js:10333:23)
    at trailingEdge (/packages/atom-typescript/node_modules/lodash/lodash.js:10382:18)
    at timerExpired (/packages/atom-typescript/node_modules/lodash/lodash.js:10370:18)
```

### Commands

```
     -0:31.3.0 core:cut (input.hidden-input)
  5x -0:29.8.0 core:delete (input.hidden-input)
  6x -0:27.2.0 core:backspace (input.hidden-input)
     -0:23.2.0 docblockr:parse-enter (input.hidden-input)
     -0:23.2.0 editor:newline (input.hidden-input)
     -0:20 core:paste (input.hidden-input)
     -0:19.5.0 core:save (input.hidden-input)
     -0:18.2.0 prettier:format (input.hidden-input)
     -0:16.5.0 typescript:hide-signature-help (input.hidden-input)
     -0:16.5.0 editor:consolidate-selections (input.hidden-input)
     -0:16.5.0 core:cancel (input.hidden-input)
     -0:09.5.0 core:backspace (input.hidden-input)
     -0:08.9.0 core:save (input.hidden-input)
     -0:08.8.0 linter:lint (atom-text-editor.editor.linter-tslint-compatible-editor.typescript-editor.is-focused)
     -0:07.5.0 core:save (input.hidden-input)
     -0:02.9.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-import-cost 1.2.0 
atom-typescript 13.3.0 
autoclose-html 0.23.0 
autocomplete-modules 2.3.0 
busy-signal 2.0.1 
change-case 0.6.5 
docblockr 0.13.7 
file-icons 2.1.33 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.13.3 
js-refactor 0.8.1 
jsx-comment 0.2.0 
language-babel 2.85.0 
language-javascript-jsx 0.3.7 
linter 2.3.0 
linter-eslint 8.5.5 
linter-stylelint 4.4.9 
linter-tslint 1.10.28 
linter-ui-default 1.7.1 
node-debug 0.1.7 
pigments 0.40.2 
prettier-atom 0.57.2 
project-manager 3.3.7 
tree-view-auto-collapse 1.0.2 
```

**Comment by aminya** [comment]
Closing in favor of an already reported issue: https://github.com/steelbrain/linter-ui-default/issues/492
