### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by CGNAT** [steelbrain/linter-ui-default#550]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.3
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /usr/share/atom/resources/app/static/<embedded>:11

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (/usr/share/atom/resources/app/static/<embedded>:11:76051)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (/usr/share/atom/resources/app/static/<embedded>:11:75983)
    at TextEditorComponent.renderContent (/usr/share/atom/resources/app/static/<embedded>:11:74509)
    at TextEditorComponent.renderScrollContainer (/usr/share/atom/resources/app/static/<embedded>:11:73969)
    at TextEditorComponent.render (/usr/share/atom/resources/app/static/<embedded>:11:72748)
    at Object.updateSync (/usr/share/atom/resources/app/static/<embedded>:14:134831)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/usr/share/atom/resources/app/static/<embedded>:11:70606)
    at TextEditorComponent.updateSync (/usr/share/atom/resources/app/static/<embedded>:11:67993)
    at TextEditorComponent.pixelPositionForScreenPosition (/usr/share/atom/resources/app/static/<embedded>:11:66662)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:253:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -5:47 pane:split-down-and-copy-active-item (span.syntax--entity.syntax--name.syntax--function)
     -5:46.2.0 intentions:highlight (input.hidden-input)
  2x -5:45.1.0 core:undo (input.hidden-input)
     -5:40.2.0 pane:close (div.title)
     -5:36.7.0 core:copy (span.syntax--entity.syntax--name.syntax--function)
     -0:55.8.0 intentions:highlight (input.hidden-input)
     -0:55.5.0 find-and-replace:show (input.hidden-input)
  2x -0:51.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
aesthetic-ui 4.0.0 
atom-beautify 0.33.4 
autocomplete-python 1.14.1 
autocomplete-python-jedi 1.10.3-0 
busy-signal 2.0.1 
darkpython-syntax 0.5.0 
highlight-selected 0.16.0 
ide-python 1.4.1 
intentions 1.1.5 
isotope-ui 2.8.5 
linter 2.3.0 
linter-flake8 2.4.0 
linter-python 3.1.2 
linter-ui-default 1.7.1 
open-recent 5.0.0 
pigments 0.40.2 
python-indent 1.2.3 
python-tools 0.6.9 
slime 2.4.0 
styri-syntax 1.0.0 
```

**Comment by aminya** [comment]
Close in favor of the already reported issue: #571

Please add more information to that issue, if it happens in the latest version of Atom and linter.
