### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by trekkie4life** [steelbrain/linter-ui-default#551]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1198145)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1193815)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:94192)
    at TextEditorComponent.queryScreenLinesToRender (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:79712)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:70365)
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:107777)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:9:50)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
  2x -6:29.7.0 editor:newline (input.hidden-input)
     -6:19.6.0 core:undo (input.hidden-input)
  3x -6:18 core:backspace (input.hidden-input)
  2x -6:12.8.0 find-and-replace:select-next (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
erb-snippets 1.1.0 
file-icons 2.1.33 
intentions 1.1.5 
linter 2.3.1 
linter-rubocop 2.4.2 
linter-ui-default 1.7.1 
ruby-block 0.3.6 
```

**Comment by aminya** [comment]
Closing in favor of another duplicate issue. https://github.com/steelbrain/linter-ui-default/issues/538
