### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by open-all** [steelbrain/linter-ui-default#552]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:76051)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:75983)
    at TextEditorComponent.renderContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:74509)
    at TextEditorComponent.renderScrollContainer (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:73969)
    at TextEditorComponent.render (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:72748)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:136093)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:70606)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:67993)
    at TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:66662)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:253:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -0:07.9.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-one-dark-ui.teletype-Authenticated)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.17 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
autocomplete-java 1.2.7 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
intentions 1.1.5 
jackhammer-syntax 1.1.0 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-jshint 3.1.16 
linter-ui-default 1.7.1 
pigments 0.40.2 
script 3.18.1 
styri-syntax 1.0.0 
Sublime-Style-Column-Selection 1.7.5 
teletype 0.13.4 
xml-formatter 0.13.0 
```

**Comment by aminya** [comment]
Close in favor of the already reported issue: #571

Please add more information to that issue, if it happens in the latest version of Atom and linter.
