### ISSUE TITLE
Uncaught TypeError: Cannot read property 'matchesParams' of undefined

### ISSUE THREAD

**Issue by karel-un** [steelbrain/linter-ui-default#556]
This error keeps popping up when I open file in atom.io (tried with Python and YAML file types) and click into file. After click first error pop-up occurs. Then if I move mouse cursor over file it keeps popping up (looks like it pops up when mouse cursor is stopped for few milliseconds). When mouse cursor doesn't move it doesn't pop-up. Selecting words with double click doesn't work either. And when I open bottom find panel it shows up, but doesn't find nothing.

After disabling or uninstalling linter-ui-default errors stop popping up, but find panel still doesn't work.

[Enter steps to reproduce:]

1. open file in atom.io (tried with Python and YAML files)
2. click into file and first error pop-up message shows up
3. move mouse over file and each few seconds another error pop-up shows up

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: "Gentoo Base
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'matchesParams' of undefined

```
At /usr/local/share/atom/resources/app/static/<embedded>:14

TypeError: Cannot read property 'matchesParams' of undefined
    at /usr/local/share/atom/resources/app/static/<embedded>:14:77917
    at Set.forEach (<anonymous>)
    at MarkerLayer.findMarkers (/usr/local/share/atom/resources/app/static/<embedded>:14:77859)
    at DisplayMarkerLayer.findMarkers (/usr/local/share/atom/resources/app/static/<embedded>:14:1122827)
    at decorationCountsByLayer.forEach (/usr/local/share/atom/resources/app/static/<embedded>:11:517723)
    at Map.forEach (<anonymous>)
    at DecorationManager.decorationPropertiesByMarkerForScreenRowRange (/usr/local/share/atom/resources/app/static/<embedded>:11:517697)
    at TextEditorComponent.queryDecorationsToRender (/usr/local/share/atom/resources/app/static/<embedded>:11:82388)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/usr/local/share/atom/resources/app/static/<embedded>:11:70481)
    at TextEditorComponent.updateSync (/usr/local/share/atom/resources/app/static/<embedded>:11:67993)
    at TextEditorComponent.pixelPositionForScreenPosition (/usr/local/share/atom/resources/app/static/<embedded>:11:66662)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:253:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -1:16.5.0 intentions:highlight (input.hidden-input)
     -1:16.3.0 find-and-replace:show (input.hidden-input)
     -1:05.4.0 settings-view:uninstall-packages (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.16.0 
busy-signal 2.0.1 
git-plus 8.7.1 
git-time-machine 2.1.0 
goto 1.8.3 
intentions 1.1.5 
linter 2.3.1 
linter-flake8 2.4.0 
linter-pycodestyle 2.1.3 
linter-ui-default 1.8.0 
markdown-pdf 2.2.0 
minimap 4.29.9 
python-indent 1.2.3 
python-tools 0.6.9 
script 3.18.1 
```

**Comment by karel-un** [comment]
SOLVED by manually unmasking nodejs 10.16.3, updating it and reinstalling atom.io. Looks like atom.io v1.40.1 requires nodejs > 8.12.0 (which is highest version stable on Gentoo).
