### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by FlavioTrelles** [steelbrain/linter-ui-default#557]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At C:\Users\FlavioDaniel\.atom\packages\linter-ui-default\lib\helpers.js:29

TypeError: Cannot read property 'file' of undefined
    at /packages/linter-ui-default/lib/helpers.js:29:27)
    at /packages/linter-ui-default/lib/editors.js:51:24
    at Array.forEach (<anonymous>)
    at Editors.update (/packages/linter-ui-default/lib/editors.js:50:13)
    at LinterUI.render (/packages/linter-ui-default/lib/main.js:87:17)
    at /packages/linter/lib/ui-registry.js:32:16
    at Set.forEach (<anonymous>)
    at UIRegistry.render (/packages/linter/lib/ui-registry.js:31:20)
    at /packages/linter/lib/main.js:187:23
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at MessageRegistry.update (/packages/linter/lib/message-registry.js:130:20)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -5:47.2.0 editor:indent (input.hidden-input)
     -5:46.3.0 intentions:highlight (input.hidden-input)
     -5:46.1.0 core:paste (input.hidden-input)
  2x -5:40.7.0 core:backspace (input.hidden-input)
     -5:23.4.0 platformio-ide:target:upload (input.hidden-input)
     -5:23.4.0 platformio-ide:target:upload-C:\Users\FlavioDaniel\Documents\PlatformIO\Projects\Cigarrillera (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:41.5.0 intentions:highlight (input.hidden-input)
     -3:41.2.0 core:select-all (input.hidden-input)
     -3:00.4.0 core:copy (span.syntax--string.syntax--quoted.syntax--other)
     -2:07.0 platformio-ide:target:build (input.hidden-input)
     -2:07.0 platformio-ide:target:build-C:\Users\FlavioDaniel\Documents\PlatformIO\Projects\Cigarrillera (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:44.1.0 core:save (input.hidden-input)
     -1:32.9.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
  2x -1:32.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:30.6.0 platformio-ide:target:build (input.hidden-input)
     -0:30.6.0 platformio-ide:target:build-C:\Users\FlavioDaniel\Documents\PlatformIO\Projects\Cigarrillera (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-clang 0.12.0 
build 0.70.0 
busy 0.7.0 
busy-signal 1.4.3 
file-icons 2.1.22 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.8.0 
minimap 4.29.8 
platformio-ide 2.4.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.4 
tool-bar 1.1.12 
```

**Comment by aminya** [comment]
Fixed in 2.1.2
