### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Mozart409** [steelbrain/linter-ui-default#558]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:76051)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:75983)
    at TextEditorComponent.renderContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:74509)
    at TextEditorComponent.renderScrollContainer (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:73969)
    at TextEditorComponent.render (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:72748)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:136093)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:70606)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:67993)
    at TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:66662)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:253:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -1:17.4.0 docblockr:parse-enter (input.hidden-input)
     -1:17.4.0 editor:newline (input.hidden-input)
     -1:17.2.0 docblockr:parse-enter (input.hidden-input)
     -1:17.2.0 editor:newline (input.hidden-input)
     -1:17 core:paste (input.hidden-input)
     -1:13.6.0 core:copy (input.hidden-input)
     -1:12 docblockr:parse-enter (input.hidden-input)
     -1:12 editor:newline (input.hidden-input)
     -1:11.8.0 core:paste (input.hidden-input)
     -1:08.8.0 core:cut (input.hidden-input)
     -1:05.8.0 core:paste (input.hidden-input)
     -0:46.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-brackets-glow 0.6.0 
atom-electron-snippets 2.0.3 
atom-react 0.4.0 
atom-ternjs 0.20.0 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
busy-signal 2.0.1 
color-picker 2.3.0 
docblockr 0.13.7 
expand-region 0.5.0 
git-control 0.9.0 
git-time-machine 2.1.0 
highlight-line 0.12.0 
highlight-selected 0.16.0 
hyperclick 0.1.5 
intentions 1.1.5 
jquery-snippets 11.0.0 
js-hyperclick 1.19.0 
language-patch 1.2.0 
linter 2.3.1 
linter-csslint 2.0.6 
linter-eslint 8.5.5 
linter-jsonlint 1.4.0 
linter-markdown 5.2.10 
linter-tidy 2.4.0 
linter-ui-default 1.8.0 
local-history 4.3.1 
lorem 4.0.0 
markdown-badges-snippets 0.3.1 
markdown-preview-plus 3.10.0 
merge-conflicts 1.4.5 
pigments 0.40.2 
pp-markdown 0.0.2 
pretty-json 2.1.2 
project-plus 1.0.0 
react 0.18.0 
react-snippets 1.1.3 
seti-icons 1.5.4 
svg-preview 0.14.0 
todo-show 2.3.2 
wakatime 7.1.1 
```

**Comment by aminya** [comment]
Close in favor of the already reported issue: #571

Please add more information to that issue, if it happens in the latest version of Atom and linter.
