### ISSUE TITLE
Uncaught TypeError: Invalid Point: ((11, 15), (11, 23))

### ISSUE THREAD

**Issue by Asc2011** [steelbrain/linter-ui-default#560]
[Enter steps to reproduce:]
create a point from Coffeescripts-AST-location-data
1. 
  { 
    first_line  : sr, first_column : sc
    last_line   : er, last_column  : ec
  } = node.locationData
  [ 
    new Point(1*sr, 1*sc),
    new Point(1*er, 1*ec)
  ]

2. alternative 
  [ 
    [ 12, 15],
    [ 12, 23]
  ]

Before i imported the Point-class i tried a plain-array.
Somehow a '1'-string was added to the column-parameter :
so a given 15 became a 151 and 23 ended up as 231 ?

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.8.0

### Stack Trace

Uncaught TypeError: Invalid Point: ((11, 15), (11, 23))

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

TypeError: Invalid Point: ((11, 15), (11, 23))
    at Function.Point.assertValid (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:49613)
    at TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:496434)
    at TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:496290)
    at MarkerLayer.markRange (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:78208)
    at TextBuffer.markRange (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:490124)
    at _loop (/packages/linter-ui-default/lib/editor/index.js:310:33)
    at Editor.apply (/packages/linter-ui-default/lib/editor/index.js:303:61)
    at /packages/linter-ui-default/lib/editors.js:60:48
    at Array.forEach (<anonymous>)
    at /packages/linter-ui-default/lib/editors.js:60:23
    at Array.forEach (<anonymous>)
    at Editors.update (/packages/linter-ui-default/lib/editors.js:57:15)
    at /packages/linter-ui-default/lib/main.js:60:28
    at Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:334261)
    at Config.observe (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:328743)
    at LinterUI.observeShowDecorations (/packages/linter-ui-default/lib/main.js:57:23)
```

### Commands

```
```

### Non-Core Packages

```
adatools 0.0.0 
atom-alignment 0.13.0 
atom-clock 0.1.17 
atom-cursor-indent 0.3.3 
atom-overtype-mode 0.5.0 
atom-runner 2.7.1 
atomic-chrome 0.3.3 
atomic-chrome-coffee 0.0.0 
autocomplete-tailwind 0.8.2 
busy-signal 2.0.1 
cobalt2-syntax 0.5.3 
coffee-compile 0.32.0 
coffee-navigator 0.0.18 
color-picker 2.3.0 
cson 2.0.1 
editorconfig 2.5.0 
find-scroll-marker 0.1.3 
ghost-text 0.0.1 
highlight-line 0.12.0 
hyperclick 0.1.5 
ide-svelte 0.1.1 
intentions 1.1.5 
json-converter 0.2.4 
language-ada 1.1.0 
language-cjsx 0.3.0 
language-cson 0.0.1 
language-ini 1.23.0 
language-markdown 0.37.0 
linter 2.3.1 
linter-coffeelint 2.0.20 
linter-jsonlint 1.4.0 
linter-ui-default 1.8.0 
local-history 4.3.1 
open 2.0.4 
package-list 0.1.2 
package-settings 1.1.0 
preferenzer 0.0.1 
prettier-atom 0.57.3 
process-palette 0.17.0 
Repl 0.5.0 
restart-atom 0.2.0 
rester 1.1.1 
rulerz 0.5.0 
script 3.18.1 
scroll-marker 0.3.2 
simple-block-cursor 0.6.0 
sort-lines 0.19.0 
terminal-tab 0.5.7 
todo-show 2.3.2 
twin-view 0.0.1 
typewriter 0.8.0 
```

**Comment by Asc2011** [comment]
my bad
