### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by nfortea** [steelbrain/linter-ui-default#561]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At C:\Users\nfortea\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:76051)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:75983)
    at TextEditorComponent.renderContent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:74509)
    at TextEditorComponent.renderScrollContainer (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:73969)
    at TextEditorComponent.render (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:72748)
    at Object.updateSync (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:136093)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:70606)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:67993)
    at TextEditorComponent.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:66662)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:253:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-minify 0.8.0 
autocomplete-php 0.3.7 
autocomplete-sql 0.5.0 
busy-signal 2.0.1 
color-picker 2.3.0 
intentions 1.1.5 
linter 2.3.1 
linter-csslint 2.0.6 
linter-htmlhint 1.6.3 
linter-ui-default 1.8.0 
pigments 0.40.2 
remote-ftp 2.2.2 
teletype 0.13.4 
wordpress-api 1.2.2 
```

**Comment by aminya** [comment]
Close in favor of the already reported issue: #571

Please add more information to that issue, if it happens in the latest version of Atom and linter.
