### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-package-path'

### ISSUE THREAD

**Issue by Che5ter** [steelbrain/linter-ui-default#563]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.8.0

### Stack Trace

Uncaught Error: Cannot find module 'atom-package-path'

```
At internal/modules/cjs/loader.js:586

Error: Cannot find module 'atom-package-path'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at /packages/linter-ui-default/node_modules/atom-package-deps/lib/index.js:50:24)
    at /packages/linter-ui-default/node_modules/atom-package-deps/lib/index.js:83:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at installLinterUIDefaultDeps (/packages/linter-ui-default/lib/index.js:28:9)
```

### Commands

```
```

### Non-Core Packages

```
autoclose-html 0.23.0 
busy-signal 2.0.1 
editorconfig 2.5.0 
fast-eslint 4.11.0 
indent-guide-improved 1.4.13 
intentions 1.1.5 
linter 2.3.1 
linter-ui-default 1.8.0 
pigments 0.40.2 
sync-settings 0.8.6 
```

**Comment by Arcanemagus** [comment]
Re-install the package, it looks like a dependency didn't get installed by Atom.
