### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by JamesSSA** [steelbrain/linter-ui-default#564]
1. Highlighted (with mouse) a function header in javascript (not including the function keyword).

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 19.10
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /usr/share/atom/resources/app/static/<embedded>:11

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (/usr/share/atom/resources/app/static/<embedded>:11:76051)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (/usr/share/atom/resources/app/static/<embedded>:11:75983)
    at TextEditorComponent.renderContent (/usr/share/atom/resources/app/static/<embedded>:11:74509)
    at TextEditorComponent.renderScrollContainer (/usr/share/atom/resources/app/static/<embedded>:11:73969)
    at TextEditorComponent.render (/usr/share/atom/resources/app/static/<embedded>:11:72748)
    at Object.updateSync (/usr/share/atom/resources/app/static/<embedded>:14:136093)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/usr/share/atom/resources/app/static/<embedded>:11:70606)
    at TextEditorComponent.updateSync (/usr/share/atom/resources/app/static/<embedded>:11:67993)
    at TextEditorComponent.pixelPositionForScreenPosition (/usr/share/atom/resources/app/static/<embedded>:11:66662)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:253:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -7:15.2.0 core:save (input.hidden-input)
  4x -4:41.4.0 core:backspace (input.hidden-input)
     -4:35 intentions:highlight (input.hidden-input)
     -4:34.9.0 core:save (input.hidden-input)
     -4:00.8.0 intentions:highlight (input.hidden-input)
     -4:00.6.0 find-and-replace:show (input.hidden-input)
     -3:58.6.0 core:backspace (input.hidden-input)
  3x -3:52.9.0 core:confirm (input.hidden-input)
     -3:19.6.0 intentions:highlight (input.hidden-input)
     -3:19.4.0 find-and-replace:show (input.hidden-input)
  2x -3:13.8.0 core:confirm (input.hidden-input)
     -0:18.1.0 core:move-right (input.hidden-input)
     -0:17.6.0 core:move-down (input.hidden-input)
     -0:17.4.0 core:move-left (input.hidden-input)
     -0:17.3.0 core:move-down (input.hidden-input)
     -0:16.9.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
bottom-dock 0.4.4 
busy-signal 2.0.1 
emmet 2.4.3 
intentions 1.1.5 
linter 2.3.1 
linter-csslint 2.0.6 
linter-htmllint 1.1.5 
linter-js-standard 7.0.0 
linter-ui-default 1.8.0 
pigments 0.40.2 
teletype 0.13.4 
todo-manager 0.2.10 
```

**Comment by aminya** [comment]
Close in favor of the already reported issue: #571
