### ISSUE TITLE
Uncaught TypeError: range.intersectsWith is not a function

### ISSUE THREAD

**Issue by GeminiServer** [steelbrain/linter-ui-default#567]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.2
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.8.1

### Stack Trace

Uncaught TypeError: range.intersectsWith is not a function

```
At /Users/ecolak/.atom/packages/linter-ui-default/lib/helpers.js:102

TypeError: range.intersectsWith is not a function
    at /packages/linter-ui-default/lib/helpers.js:102:53
    at Set.forEach (<anonymous>)
    at filterMessagesByRangeOrPoint (/packages/linter-ui-default/lib/helpers.js:99:12)
    at Editor.updateTooltip (/packages/linter-ui-default/lib/editor/index.js:275:22)
    at /packages/linter-ui-default/lib/editor/index.js:221:18)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -1:37.7.0 core:backspace (input.hidden-input)
     -1:37.5.0 core:move-down (input.hidden-input)
     -1:37.2.0 intentions:highlight (input.hidden-input)
     -1:37.1.0 editor:select-to-end-of-word (input.hidden-input)
     -1:36.8.0 editor:select-to-beginning-of-word (input.hidden-input)
     -1:36.5.0 core:backspace (input.hidden-input)
     -1:36.3.0 core:move-down (input.hidden-input)
     -1:36.2.0 intentions:highlight (input.hidden-input)
     -1:36.1.0 editor:select-to-end-of-word (input.hidden-input)
     -1:35.8.0 editor:select-to-beginning-of-word (input.hidden-input)
  4x -1:35.4.0 core:backspace (input.hidden-input)
     -1:15.3.0 core:move-down (input.hidden-input)
     -0:17.1.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:16.4.0 editor:select-to-end-of-line (input.hidden-input)
  3x -0:15.2.0 core:move-up (input.hidden-input)
  3x -0:14.3.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.12.1 
build 0.70.0 
build-gradle 0.6.0 
busy-signal 2.0.1 
file-icons 2.1.38 
intentions 1.1.5 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc 0.9.0 
linter-gcc2 0.8.8 
linter-ui-default 1.8.1 
platformio-ide 2.6.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
tool-bar 1.2.0 
```

**Comment by aminya** [comment]
Closing in favor of another duplicate issue.  https://github.com/steelbrain/linter-ui-default/issues/576
