### ISSUE TITLE
Uncaught TypeError: range.intersectsWith is not a function

### ISSUE THREAD

**Issue by anonyme22** [steelbrain/linter-ui-default#568]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.8.1

### Stack Trace

Uncaught TypeError: range.intersectsWith is not a function

```
At C:\Users\Me\.atom\packages\linter-ui-default\lib\helpers.js:102

TypeError: range.intersectsWith is not a function
    at /packages/linter-ui-default/lib/helpers.js:102:53
    at Set.forEach (<anonymous>)
    at filterMessagesByRangeOrPoint (/packages/linter-ui-default/lib/helpers.js:99:12)
    at Editor.updateTooltip (/packages/linter-ui-default/lib/editor/index.js:275:22)
    at /packages/linter-ui-default/lib/editor/index.js:221:18)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -1:48.6.0 platformio-ide:target:upload (input.hidden-input)
     -1:48.6.0 platformio-ide:target:upload-C:\Users\Me\Project (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:37.7.0 core:select-right (input.hidden-input)
  5x -1:36.5.0 core:move-right (input.hidden-input)
     -1:34.9.0 core:select-right (input.hidden-input)
  4x -1:34.1.0 core:move-right (input.hidden-input)
  2x -1:32.8.0 core:select-right (input.hidden-input)
 46x -1:31.6.0 core:move-right (input.hidden-input)
     -1:10.5.0 core:move-left (input.hidden-input)
  2x -1:10 core:move-right (input.hidden-input)
  2x -1:04.5.0 core:move-left (input.hidden-input)
     -1:03.4.0 core:move-right (input.hidden-input)
     -1:01.5.0 intentions:highlight (input.hidden-input)
     -1:01.2.0 core:save (input.hidden-input)
     -0:59 platformio-ide:target:upload (input.hidden-input)
     -0:59 platformio-ide:target:upload-C:\Users\Me\Project (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
autocomplete-clang 0.12.1 
build 0.70.0 
build-platformio 1.2.4 
busy-signal 2.0.1 
file-icons 2.1.38 
intentions 1.1.5 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc 0.9.0 
linter-gcc2 0.8.8 
linter-ui-default 1.8.1 
minimap 4.29.9 
minimap-pigments 0.2.2 
pigments 0.40.2 
platformio-aia 0.0.5 
platformio-ide 2.6.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
platomformio 0.7.1 
todo 0.6.0 
tool-bar 1.2.0 
uncrustify-0.70.1_f-win32 undefined 
```

**Comment by carlobrok** [comment]
same for me... It is still not fixed and I don't know what I did that it occurs.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 19.10
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.8.1


### Stack Trace

Uncaught TypeError: range.intersectsWith is not a function

```
At /home/carlo/.atom/packages/linter-ui-default/lib/helpers.js:102

TypeError: range.intersectsWith is not a function
    at /packages/linter-ui-default/lib/helpers.js:102:53
    at Set.forEach (<anonymous>)
    at filterMessagesByRangeOrPoint (/packages/linter-ui-default/lib/helpers.js:99:12)
    at Editor.updateTooltip (/packages/linter-ui-default/lib/editor/index.js:275:22)
    at /packages/linter-ui-default/lib/editor/index.js:235:14
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
  2x -9:05.5.0 core:move-left (input.hidden-input)
     -9:04.6.0 core:move-down (input.hidden-input)
  2x -9:04.5.0 core:move-left (input.hidden-input)
     -9:02.8.0 intentions:highlight (input.hidden-input)
     -9:02.3.0 core:save (input.hidden-input)
  3x -8:45.9.0 core:delete (input.hidden-input)
  2x -8:44.5.0 core:move-up (input.hidden-input)
     -8:42.7.0 core:move-down (input.hidden-input)
     -2:29.9.0 intentions:highlight (input.hidden-input)
     -2:29.6.0 core:copy (input.hidden-input)
     -2:26.9.0 project-find:show-in-current-directory (div.header.list-item)
     -2:26 core:paste (input.hidden-input)
     -0:23.6.0 intentions:highlight (input.hidden-input)
     -0:23.4.0 core:save (input.hidden-input)
     -0:22.6.0 core:move-down (input.hidden-input)
     -0:22.4.0 core:move-up (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-shell-commands 1.5.0 
autocomplete-clang 0.12.1 
build 0.70.0 
file-icons 2.1.35 
intentions 1.1.5 
linter 2.3.1 
linter-gcc 0.9.0 
linter-ui-default 1.8.1 
minimap 4.29.9 
one-dark-vivid-syntax 1.8.1 
script 3.18.1 
seti-syntax 1.2.0 
terminal-plus 0.14.5 
tool-bar 1.1.12 
```

**Comment by aminya** [comment]
Closing in favor of another duplicate issue.  https://github.com/steelbrain/linter-ui-default/issues/576
