### ISSUE TITLE
Uncaught TypeError: Cannot read property 'element' of undefined

### ISSUE THREAD

**Issue by Justany** [steelbrain/linter-ui-default#569]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At C:\Users\Miche Jeanny\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11

TypeError: Cannot read property 'element' of undefined
    at TextEditorComponent.measureLongestLineWidth (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:11:104951)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:11:70947)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:11:68224)
    at TextEditorComponent.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.43.0/resources/app/static/<embedded>:11:66662)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:253:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -2:42.7.0 find-and-replace:show (input.hidden-input)
     -2:39.7.0 core:confirm (input.hidden-input)
  3x -2:28.8.0 core:backspace (input.hidden-input)
     -2:27.3.0 intentions:highlight (input.hidden-input)
     -2:27.1.0 core:save (input.hidden-input)
  3x -1:23.4.0 core:backspace (input.hidden-input)
     -1:07.7.0 intentions:highlight (input.hidden-input)
     -1:07.4.0 core:save (input.hidden-input)
     -0:47.5.0 intentions:highlight (input.hidden-input)
  5x -0:47.3.0 core:undo (input.hidden-input)
  6x -0:26.2.0 intentions:highlight (input.hidden-input)
  2x -0:25.5.0 core:undo (input.hidden-input)
     -0:21.6.0 intentions:highlight (input.hidden-input)
     -0:21.3.0 core:save (input.hidden-input)
     -0:20 intentions:highlight (input.hidden-input)
     -0:19.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.33.4 
atom-clock 0.1.17 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-toolbar 0.1.6 
autocomplete-plus-async 0.22.0 
bootstrap4-quicksnip 0.3.10 
busy-signal 2.0.1 
dart 1.0.1 
dash 1.7.1 
french-menu 1.0.0 
hey-pane 1.2.0 
Hydrogen undefined 
intentions 1.1.5 
language-icon 0.1.1 
linter 2.3.1 
linter-ui-default 1.8.1 
monoid-syntax 0.2.0 
no-file-icons 1.0.0 
tool-bar-expert 0.4.0 
uikit-atom 0.3.2 
zentabs 0.8.9 
```

**Comment by aminya** [comment]
Similar to https://github.com/steelbrain/linter-ui-default/issues/571
