### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by kumichin** [steelbrain/linter-ui-default#571]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At C:\Users\kumik\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:76051)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:75983)
    at TextEditorComponent.renderContent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:74509)
    at TextEditorComponent.renderScrollContainer (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:73969)
    at TextEditorComponent.render (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:72748)
    at Object.updateSync (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:14:132897)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:70606)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:67993)
    at TextEditorComponent.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:66662)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:253:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
color-picker 2.3.0 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
file-icons 2.1.39 
formatter-tidy 1.0.1 
intentions 1.1.5 
language-idyll 0.2.1 
language-tiddlywiki5 0.3.0 
linter 2.3.1 
linter-clang-tidy 0.2.0 
linter-tidy 2.4.0 
linter-ui-default 1.8.1 
masontidy 1.1.0 
open-in-browser 0.5.2 
open-in-browsers 0.0.30 
perltidy 4.0.0 
pigments 0.40.2 
tidal-autocode 0.6.4 
tidy-html5 0.2.1 
tidy-tabs 0.4.0 
vk-terminal 3.0.1 
wp-phptidy 1.1.0 
```

**Comment by psnider30** [comment]
same error on mac Catalina 10.15.3

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:76051)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:75983)
    at TextEditorComponent.renderContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:74509)
    at TextEditorComponent.renderScrollContainer (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:73969)
    at TextEditorComponent.render (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:72748)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:132897)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:70606)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:67993)
    at TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:66662)
    at HTMLElement.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:253:32)
    at getBufferPositionFromMouseEvent (/Users/Paul/.atom/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at HTMLElement.<anonymous> (/Users/Paul/.atom/packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/Users/Paul/.atom/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)

**Comment by aubreyz** [comment]
My atom is continuously filled with this error. Any solution other than to remove linter?

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.8.1


### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At C:\Users\ablum\AppData\Local\atom\app-1.46.0\resources\app\static\<embedded>:11

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:76051)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:75983)
    at TextEditorComponent.renderContent (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:74509)
    at TextEditorComponent.renderScrollContainer (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:73969)
    at TextEditorComponent.render (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:72748)
    at Object.updateSync (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:132897)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:70606)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:67993)
    at TextEditorComponent.pixelPositionForScreenPosition (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:66662)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:253:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
  2x -3:32.6.0 spell-check:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-notes 1.23.0 
atom-wrap-in-tag 0.6.0 
autocomplete-latex 0.9.2 
busy-signal 2.0.1 
comment 0.6.1 
custom-folds 1.9.5 
drag-relative-path 1.2.3 
file-icons 2.1.40 
flex-tool-bar 2.2.0 
fold-lines 0.2.2 
intentions 1.1.5 
language-atom-notes 0.4.1 
language-todotxt 1.1.5 
linter 2.3.1 
linter-tidy 2.4.0 
linter-ui-default 1.8.1 
markdown-preview-plus 3.11.5 
markdown-writer 2.11.10 
open-recent 5.0.0 
pandoc-convert 1.1.1 
pigments 0.40.2 
project-manager 3.3.8 
sort-lines 0.19.0 
sync-settings 4.3.3 
sync-settings-folder-location 1.0.6 
todo-show 2.3.2 
tool-bar 1.3.0 
```

**Comment by aubreyz** [comment]
I have small bit of information which might be relevant and might assist to having this debugged. 

The bombarding of these Linter error messages started immediately after the inbuilt spell check package was updated from 0.75.0 to 0.76.0. The updated spell check package had a problem locating the local dictionary (which had not moved). Immediately following the application of the workaround for the spell-check bug shown here the Linter errors stopped arriving:

https://github.com/atom/spell-check/issues/284#issuecomment-570759212

The timing of the start and end of the linter errors seems unlikely to be coincidental....

**Comment by aminya** [comment]
Does this error happen on the latest version of Atom and liner/linter-ui-default?
