### ISSUE TITLE
Linter-ui-default Uncaught TypeError when using Kite

### ISSUE THREAD

**Issue by gmarwaha** [steelbrain/linter-ui-default#572]
New to python and atom but here's an persistent issue I get on a new installation: 
![image](https://user-images.githubusercontent.com/34516820/79050312-2a988a80-7bf7-11ea-98a7-0fb6319134f1.png)

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'tags' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

TypeError: Cannot read property 'tags' of undefined
    at TextMateHighlightIterator.seek (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:560730)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1189908)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:95309)
    at DisplayLayer.getScreenLine (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:95206)
    at TextEditor.screenLineForScreenRow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:13891)
    at TextEditorComponent.requestHorizontalMeasurement (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:105144)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:70160)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:67993)
    at TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:66662)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:253:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
  2x -2:50 autocomplete-plus:confirm (input.hidden-input)
  3x -2:48.5.0 core:backspace (input.hidden-input)
     -2:47.9.0 snippets:next-tab-stop (input.hidden-input)
     -2:47.9.0 snippets:expand (input.hidden-input)
     -2:47.8.0 editor:indent (input.hidden-input)
 10x -2:47 core:backspace (input.hidden-input)
     -2:36.7.0 core:move-right (input.hidden-input)
     -2:32.9.0 editor:newline (input.hidden-input)
  4x -2:31.2.0 core:backspace (input.hidden-input)
     -2:29.4.0 editor:newline (input.hidden-input)
     -2:25.1.0 autocomplete-plus:confirm (input.hidden-input)
     -2:24.3.0 core:backspace (input.hidden-input)
     -2:23.3.0 snippets:next-tab-stop (input.hidden-input)
     -2:23.3.0 snippets:expand (input.hidden-input)
     -2:23.3.0 editor:indent (input.hidden-input)
  8x -2:22.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.16.0 
busy-signal 2.0.1 
file-icons 2.1.40 
intentions 1.1.5 
kite 0.178.0 
linter 2.3.1 
linter-flake8 2.4.0 
linter-ui-default 1.8.1 
python-autopep8 0.1.3 
script 3.25.0 
```

**Comment by aminya** [comment]
I can't reproduce your error. Does it still happen?

**Comment by aminya** [comment]
@gmarwaha
