### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by cavirgi** [steelbrain/linter-ui-default#574]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:76051)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:75983)
    at TextEditorComponent.renderContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:74509)
    at TextEditorComponent.renderScrollContainer (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:73969)
    at TextEditorComponent.render (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:72748)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:132897)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:70606)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:67993)
    at TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:66662)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:253:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:214:33)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
 12x -9:55.2.0 core:backspace (input.hidden-input)
     -9:03.7.0 command-palette:toggle (a.)
  8x -9:01.2.0 core:backspace (input.hidden-input)
     -8:54.5.0 core:copy (div.package-readme.native-key-bindings)
     -5:19.9.0 core:paste (input.hidden-input)
 22x -5:19.2.0 core:backspace (input.hidden-input)
     -5:11.6.0 command-palette:toggle (input.hidden-input)
     -5:04.9.0 editor:log-cursor-scope (input.hidden-input)
  3x -4:39.6.0 core:backspace (input.hidden-input)
     -4:32.3.0 core:move-right (input.hidden-input)
 10x -3:44.8.0 core:backspace (input.hidden-input)
     -3:40.7.0 linter-spell:show-language-selector (atom-text-editor.editor)
     -3:11.9.0 spell-check:correct-misspelling-1 (span.syntax--text.syntax--tex.syntax--latex)
     -3:07.8.0 core:copy (input.hidden-input)
  7x -1:13.6.0 spell-check:correct-misspelling-0 (span.syntax--text.syntax--tex.syntax--latex)
     -0:05.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-material-ui 2.1.3 
busy-signal 2.0.1 
intentions 1.1.5 
language-fortran 2.1.11 
language-latex 1.2.0 
linter 2.3.1 
linter-spell 0.15.0 
linter-spell-latex 0.11.0 
linter-ui-default 1.8.1 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
script 3.26.0 
vk-terminal 3.0.1 
```

**Comment by aminya** [comment]
Close in favor of the already reported issue: #571
