### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by abcsds** [steelbrain/linter-ui-default#577]
I'm sorry if I cannot provide much information about this, but It started happening out of nowhere when I added some text on a .tex file. It does not stop, and doesn't let me work on the file without throwing a stack trace with every interaction with the editor pane. This error is also sent if i change windows and come back to atom, if I try to scroll down. It happens all the time.

It stopped when I restarted atom. I have not been able to reproduce it. Still, I thought it could be useful to you.

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: "Manjaro Linux"
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /usr/lib/atom/src/text-editor-component.js:698

TypeError: Cannot read property 'id' of undefined
    at /usr/lib/atom/src/text-editor-component.js:698:42
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (/usr/lib/atom/src/text-editor-component.js:694:37)
    at TextEditorComponent.renderContent (/usr/lib/atom/src/text-editor-component.js:622:12)
    at TextEditorComponent.renderScrollContainer (/usr/lib/atom/src/text-editor-component.js:596:12)
    at TextEditorComponent.render (/usr/lib/atom/src/text-editor-component.js:541:14)
    at Object.updateSync (/usr/lib/atom/node_modules/etch/lib/component-helpers.js:107:34)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/usr/lib/atom/src/text-editor-component.js:409:10)
    at TextEditorComponent.updateSync (/usr/lib/atom/src/text-editor-component.js:279:10)
    at TextEditorComponent.pixelPositionForScreenPosition (/usr/lib/atom/src/text-editor-component.js:206:12)
    at HTMLElement.pixelPositionForScreenPosition (/usr/lib/atom/src/text-editor-element.js:253:32)
    at mouseEventNearPosition (/packages/linter-ui-default/lib/editor/helpers.js:27:47)
    at /packages/linter-ui-default/lib/editor/index.js:203:13)
    at later (/packages/linter-ui-default/node_modules/sb-debounce/index.js:9:14)
```

### Commands

```
     -2:25.4.0 core:move-left (input.hidden-input)
     -2:23.3.0 core:move-right (input.hidden-input)
     -2:19.9.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -2:17.9.0 intentions:highlight (input.hidden-input)
  2x -2:11.5.0 core:backspace (input.hidden-input)
     -2:09.9.0 intentions:highlight (input.hidden-input)
     -2:08.1.0 core:save (input.hidden-input)
     -2:07.5.0 intentions:highlight (input.hidden-input)
  2x -2:07.2.0 latex:build (input.hidden-input)
     -1:40.2.0 latex:sync (span.syntax--text.syntax--tex.syntax--latex)
  2x -1:11.3.0 core:backspace (input.hidden-input)
     -1:08.5.0 intentions:highlight (input.hidden-input)
  2x -1:02.4.0 core:backspace (input.hidden-input)
     -1:00.7.0 latex:build (input.hidden-input)
     -0:13.4.0 intentions:highlight (input.hidden-input)
     -0:13.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
autocomplete-bibtex 1.2.10 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
color-picker 2.3.0 
docker 0.8.0 
editor-stats 0.17.0 
file-icons 2.1.41 
git-time-machine 2.1.0 
Hydrogen 2.14.1 
ide-python 1.5.0 
ink 0.12.3 
intentions 1.1.5 
jekyll 2.1.0 
julia-client 0.12.4 
language-csv 1.1.2 
language-docker 1.1.8 
language-julia 0.19.3 
language-latex 1.2.0 
language-liquid 0.7.0 
language-matlab 0.2.1 
language-viml 1.2.1 
latex 0.50.2 
latex-autocomplete 1.1.1 
latex-hyperclick 0.2.0 
latex-plus 0.9.1 
linter 2.3.1 
linter-chktex 1.4.0 
linter-flake8 2.4.0 
linter-julia 0.8.3 
linter-ui-default 1.8.1 
markdown-scroll-sync 2.1.2 
material-syntax 0.6.1 
pdf-view 0.72.0 
pigments 0.40.2 
python-tools 0.6.9 
sdlang 1.0.0 
set-syntax 0.4.0 
sort-lines 0.19.0 
split-diff 1.6.1 
uber-juno 0.3.0 
zotero-picker 2.0.2 
```

**Comment by aminya** [comment]
Close in favor of the already reported issue: #571

Please add more information to that issue, if it happens in the latest version of Atom and linter.
