### ISSUE TITLE
Uncaught TypeError: (0 , _helpers.$file) is not a function

### ISSUE THREAD

**Issue by gavintmyers** [steelbrain/linter-ui-default#593]
[Enter steps to reproduce:]

1. I do have a file named `tree_view.rb` in the project...
2. I was just saving a different file that had no new changes.

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.6
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 2.1.2

### Stack Trace

Uncaught TypeError: (0 , _helpers.$file) is not a function

```
At /Users/gavinmyers/[......]/.atom/packages/linter-ui-default/lib/tree-view/helpers.js:51

TypeError: (0 , _helpers.$file) is not a function
    at /packages/linter-ui-default/lib/tree-view/helpers.js:51:22
    at Array.forEach (<anonymous>)
    at calculateDecorations (/packages/linter-ui-default/lib/tree-view/helpers.js:50:12)
    at TreeView.update (/packages/linter-ui-default/lib/tree-view/index.js:67:27)
    at /packages/linter-ui-default/lib/tree-view/index.js:49:18)
    at invokeFunc (/packages/linter-ui-default/node_modules/lodash/lodash.js:10359:23)
    at trailingEdge (/packages/linter-ui-default/node_modules/lodash/lodash.js:10408:18)
    at timerExpired (/packages/linter-ui-default/node_modules/lodash/lodash.js:10396:18)
```

### Commands

```
  2x -1:27.9.0 core:save (input.hidden-input)
  8x -1:21.7.0 core:close (input.hidden-input)
     -0:34.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-clock 0.1.18 
busy-signal 2.0.1 
intentions 1.1.5 
linter 3.1.1 
linter-rubocop 2.5.7 
linter-ui-default 2.1.2 
```

**Comment by aminya** [comment]
Does reinstalling the package helps?
