### ISSUE TITLE
npm ERR! Unexpected end of JSON input

### ISSUE THREAD

**Issue by black-snow** [steelbrain/linter-ui-default#594]
```
Updating to “linter-ui-default@2.1.2” failed.Hide output…

npm ERR! Unexpected end of JSON input while parsing near '...pmjs.org/lodash/-/lod'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\.atom\.apm\_logs\2020-10-10T11_01_47_494Z-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\xxx\\AppData\\Local\\atom\\app-1.51.0\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\Users\\xxx\\AppData\\Local\\atom\\app-1.51.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Users\\xxx\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Users\\xxx\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/linter-ui-default/versions/2.1.2/tarball',
1 verbose cli   '--target=5.0.13',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style',
1 verbose cli   '--msvs_version=2015' ]
2 info using npm@6.14.5
3 info using node@v10.20.1
4 verbose npm-session 860e50d7aa6969a9
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://codeload.github.com/steelbrain/linter-ui-default/legacy.tar.gz/v2.1.2 1028ms (from cache)
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/linter-ui-default/versions/2.1.2/tarball fetched in 1069ms
9 timing stage:loadCurrentTree Completed in 1108ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule linter-ui-default@2.1.2 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/disposable-event 368ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/lodash 372ms (from cache)
19 silly fetchPackageMetaData error for lodash@^4.17.20 Unexpected end of JSON input while parsing near '...pmjs.org/lodash/-/lod'
20 silly pacote range manifest for disposable-event@^1.0.3 fetched in 379ms
21 silly resolveWithNewModule disposable-event@1.0.3 checking installable status
22 http fetch GET 304 https://registry.npmjs.org/marked 387ms (from cache)
23 silly pacote range manifest for marked@^1.2.0 fetched in 396ms
24 silly resolveWithNewModule marked@1.2.0 checking installable status
25 http fetch GET 304 https://registry.npmjs.org/sb-react-table 392ms (from cache)
26 silly pacote range manifest for sb-react-table@^1.0.2 fetched in 393ms
27 silly resolveWithNewModule sb-react-table@1.0.2 checking installable status
28 http fetch GET 304 https://registry.npmjs.org/react 399ms (from cache)
29 http fetch GET 304 https://registry.npmjs.org/react-dom 406ms (from cache)
30 silly pacote range manifest for react@^16.13.1 fetched in 419ms
31 silly resolveWithNewModule react@16.13.1 checking installable status
32 silly pacote range manifest for react-dom@^16.13.1 fetched in 418ms
33 silly resolveWithNewModule react-dom@16.13.1 checking installable status
34 http fetch GET 304 https://registry.npmjs.org/atom-package-deps 428ms (from cache)
35 silly pacote range manifest for atom-package-deps@^6.0.0 fetched in 433ms
36 silly resolveWithNewModule atom-package-deps@6.0.0 checking installable status
37 timing stage:rollbackFailedOptional Completed in 0ms
38 timing stage:runTopLevelLifecycles Completed in 1562ms
39 silly saveTree apm-install-dir-2020910-13192-f6rdlx.7ullw
39 silly saveTree `-- linter-ui-default@2.1.2
39 silly saveTree   +-- atom-package-deps@6.0.0
39 silly saveTree   +-- disposable-event@1.0.3
39 silly saveTree   +-- marked@1.2.0
39 silly saveTree   +-- react-dom@16.13.1
39 silly saveTree   +-- react@16.13.1
39 silly saveTree   `-- sb-react-table@1.0.2
40 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...pmjs.org/lodash/-/lod'
40 verbose stack     at JSON.parse (<anonymous>)
40 verbose stack     at parseJson (C:\Users\xxx\AppData\Local\atom\app-1.51.0\resources\app\apm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
40 verbose stack     at consumeBody.call.then.buffer (C:\Users\xxx\AppData\Local\atom\app-1.51.0\resources\app\apm\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50)
40 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
41 verbose cwd C:\Users\xxx\AppData\Local\Temp\apm-install-dir-2020910-13192-f6rdlx.7ullw
42 verbose Windows_NT 10.0.19041
43 verbose argv "C:\\Users\\xxx\\AppData\\Local\\atom\\app-1.51.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\xxx\\AppData\\Local\\atom\\app-1.51.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\xxx\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\xxx\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/linter-ui-default/versions/2.1.2/tarball" "--target=5.0.13" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style" "--msvs_version=2015"
44 verbose node v10.20.1
45 verbose npm  v6.14.5
46 error Unexpected end of JSON input while parsing near '...pmjs.org/lodash/-/lod'
47 verbose exit [ 1, true ]
```

latest stable atom

**Comment by aminya** [comment]
Is this a downloading issue? What are the steps to reproduce this?

**Comment by black-snow** [comment]
I don't know. 2.1.2 won't install. Since the upgrade failed I uninstalled it and now I cannot install it again.

**Comment by black-snow** [comment]
lodash entry looks okay (package-lock)
```json
    "lodash": {
      "version": "4.17.20",
      "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.20.tgz",
      "integrity": "sha512-PlhdFcillOINfeV7Ni6oF1TAEayyZBoZ8bcshTHqOYJYlrqzRK5hagpagky5o4HfCzzd1TRkXPMFq6cKk9rGmA=="
    },
```

**Comment by black-snow** [comment]
previous version failed, too but this worked

```
$ apm i linter-ui-default@2.0.1
Installing linter-ui-default@2.0.1 to C:\Users\m02ph\.atom\packages done
```

**Comment by aminya** [comment]
I can't reproduce this. Try deleting `.atom/packages/linter-ui-default` and install the package again.

**Comment by vrinch** [comment]
I am having same issue
no other version works after failing to install properly

**Comment by aminya** [comment]
@vrinch Could you try the latest version?

**Comment by vrinch** [comment]
@aminya still the same thing

**Comment by aminya** [comment]
@vrinch Please uninstall the package.

Go to the download page and install it again from scratch: https://atom.io/packages/linter-ui-default

**Comment by TechieAndroid** [comment]
Okay I'm having the same problem too, here's what happened.

1. I tried to update linter-ui-default.
2. It failed to update.
3. Uninstalled it.
4. Reinstalled it. (but it's hanging up on the dependency now)

![image](https://user-images.githubusercontent.com/17918163/97369228-7e5c7f80-187a-11eb-91f3-07b890c3e061.png)

**Comment by TechieAndroid** [comment]
Running `apm install linter-ui-default` outputs this error.

```
Installing linter-ui-default to /home/austin/.atom/packages ✗

npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning undefined: premature close
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/react-is: Integrity verification failed for sha512-lElkOgBNZtEozET5gsNwK3P0UuA0I+88uNcASj2qV2k5qrDWHF1rr2DI/L8kgV8tmoRdJTwPtoY+Cc+yvVX2+A== (/home/austin/.atom/.apm/_cacache/content-v2/sha512/94/49/643a004d66d128cc44f982c3702b73f452e03423ef3cb8d7004a3daa576939aab0d61c5d6baf60c8fcbf24815f2d9a845d253c0fb6863e09cfb2bd55f6f8)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/austin/.atom/.apm/_logs/2020-10-27T22_38_02_558Z-debug.log
```

**Comment by steelbrain** [comment]
I have experienced similar issues in the past, almost always have been because of ISPs meddling or corporate firewalls

**Comment by aminya** [comment]
I am adding package-lock again and updating the dependencies to the latest. Hopefully, this will fix the issue.

**Comment by TechieAndroid** [comment]
Do I need to clear any cache out before reinstalling it? I just quit Atom and started it back up and tried a fresh install and it still gives me this:
![image](https://user-images.githubusercontent.com/17918163/97374643-c1bceb00-1886-11eb-96f9-dab179b381a1.png)

**Comment by aminya** [comment]
You can try to remove cache and temp. If you really want to clean all the Atom cache you should remove these folders:
```
C:\Users\yourname\.atom\.node-gyp
C:\Users\yourname\.atom\storage
C:\Users\yourname\.atom\.apm
C:\Users\yourname\.atom\.npm
C:\Users\yourname\.atom\compile-cache
C:\Users\yourname\.atom\snapshot-cache
C:\Users\yourname\.atom\atom-shell
C:\Users\yourname\.atom\electron
C:\Users\yourname\AppData\Local\Temp\atom-build
C:\Users\yourname\AppData\Local\Temp\atom-cached-atom-shells
```

**Comment by aminya** [comment]
> ![image](https://user-images.githubusercontent.com/17918163/97374643-c1bceb00-1886-11eb-96f9-dab179b381a1.png)

@TechieAndroid There is a log folder given in this image. Could you upload that?

**Comment by TechieAndroid** [comment]
[2020-10-27T23_58_34_482Z-debug.log](https://github.com/steelbrain/linter-ui-default/files/5448788/2020-10-27T23_58_34_482Z-debug.log)

**Comment by aminya** [comment]
> [2020-10-27T23_58_34_482Z-debug.log](https://github.com/steelbrain/linter-ui-default/files/5448788/2020-10-27T23_58_34_482Z-debug.log)

This log seems like a connection issue which is different from the error message of this original issue.

Could you try running this:
```
npm cache verify
npm cache clean -force
npm i
```


Doing some searches show that this has happened with npm before:
https://github.com/npm/cli/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+npm+ERR%21+Unexpected+end+of+JSON+input

<details>
<summary>log</summary>



```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/home/austin/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/home/austin/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/linter-ui-default/versions/2.1.4/tarball',
1 verbose cli   '--target=6.1.12',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v15.0.1
4 verbose npm-session 656b873c7fcef141
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://codeload.github.com/steelbrain/linter-ui-default/legacy.tar.gz/v2.1.4 546ms (from cache)
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/linter-ui-default/versions/2.1.4/tarball fetched in 560ms
9 timing stage:loadCurrentTree Completed in 578ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule linter-ui-default@2.1.4 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/react 35ms (from cache)
18 silly pacote range manifest for react@^17.0.1 fetched in 40ms
19 silly resolveWithNewModule react@17.0.1 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/atom-package-deps 142ms (from cache)
21 silly pacote range manifest for atom-package-deps@^6.0.0 fetched in 152ms
22 silly resolveWithNewModule atom-package-deps@6.0.0 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/marked 152ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/sb-react-table 152ms (from cache)
25 silly pacote range manifest for marked@^1.2.2 fetched in 160ms
26 silly resolveWithNewModule marked@1.2.2 checking installable status
27 silly pacote range manifest for sb-react-table@^1.0.2 fetched in 157ms
28 silly resolveWithNewModule sb-react-table@1.0.2 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/lodash 164ms (from cache)
30 silly pacote range manifest for lodash@^4.17.20 fetched in 166ms
31 silly resolveWithNewModule lodash@4.17.20 checking installable status
32 http fetch GET 304 https://registry.npmjs.org/disposable-event 168ms (from cache)
33 http fetch GET 304 https://registry.npmjs.org/react-dom 164ms (from cache)
34 silly pacote range manifest for disposable-event@^1.0.3 fetched in 173ms
35 silly resolveWithNewModule disposable-event@1.0.3 checking installable status
36 silly pacote range manifest for react-dom@^17.0.1 fetched in 168ms
37 silly resolveWithNewModule react-dom@17.0.1 checking installable status
38 http fetch GET 304 https://registry.npmjs.org/semver 44ms (from cache)
39 silly pacote range manifest for semver@^7.3.2 fetched in 46ms
40 silly resolveWithNewModule semver@7.3.2 checking installable status
41 http fetch GET 304 https://registry.npmjs.org/sb-fs 47ms (from cache)
42 silly pacote range manifest for sb-fs@^4.0.0 fetched in 52ms
43 silly resolveWithNewModule sb-fs@4.0.0 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/strip-bom-buf 63ms (from cache)
45 silly pacote range manifest for strip-bom-buf@^1.0.0 fetched in 65ms
46 silly resolveWithNewModule strip-bom-buf@1.0.0 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/is-utf8 41ms (from cache)
48 silly pacote range manifest for is-utf8@^0.2.1 fetched in 42ms
49 silly resolveWithNewModule is-utf8@0.2.1 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/sb-event-kit 39ms (from cache)
51 silly pacote range manifest for sb-event-kit@^2.0.0 fetched in 41ms
52 silly resolveWithNewModule sb-event-kit@2.0.0 checking installable status
53 http fetch GET 304 https://registry.npmjs.org/object-assign 52ms (from cache)
54 http fetch GET 304 https://registry.npmjs.org/loose-envify 54ms (from cache)
55 silly pacote range manifest for object-assign@^4.1.1 fetched in 55ms
56 silly resolveWithNewModule object-assign@4.1.1 checking installable status
57 silly pacote range manifest for loose-envify@^1.1.0 fetched in 56ms
58 silly resolveWithNewModule loose-envify@1.4.0 checking installable status
59 http fetch GET 304 https://registry.npmjs.org/js-tokens 35ms (from cache)
60 silly pacote range manifest for js-tokens@^3.0.0 || ^4.0.0 fetched in 37ms
61 silly resolveWithNewModule js-tokens@4.0.0 checking installable status
62 warn registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning undefined: premature close
63 warn registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
64 silly fetchPackageMetaData error for scheduler@^0.20.1 Invalid response body while trying to fetch https://registry.npmjs.org/scheduler: Integrity verification failed for sha512-hW/3FRm5k0EdIj7927hZDAsprxVWSlBapASVfB0xG041hUqKoW4qwMwhNC8NK7vxqFH4lVfZtLI9GxhDt8S8vQ== (/home/austin/.atom/.apm/_cacache/content-v2/sha512/85/6f/f71519b993411d223efddbb8590c0b29af15564a505aa404957c1d311b4e35854a8aa16e2ac0cc21342f0d2bbbf1a851f89557d9b4b23d1b1843b7c4bcbd)
65 timing stage:rollbackFailedOptional Completed in 0ms
66 timing stage:runTopLevelLifecycles Completed in 1117ms
67 silly saveTree apm-install-dir-2020927-23609-1ir8n0y.m6a8h
67 silly saveTree └─┬ linter-ui-default@2.1.4
67 silly saveTree   ├─┬ atom-package-deps@6.0.0
67 silly saveTree   │ ├─┬ sb-fs@4.0.0
67 silly saveTree   │ │ └─┬ strip-bom-buf@1.0.0
67 silly saveTree   │ │   └── is-utf8@0.2.1
67 silly saveTree   │ └── semver@7.3.2
67 silly saveTree   ├─┬ disposable-event@1.0.3
67 silly saveTree   │ └── sb-event-kit@2.0.0
67 silly saveTree   ├── lodash@4.17.20
67 silly saveTree   ├── marked@1.2.2
67 silly saveTree   ├─┬ react-dom@17.0.1
67 silly saveTree   │ ├─┬ loose-envify@1.4.0
67 silly saveTree   │ │ └── js-tokens@4.0.0
67 silly saveTree   │ └── object-assign@4.1.1
67 silly saveTree   ├── react@17.0.1
67 silly saveTree   └── sb-react-table@1.0.2
68 verbose type system
69 verbose stack FetchError: Invalid response body while trying to fetch https://registry.npmjs.org/scheduler: Integrity verification failed for sha512-hW/3FRm5k0EdIj7927hZDAsprxVWSlBapASVfB0xG041hUqKoW4qwMwhNC8NK7vxqFH4lVfZtLI9GxhDt8S8vQ== (/home/austin/.atom/.apm/_cacache/content-v2/sha512/85/6f/f71519b993411d223efddbb8590c0b29af15564a505aa404957c1d311b4e35854a8aa16e2ac0cc21342f0d2bbbf1a851f89557d9b4b23d1b1843b7c4bcbd)
69 verbose stack     at Readable.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:195:14)
69 verbose stack     at Readable.emit (node:events:327:20)
69 verbose stack     at /usr/lib/node_modules/npm/node_modules/make-fetch-happen/cache.js:92:30
69 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
69 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
69 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
69 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
69 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:695:18)
69 verbose stack     at _drainQueueStep (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
69 verbose stack     at _drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
69 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
69 verbose stack     at Immediate.Async.drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
69 verbose stack     at processImmediate (node:internal/timers:462:21)
70 verbose cwd /tmp/apm-install-dir-2020927-23609-1ir8n0y.m6a8h
71 verbose Linux 5.9.1-zen2-1-zen
72 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/austin/.atom/.apm/.apmrc" "--userconfig" "/home/austin/.atom/.apmrc" "install" "https://www.atom.io/api/packages/linter-ui-default/versions/2.1.4/tarball" "--target=6.1.12" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
73 verbose node v15.0.1
74 verbose npm  v6.14.8
75 error code EINTEGRITY
76 error errno EINTEGRITY
77 error Invalid response body while trying to fetch https://registry.npmjs.org/scheduler: Integrity verification failed for sha512-hW/3FRm5k0EdIj7927hZDAsprxVWSlBapASVfB0xG041hUqKoW4qwMwhNC8NK7vxqFH4lVfZtLI9GxhDt8S8vQ== (/home/austin/.atom/.apm/_cacache/content-v2/sha512/85/6f/f71519b993411d223efddbb8590c0b29af15564a505aa404957c1d311b4e35854a8aa16e2ac0cc21342f0d2bbbf1a851f89557d9b4b23d1b1843b7c4bcbd)
78 verbose exit [ 1, true ]

```

</details>

**Comment by TechieAndroid** [comment]
> This log seems like a connection issue which is different from the error message of this original issue.
> 
> Could you try running this:
> 
> ```
> npm cache verify
> npm cache clean -force
> apm install linter-ui-default
> ```
> 
> Doing some searches show that this has happened with npm before. [1](https://github.com/npm/cli/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+npm+ERR%21+Unexpected+end+of+JSON+input), [2](https://github.com/npm/cli/issues?q=is%3Aissue+sort%3Aupdated-desc+Invalid+response+body+while+trying+is%3Aclosed)

Ah okay sorry then, I didn't mean to hijack this issue.

I did want to mention though, that I followed your instructions and deleted those directories and then rebooted and tried reinstalling and it worked. Thank you for helping me out!

**Comment by aminya** [comment]
> I did want to mention though, that I followed your instructions and deleted those directories and then rebooted and tried reinstalling and it worked. Thank you for helping me out!

You're welcome

**Comment by vrinch** [comment]
has anyone been able to resolve this issue?

**Comment by aminya** [comment]
@vrinch Did you try this?: https://github.com/steelbrain/linter-ui-default/issues/594#issuecomment-717616701

**Comment by vrinch** [comment]
@aminya I did, it just worked 
thanks

**Comment by black-snow** [comment]
Aight, I'll close this then.
