### ISSUE TITLE
Uncaught TypeError: _sbEventKit.Disposable is not a constructor

### ISSUE THREAD

**Issue by Sketnext** [steelbrain/linter-ui-default#595]
[Enter steps to reproduce:]

1. install linter 3.1.1
2. install linter-php 1.6.1
3. install linter-ui-default 2.1.2

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Win10
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 2.1.2

### Stack Trace

Uncaught TypeError: _sbEventKit.Disposable is not a constructor

```
At C:\Users\Abel\.atom\packages\linter-ui-default\node_modules\disposable-event\lib\index.js:15

TypeError: _sbEventKit.Disposable is not a constructor
    at disposableEvent (/packages/linter-ui-default/node_modules/disposable-event/lib/index.js:15:10)
    at Editor.listenForMouseMovement (/packages/linter-ui-default/lib/editor/index.js:203:12)
    at /packages/linter-ui-default/lib/editor/index.js:94:40
    at Config.observeKeyPath (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:334918)
    at Config.observe (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:329400)
    at /packages/linter-ui-default/lib/editor/index.js:87:19)
    at Editors.getEditor (/packages/linter-ui-default/lib/editors.js:76:20)
    at /packages/linter-ui-default/lib/editors.js:23:14
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:428905)
    at /packages/linter-ui-default/lib/editors.js:22:22)
    at /packages/linter-ui-default/lib/main.js:59:30
    at Config.observeKeyPath (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:334918)
    at Config.observe (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:329400)
    at LinterUI.observeShowDecorations (/packages/linter-ui-default/lib/main.js:57:23)
```

### Commands

```
```

### Non-Core Packages

```
atom-discord 2.0.2 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
console-command-runner 1.1.0 
linter 3.1.1 
linter-php 1.6.1 
linter-ui-default 2.1.2 
teletype 0.13.4 
```

**Comment by aminya** [comment]
Could you provide reproduction steps?

**Comment by Sketnext** [comment]
I have already solved the problem, it happens that when I am editing a php code it skips that error and does not point out the problems in the code.

The problem is that the php PATH is not configured in the environment variables in windows.

ES: [Tutorial para solucionar](https://www.netveloper.com/php-variable-de-entorno-en-windows)
EN: [Tutorial to fix](https://www.forevolve.com/en/articles/2016/10/27/how-to-add-your-php-runtime-directory-to-your-windows-10-path-environment-variable/)
