### ISSUE TITLE
Uncaught ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by wiccawill420** [steelbrain/linter-ui-default#617]
[Enter steps to reproduce:]

1. writing php script with error
```
#!/usr/bin/php 
<?php
	printf("\nWhat's up\n")

```
2. linter runs with linter-php, throws exception
linter-php is version 1.6.1 (latest)
linter-ui-default appears to work correctly with linter-shellcheck.

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.5
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 2.5.2

### Stack Trace

Uncaught ReferenceError: globalThis is not defined

```
At /home/william/.atom/packages/linter-ui-default/dist/index.js:1

ReferenceError: globalThis is not defined
    at /packages/linter-ui-default/dist/index.js:1:7989
    at Se (/packages/linter-ui-default/dist/index.js:1:8142)
    at oi (/packages/linter-ui-default/dist/index.js:1:44368)
    at _e (/packages/linter-ui-default/dist/index.js:1:15274)
    at _e (/packages/linter-ui-default/dist/index.js:1:7948)
    at st (/packages/linter-ui-default/dist/index.js:1:15266)
    at Qn.e.forEach.e (/packages/linter-ui-default/dist/index.js:1:83011)
    at Array.forEach (<anonymous>)
    at /packages/linter-ui-default/dist/index.js:1:82976)
    at mn.updateTooltip (/packages/linter-ui-default/dist/index.js:1:89363)
    at textEditor.onDidChangeCursorPosition (/packages/linter-ui-default/dist/index.js:1:88651)
    at /packages/linter-ui-default/dist/index.js:1:41580)
    at /packages/linter-ui-default/dist/index.js:1:41857)
    at /packages/linter-ui-default/dist/index.js:1:41746)
```

### Commands

```
```

### Non-Core Packages

```
atom-overtype-mode 0.4.0 
busy-signal 2.0.1 
docblockr 0.13.7 
intentions 1.1.5 
language-icinga2 0.4.1 
language-rockstar 0.3.1 
linter 3.3.0 
linter-icinga-validate 1.1.1 
linter-perl 0.9.0 
linter-perlcritic 2.3.1 
linter-php 1.6.1 
linter-python 3.1.2 
linter-shellcheck 1.6.0 
linter-ui-default 2.5.2 
minimap 4.39.6 
minimap-linter 2.2.2 
multi-cursor 3.0.0 
platformio-ide-terminal 2.10.1 
scroll-through-time 0.3.1 
sort-lines 0.19.0 
Sublime-Style-Column-Selection 1.7.5 
teletype 0.13.4 
vim-mode-plus 1.34.0 
```

**Comment by aminya** [comment]
Thanks for the report. I will investigate this.

**Comment by aminya** [comment]
@wiccawill420 Could you install a dev version and see if the error is still present?

```
apm uninstall linter-ui-default
git clone https://github.com/steelbrain/linter-ui-default/
cd linter-ui-default
npm install
npm run tsc.build
apm link .
atom .
```

and do your bug reproduction

**Comment by mahruskh** [comment]
Hi @aminya 

> @wiccawill420 Could you install a dev version and see if the error is still present?

Sorry, i got the same issue. I have tried the steps above, it's done when build but found 4 errors below.
I continued with the next step: `apm link .`, but the error ui in atom still present. Thanks.

I use python, and example to produce error:
```
def testing_flake_ui():
    return value
```


Error when build `npm run tsc.build`:
```
mahruskh@kh:~/Downloads/linter-ui-default$ npm run tsc.build

> linter-ui-default@3.0.0 tsc.build /home/mahruskh/Downloads/linter-ui-default
> npm run clean && cross-env NODE_ENV=production tsc -p lib/tsconfig.json || echo done && npm run babel


> linter-ui-default@3.0.0 clean /home/mahruskh/Downloads/linter-ui-default
> shx rm -rf dist .parcel-cache

lib/editor/index.ts:312:46 - error TS2339: Property 'previousEventState' does not exist on type 'Marker'.

312           message.location.position = marker.previousEventState.range
                                                 ~~~~~~~~~~~~~~~~~~

lib/editor/index.ts:324:38 - error TS2345: Argument of type 'DisplayMarker | Marker' is not assignable to parameter of type 'DisplayMarker'.
  Type 'Marker' is missing the following properties from type 'DisplayMarker': getProperties, setProperties, matchesProperties, getBufferRange, and 15 more.

324       this.textEditor.decorateMarker(marker, {
                                         ~~~~~~

lib/editor/index.ts:334:29 - error TS2345: Argument of type 'DisplayMarker | Marker' is not assignable to parameter of type 'DisplayMarker'.
  Type 'Marker' is not assignable to type 'DisplayMarker'.

334       gutter.decorateMarker(marker, {
                                ~~~~~~

lib/tooltip/delegate.ts:33:22 - error TS2339: Property 'originalEvent' does not exist on type 'CommandEvent<EventTarget>'.

33           if (event?.originalEvent?.isTrusted) {
                        ~~~~~~~~~~~~~
Found 4 errors.
done
```

**Comment by aminya** [comment]
Try the new official version. This issue is caused by the build tool that I used. I have disabled it temporarily.

```
apm uninstall linter-ui-default
apm install linter-ui-default
```

**Comment by aminya** [comment]
Sorry, I had to revert 3.0.1. The linter panel was not working correctly. Let me know if the error is still present in the latest version.

**Comment by mahruskh** [comment]
In my machine, the error still present in the last version (`3.0.2`). Maybe need to test by @wiccawill420.

I try to install for with specific version, start from `3.0.2`, until  `3.5.0` and still got error.
But install version: **`2.4.1`** and it works. I will update to latest version if all done.

```
apm install linter-ui-default@2.4.1
```

**Comment by wiccawill420** [comment]
As there was further chat on the issue, I started with uninstalling and re-installing the new official version. It looks like it is still happening. I also tried linter-ui-default 3.0.1 as noted above and still the same. 
As far as when it crashes, it seems to occur when I either move my cursor or mouse to where the error, as if it's trying to generate the popup with the linter suggestion. I can type normally with an error on screen with no issues, but as soon as I try to see what the error is about is when linter-ui-default indicates crash. Please let me know what else I can provide

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.5
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 3.0.2


### Stack Trace

Uncaught ReferenceError: globalThis is not defined

```
At /home/william/.atom/packages/linter-ui-default/dist/index.js:1

ReferenceError: globalThis is not defined
    at /packages/linter-ui-default/dist/index.js:1:7987
    at xe (/packages/linter-ui-default/dist/index.js:1:8103)
    at oi (/packages/linter-ui-default/dist/index.js:1:44370)
    at ye (/packages/linter-ui-default/dist/index.js:1:16000)
    at ye (/packages/linter-ui-default/dist/index.js:1:7946)
    at et (/packages/linter-ui-default/dist/index.js:1:15992)
    at Xn.e.forEach.e (/packages/linter-ui-default/dist/index.js:1:82713)
    at Array.forEach (<anonymous>)
    at /packages/linter-ui-default/dist/index.js:1:82678)
    at bn.updateTooltip (/packages/linter-ui-default/dist/index.js:1:89175)
    at HTMLElement.t (/packages/linter-ui-default/dist/index.js:1:88239)
    at /packages/linter-ui-default/dist/index.js:1:41533)
    at /packages/linter-ui-default/dist/index.js:1:41810)
    at /packages/linter-ui-default/dist/index.js:1:41699)
```

### Commands

```
     -2:01.7.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui.teletype-Authenticated)
     -1:28.8.0 core:backspace (input.hidden-input)
     -0:12.2.0 editor:delete-to-beginning-of-word (input.hidden-input)
```

### Non-Core Packages

```
atom-overtype-mode 0.4.0 
busy-signal 2.0.1 
docblockr 0.13.7 
intentions 1.1.5 
language-icinga2 0.4.1 
language-rockstar 0.3.1 
linter 3.3.0 
linter-icinga-validate 1.1.1 
linter-perl 0.9.0 
linter-perlcritic 2.3.1 
linter-php 1.6.1 
linter-python 3.1.2 
linter-shellcheck 1.6.0 
linter-ui-default 3.0.2 
minimap 4.39.6 
minimap-linter 2.2.2 
multi-cursor 3.0.0 
platformio-ide-terminal 2.10.1 
scroll-through-time 0.3.1 
sort-lines 0.19.0 
Sublime-Style-Column-Selection 1.7.5 
teletype 0.13.4 
vim-mode-plus 1.34.0 
```

**Comment by wiccawill420** [comment]
And I have confirmed what @mahruskh said applies to my situation as well, installing linter-ui-default version 2.4.1 does seem to work.

**Comment by aminya** [comment]
I have found the issue. I think it is because solid-js uses `globalThis` somewhere in the code.
https://github.com/ryansolid/solid/search?q=globalThis

We are tracking the issue in:
https://github.com/parcel-bundler/parcel/issues/5746

**Comment by aminya** [comment]
@wiccawill420 @mahruskh I noticed you are using an old Atom version (old Node 10). You should upgrade to the latest Atom!

This is because globalThis is not defined in Node 10.

**Comment by aminya** [comment]
A workaround added in #618, but please download Atom to the latest version that is only downloadable from the official website:

https://atom.io/

**Comment by wiccawill420** [comment]
Updating atom from deb downloaded directly from site and updating linter-ui-default to latest is working properly. Thank you so much!!

**Comment by formula1** [comment]
This error is still happening to me except its on a javascript file
```
ReferenceError: globalThis is not defined
    at /home/sam/.atom/packages/linter-ui-default/dist/index.js:1:7987
    at xe (/home/sam/.atom/packages/linter-ui-default/dist/index.js:1:8103)
    at oi (/home/sam/.atom/packages/linter-ui-default/dist/index.js:1:44370)
    at ye (/home/sam/.atom/packages/linter-ui-default/dist/index.js:1:16000)
    at ye (/home/sam/.atom/packages/linter-ui-default/dist/index.js:1:7946)
    at et (/home/sam/.atom/packages/linter-ui-default/dist/index.js:1:15992)
    at Xn.e.forEach.e (/home/sam/.atom/packages/linter-ui-default/dist/index.js:1:82713)
    at Array.forEach (<anonymous>)
    at new Xn (/home/sam/.atom/packages/linter-ui-default/dist/index.js:1:82678)
    at bn.updateTooltip (/home/sam/.atom/packages/linter-ui-default/dist/index.js:1:89175)
    at textEditor.onDidChangeCursorPosition (/home/sam/.atom/packages/linter-ui-default/dist/index.js:1:88463)
    at p (/home/sam/.atom/packages/linter-ui-default/dist/index.js:1:41533)
    at v (/home/sam/.atom/packages/linter-ui-default/dist/index.js:1:41810)
    at m (/home/sam/.atom/packages/linter-ui-default/dist/index.js:1:41699)
```

**Comment by festinalente** [comment]
@formula1 I had that exact same error message before updating atom from 1.45 to 1.60, I'd double check you're running the latest version.
