### ISSUE TITLE
Uncaught Error: ENOENT, node_modules\typescript\lib\lib.d.ts not found in C:\Users\User\AppData\Local\atom\app-1.54.0\resources\app.asar

### ISSUE THREAD

**Issue by thexeos** [steelbrain/linter-ui-default#635]
Trying to edit test/index.ts file immediately after cloning https://github.com/chriswells0/node-typescript-template results in this error in Atom:

![image](https://user-images.githubusercontent.com/2260539/110011262-1f6eb180-7d17-11eb-9485-1cb6e84631f7.png)

The error says "2.1.4 installed; 3.2.5 latest", however looking at Atom packages, it has the latest version installed. No updates are available either.

![image](https://user-images.githubusercontent.com/2260539/110011068-ec2c2280-7d16-11eb-9377-9f518acfd7b4.png)

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 2.1.4

### Stack Trace

Uncaught Error: ENOENT, node_modules\typescript\lib\lib.d.ts not found in C:\Users\User\AppData\Local\atom\app-1.54.0\resources\app.asar

```
At electron/js2c/asar.js:586

Error: ENOENT, node_modules\typescript\lib\lib.d.ts not found in C:\Users\User\AppData\Local\atom\app-1.54.0\resources\app.asar
    at createError (electron/js2c/asar.js:109:17)
    at Object.fs.readFileSync (electron/js2c/asar.js:586:24)
    at TypeScriptSimple.createService (/app.asar/node_modules/typescript-simple/index.js:79:61)
    at TypeScriptSimple.compile (/app.asar/node_modules/typescript-simple/index.js:63:37)
    at Object.e.compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:579724)
    at Object.compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:575502)
    at compileFileAtPath (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:148520)
    at Object.value [as .ts] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150918)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at LinterUI.render (/packages/linter-ui-default/lib/main.js:100:22)
    at /packages/linter/dist/index.js:1:8497
    at Set.forEach (<anonymous>)
    at Ct.render (/packages/linter/dist/index.js:1:8474)
    at /packages/linter/dist/index.js:1:29397
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1191622)
    at Zt.update (/packages/linter/dist/index.js:1:16125)
    at /packages/linter/dist/index.js:1:14337)
    at /packages/linter/dist/index.js:1:14393)
    at /packages/linter/dist/index.js:1:14715)
    at Zt.set (/packages/linter/dist/index.js:1:15640)
    at /packages/linter/dist/index.js:1:29149
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1191622)
    at /packages/linter/dist/index.js:1:13267
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1191622)
```

### Commands

```
  2x -9:41.3.0 core:save (input.hidden-input)
     -6:57.3.0 editor:toggle-line-comments (input.hidden-input)
     -6:43.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-blackboard-bb-syntax.theme-atom-dark-ui.find-visible)
     -1:34 editor:toggle-line-comments (input.hidden-input)
     -0:49.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-blackboard-bb-syntax.theme-atom-dark-ui.find-visible)
     -0:15.4.0 core:save (input.hidden-input)
     -0:08.7.0 core:delete (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-debug-ui 1.0.4 
atom-ide-ui 0.13.0 
atom-typescript 14.0.2 
auto-detect-indentation 1.3.0 
autocomplete-php 0.3.7 
blackboard-bb-syntax 0.4.1 
busy-signal 2.0.1 
dark-blackboard-syntax 0.2.0 
duplicate-line-or-selection 0.9.0 
file-watcher 2.0.0 
highlight-selected 0.17.0 
ide-php 0.7.18 
indent-detective 0.4.0 
intentions 1.1.5 
language-json5 1.1.1 
language-latex 1.2.0 
language-tex 0.4.0 
language-vue 0.26.0 
linter 3.1.1 
linter-js-standard 7.0.0 
linter-spell 0.15.0 
linter-spell-latex 0.11.0 
linter-ui-default 2.1.4 
php-debug 0.3.5 
stacked-tabs 0.1.3 
standard-formatter 2.8.0 
wordcount 3.2.0 
```

**Comment by thexeos** [comment]
Fixed with `npm ci`, followed by restarting of Atom.
