### ISSUE TITLE
Uncaught TypeError: Cannot read property 'specMode' of undefined

### ISSUE THREAD

**Issue by LeekJones** [steelbrain/linter-ui-default#653]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: "Manjaro Linux"
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 3.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'specMode' of undefined

```
At /usr/lib/atom/src/atom-environment.js:546

TypeError: Cannot read property 'specMode' of undefined
    at inSpecMode (/usr/lib/atom/src/atom-environment.js:546:14)
    at /packages/linter-ui-default/dist/index.js:1:20622
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-base 3.1.0 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.1 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 2.3.4 
atom-ide-signature-help 0.16.0 
busy-signal 2.0.1 
ide-python 1.9.3 
intentions 2.1.1 
linter 3.4.0 
linter-ui-default 3.4.0 
metro-syntax 0.3.1 
metro-ui 2.2.2 
```

**Comment by aminya** [comment]
Fixed in 3.4.1
