### ISSUE TITLE
Uncaught TypeError: Error processing argument at index 0, conversion failure from null

### ISSUE THREAD

**Issue by mjwhiting21** [steelbrain/linter-ui-default#657]
[Enter steps to reproduce:]

1. click the link on the "Style/ConditionalAssignment: Use the return of the conditional for variable assignment and comparison." helper thing from rubocop
2. error pops up

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 3.4.1

### Stack Trace

Uncaught TypeError: Error processing argument at index 0, conversion failure from null

```
At C:\Users\mjwhi\.atom\packages\linter-ui-default\dist\index.js:1

TypeError: Error processing argument at index 0, conversion failure from null
    at /packages/linter-ui-default/dist/index.js:1:1264)
    at /packages/linter-ui-default/dist/index.js:1:18348
    at /packages/linter-ui-default/dist/index.js:1:2522
```

### Commands

```
     -2:28 core:move-up (input.hidden-input)
     -2:26.8.0 snippets:next-tab-stop (input.hidden-input)
     -2:26.8.0 snippets:expand (input.hidden-input)
     -2:26.8.0 editor:indent (input.hidden-input)
  4x -1:39.6.0 intentions:highlight (input.hidden-input)
     -1:39 core:paste (input.hidden-input)
     -1:32.9.0 intentions:highlight (input.hidden-input)
     -1:32.6.0 editor:toggle-line-comments (input.hidden-input)
     -1:27.5.0 intentions:highlight (input.hidden-input)
     -1:27.1.0 editor:toggle-line-comments (input.hidden-input)
     -1:20.8.0 intentions:highlight (input.hidden-input)
     -1:20.6.0 core:save (input.hidden-input)
  5x -0:57.4.0 core:backspace (input.hidden-input)
     -0:53.3.0 core:delete (input.hidden-input)
     -0:51.8.0 core:backspace (input.hidden-input)
     -0:43.5.0 core:delete (input.hidden-input)
```

### Non-Core Packages

```
aligner 1.3.0 
aligner-javascript 1.3.0 
aligner-ruby 1.8.0 
atom-beautify 0.33.4 
atom-browser 2.1.0 
atom-handlebars 1.3.0 
atom-open-this 0.3.0 
atom-save-all 0.4.1 
atom-tag-wrapper 0.2.0 
atomic-management 0.4.0 
busy-signal 2.0.1 
drag-relative-path 1.2.3 
file-types 1.0.1 
intentions 2.1.1 
linter 3.4.0 
linter-handlebars 2.5.0 
linter-jshint 3.1.19 
linter-rubocop 2.5.7 
linter-ruby 1.3.1 
linter-sass-lint 1.9.0 
linter-ui-default 3.4.1 
minimap 4.40.0 
minimap-titles 1.15.0 
pigments 0.40.6 
smart-html-tags 1.2.5 
teletype 0.13.4 
termination 0.7.6 
```

**Comment by ohboyd** [comment]
I'm also experiencing this, when I try to open a rubocop link using the default linter. It's a tooltip that has the link which causes this error.

**Comment by puppycodes** [comment]
+1

**Comment by AntonAdigamov** [comment]
+1

**Comment by Jemisson** [comment]
I'm facing same issue any clue?

**Comment by rocwrxsti** [comment]
+1

**Comment by ngelx** [comment]
+1

**Comment by ghaant** [comment]
+1

**Comment by ghaant** [comment]
+1
